### ISSUE TITLE
Download link is broken

### ISSUE THREAD

**Issue by wangzhangup** [KaiyangZhou/deep-person-reid#1]
densenet121_xent_htri_mars.pth.tar was not found on this server

”densenet121_xent_htri_mars.pth.tar“ ’s link is broken

**Comment by KaiyangZhou** [comment]
Thank you for spotting this issue, I have fixed it. Could you please check and let me know if this model is downloadable and can be used normally?

**Comment by wangzhangup** [comment]
@KaiyangZhou The model works fine. 
But may be a list bug, line 18, in file 'dataset_loader.py'. 'fpath'-->'img_path'?

**Comment by KaiyangZhou** [comment]
Yes, you are right. It was a typo. Fixed now.

**Comment by OmarHamdoun** [comment]
hi   
densenet121_xent_market1501.pth.tar  doesn't extract give me error UTF-8

**Comment by KaiyangZhou** [comment]
@OmarHamdoun How did you load the model? I found no error when loading it
```python
net = DenseNet121(751) # market1501 has 751 identities in train data
model = torch.load('densenet121_xent_market1501.pth.tar')
net.load_state_dict(model['state_dict'])
```

**Comment by OmarHamdoun** [comment]
I have just use  use this  
python3 train_img_model_xent.py -d market1501 -a resnet50 --evaluate --resume saved-models/densenet121_xent_market1501.pth.tar --save-dir log/resnet50-xent-market1501 --test-batch 32 
==========
Args:Namespace(arch='resnet50', dataset='market1501', eval_step=-1, evaluate=True, gamma=0.1, gpu_devices='0', height=256, lr=0.0003, max_epoch=60, print_freq=10, resume='saved-models/densenet121_xent_market1501.pth.tar', save_dir='log/resnet50-xent-market1501', seed=1, start_epoch=0, stepsize=20, test_batch=32, train_batch=32, use_cpu=False, weight_decay=0.0005, width=128, workers=4)
==========
Currently using GPU 0
Initializing dataset market1501
=> Market1501 loaded
Dataset statistics:
  ------------------------------
  subset   | # ids | # images
  ------------------------------
  train    |   751 |    12936
  query    |   750 |     3368
  gallery  |   751 |    15913
  ------------------------------
  total    |  1501 |    32217
  ------------------------------
Initializing model: resnet50
Model size: 25.04683M
Loading checkpoint from 'saved-models/densenet121_xent_market1501.pth.tar'
Traceback (most recent call last):
  File "train_img_model_xent.py", line 248, in <module>
    main()
  File "train_img_model_xent.py", line 133, in main
    checkpoint = torch.load(args.resume)
  File "/home/vision/.local/lib/python3.5/site-packages/torch/serialization.py", line 267, in load
    return _load(f, map_location, pickle_module)
  File "/home/vision/.local/lib/python3.5/site-packages/torch/serialization.py", line 420, in _load
    result = unpickler.load()
UnicodeDecodeError: 'ascii' codec can't decode byte 0x91 in position 1: ordinal not in range(128)

**Comment by KaiyangZhou** [comment]
@OmarHamdoun 
Change `-a resnet50` to `-a densenet121` because the model you load is `densenet121_xent_market1501`.
In terms of the `UnicodeDecodeError`, I had a quick search on google and [this post](https://stackoverflow.com/questions/21129020/how-to-fix-unicodedecodeerror-ascii-codec-cant-decode-byte) might help you.
