### ISSUE TITLE
Problem evaluating Market

### ISSUE THREAD

**Issue by akonstantinou** [KaiyangZhou/deep-person-reid#10]
When i try to evaluate market i get the following error

 File "/home/konstantinou/virtualenvs/pytorch_python2/local/lib/python2.7/site-packages/torch/nn/modules/linear.py", line 49, in reset_parameters
    stdv = 1. / math.sqrt(self.weight.size(1))
RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)

The command i use is the following
python train_img_model_xent.py -d market1501 -a resnet50 --evaluate --resume saved-models/resnet50_xent_market1501.pth.tar --save-dir log/resnet50m_xent_market1501 --test-batch 32

**Comment by KaiyangZhou** [comment]
Please provide the full error log. What changes did you make to the code?

**Comment by akonstantinou** [comment]
I did not make any changes. train_vid_model works fine, but i cant run train_img_model. Here is the full log

==========
Args:Namespace(arch='resnet50', dataset='market1501', eval_step=-1, evaluate=True, gamma=0.1, gpu_devices='0', height=256, lr=0.0003, max_epoch=15, optim='adam', pool='avg', print_freq=10, resume='saved-models/resnet50_xent_prid.pth.tar', root='data', save_dir='log/resnet50-xent-market', seed=1, seq_len=15, start_epoch=0, stepsize=5, test_batch=32, train_batch=32, use_cpu=False, weight_decay=0.0005, width=128, workers=4)
==========
Currently using GPU 0
Initializing dataset market1501
=> Market1501 loaded
Dataset statistics:
  ------------------------------
  subset   | # ids | # images
  ------------------------------
  train    |     0 |        0
  query    |   750 |     3368
  gallery  |   751 |    15913
  ------------------------------
  total    |   750 |    19281
  ------------------------------
Initializing model: resnet50
Traceback (most recent call last):
  File "train_vid_model_xent.py", line 279, in <module>
    main()
  File "train_vid_model_xent.py", line 132, in main
    model = models.init_model(name=args.arch, num_classes=dataset.num_train_pids, loss={'xent'})
  File "/home/konstantinou/code/deep-person-reid/models/__init__.py", line 34, in init_model
    return __factory[name](*args, **kwargs)
  File "/home/konstantinou/code/deep-person-reid/models/ResNet.py", line 16, in __init__
    self.classifier = nn.Linear(2048, num_classes)
  File "/home/konstantinou/virtualenvs/pytorch_python2/local/lib/python2.7/site-packages/torch/nn/modules/linear.py", line 46, in __init__
    self.reset_parameters()
  File "/home/konstantinou/virtualenvs/pytorch_python2/local/lib/python2.7/site-packages/torch/nn/modules/linear.py", line 49, in reset_parameters
    stdv = 1. / math.sqrt(self.weight.size(1))
RuntimeError: dimension out of range (expected to be in range of [-1, 0], but got 1)

**Comment by KaiyangZhou** [comment]
You loaded `resnet50_xent_prid.pth.tar`, whose classifier has a different number of output units with Market. Please use `resnet50_xent_market1501.pth.tar`.

**Comment by akonstantinou** [comment]
Thats not the problem, i made a mistake while trying to find a solution. It still happens even with the correct model.
