### ISSUE TITLE
Query:Own Dataset

### ISSUE THREAD

**Issue by NightFury10497** [KaiyangZhou/deep-person-reid#100]
For my own dataset, do i need  to **train** over it , or i can directly **test** it over the pre-trained model?

**Comment by ggalan87** [comment]
You can definitely test with your data over a pre-trained model, but in general performance would be worse as compared to the case that you also train on your own dataset. There are recent domain adaptation methods (such as https://arxiv.org/abs/1711.07027) which propose solutions for transfering existing knowledge (i.e. pre-trained models) to new datasets.

**Comment by NightFury10497** [comment]
I tried PRID dataset, i cant find the splits json file, help me out!

**Comment by KaiyangZhou** [comment]
@NightFury10497 https://github.com/KaiyangZhou/deep-person-reid/blob/master/DATASETS.md

**Comment by NightFury10497** [comment]
@KaiyangZhou  I  downloaded that file , it does not have a split json file in it.

**Comment by KaiyangZhou** [comment]
[this one](http://www.eecs.qmul.ac.uk/~kz303/deep-person-reid/datasets/prid2011/splits_prid2011.json)

**Comment by ciwei123** [comment]
@KaiyangZhou Thanks for your sharing. I have trained the HACNN model in Market-1501 for 300 epoch.I have got the similar test result in MODEL_ZOO.But I test the MOT16(Multi-object tracking datsaset 2016) using this model, I did not get the desired result.The model only discovers the identity between consecutive frames，can't find identity after a few frames. Could you give me some suggestions for solving this problem?Maybe I should use the results of video reid training?Thank you very much!!
