### ISSUE TITLE
Question about RandomIdentitySampler

### ISSUE THREAD

**Issue by ming1144** [KaiyangZhou/deep-person-reid#103]
I'm reading RandomIdentitySampler that you write

The basic of RandomIdentitySampler sample K images from N identities
But your code sample more than K images when the identities have several times images than K

Have you compare these two kind of RandomIdentitySampler's effects?

**Comment by KaiyangZhou** [comment]
> But your code sample more than K images when the identities have several times images than K

What do you mean? As I can see, the code samples K images for each of N identities in each batch.

Can you point out which line you are referring to?

**Comment by ming1144** [comment]
Sorry for didn't clarify the question

[https://github.com/michuanhaohao/AlignedReID/blob/master/util/samplers.py](url)
This is the another kind of randomIdentitySampler that I'm talking about

for example
if there are 10 image for an identity
and let batch_identity = 4
the above sampler will sample only one set of  4 images and discard the other 6 images
while your sampler will sample two sets of 4 images

The concept of RandomIdentitySampler is same but the training time has huge difference.
I'm not sure will this affect the training step.

**Comment by KaiyangZhou** [comment]
I see. That one comes from the open-reid. It does not use all images in an epoch because it only picks K images for each identity while ignoring the rest. In that case, the training time for each epoch is of course short. But you need to increase the max-epoch to ensure that most images will be visited during training.

**Comment by ming1144** [comment]
@KaiyangZhou Thanks for replying.

Returning to my question,
Have you ever test the results of these two types of RandomIdentitySampler with same Epoches?

**Comment by KaiyangZhou** [comment]
no, I don't think this needs to be verified.
