### ISSUE TITLE
MSMT17 dataset version updated?

### ISSUE THREAD

**Issue by d-li14** [KaiyangZhou/deep-person-reid#104]
@KaiyangZhou Thanks for your implementation to advance further research in Re-ID. I noticed that the MSMT17 dataset has been upgraded to version 2 on the official website. Would you consider updating the relevant data loader in your code?

**Comment by KaiyangZhou** [comment]
please leave a link here to point out where the changes are made, i will do it next week

**Comment by d-li14** [comment]
refer to their homepage http://www.pkuvmc.com/publications/msmt17.html, the MSMT17_v2.zip has been in place of the original MSMT17_v1.tar.gz. I can't figure out the differences between them because I don't have the v1 at hand which has been removed.

**Comment by KaiyangZhou** [comment]
Ok, I will figure out.

Is there anything incompatible using the current code with msmt_v2? If so, can you show me the log?

**Comment by d-li14** [comment]
I suppose primarily some misspecification due to the change of folder names, but I am not totally sure for lack of v1 data. So I hope you figure it out and update the data loader and README accordingly in case of misleading.

**Comment by KaiyangZhou** [comment]
got it

**Comment by KaiyangZhou** [comment]
Done.

The following codes are added to `msmt17.py`:
```
_TRAIN_DIR_KEY = 'train_dir'
_TEST_DIR_KEY = 'train_dir'
_VERSION = {
    'MSMT17_V1': {
        _TRAIN_DIR_KEY: 'train',
        _TEST_DIR_KEY: 'test',
    },
    'MSMT17_V2': {
        _TRAIN_DIR_KEY: 'mask_train_v2',
        _TEST_DIR_KEY: 'mask_test_v2',
    }
}
```

V1 and V2 only differ in folder name. The images should be the same.

**Comment by AMANKB** [comment]
why the homepage  http://www.pkuvmc.com/publications/msmt17.html can't be visited? Can anyone provide the correct website address?

**Comment by amandayeyan** [comment]
My first time encountered "killed"??  What kind of error is this?

##### Evaluating msmt17 (target) #####
Extracting features from query set ...
Done, obtained 11659-by-1280 matrix
Extracting features from gallery set ...
Done, obtained 82161-by-1280 matrix
Speed: 0.0095 sec/batch
Computing distance matrix with metric=cosine ...
Computing CMC and mAP ...
Killed

**Comment by KaiyangZhou** [comment]
@amandayeyan memory problem due to large matrix?

**Comment by amandayeyan** [comment]
Yes, I believe so. Due to large number of query data in msmt17.

**Comment by KaiyangZhou** [comment]
one way to circumvent this issue is to set a maximum threshold for number of instances for distance matrix computation, and split the computation if necessary

**Comment by gailysun** [comment]
> why the homepage http://www.pkuvmc.com/publications/msmt17.html can't be visited? Can anyone provide the correct website address?

same problem. can not open this url

**Comment by KaiyangZhou** [comment]
@gailysun many reid datasets are down, potentially due to privacy or legal issues

I suggest directly contacting the datasets' authors for help
