### ISSUE TITLE
About the accuracy of PCB model

### ISSUE THREAD

**Issue by jiao133** [KaiyangZhou/deep-person-reid#105]
Thanks for sharing. I am reproducing the PCB model, but I have tried a variety of parameter adjustment methods that can not achieve the accuracy of the original paper. My best rank1 result of pcb_p6 is 80.3%. I would like to ask what is the accuracy of your PCB model? Thanks.

**Comment by KaiyangZhou** [comment]
Around 91% as I can remember (not close to the original paper). I used the param setting of resnet50_fc512 (see model zoo).

**Comment by jiao133** [comment]
thanks
