### ISSUE TITLE
add new model into repo

### ISSUE THREAD

**Issue by hoangtuanvu** [KaiyangZhou/deep-person-reid#113]
Recently, EANet has been proposed and this one has achieved SOTA on Market, CUHK03. Can you add new model to this repo? Thank you!

**Comment by KaiyangZhou** [comment]
Thanks for your suggestion. It's an interesting paper and the results are indeed impressive.

As there is an official implementation as mentioned in the paper abstract, I would suggest using that one for better reproduction.

I will try to add EANet here. Not sure if it can fit in this repo as it has 3rd-party models and a customized training procedure.
