### ISSUE TITLE
Updating i-LIDS and PRID (both are image-based)

### ISSUE THREAD

**Issue by KaiyangZhou** [KaiyangZhou/deep-person-reid#115]
Download link: http://www.eecs.qmul.ac.uk/~jason/data/i-LIDS_Pedestrian.tgz

**Comment by KaiyangZhou** [comment]
References:
1. [Associating Groups of People](http://www.eecs.qmul.ac.uk/~sgg/papers/ZhengGongXiang_BMVC09.pdf)
2. [One-Shot Metric Learning for Person Re-identification](http://openaccess.thecvf.com/content_cvpr_2017/papers/Bak_One-Shot_Metric_Learning_CVPR_2017_paper.pdf)
3. [Person Re-Identification by Descriptive and Discriminative Classification](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.383.7106&rep=rep1&type=pdf)

**Comment by KaiyangZhou** [comment]
See [DATASETS.md](https://github.com/KaiyangZhou/deep-person-reid/blob/master/DATASETS.md) for how to prepare and build the datasets.

**Comment by pribadihcr** [comment]
> Download link: http://www.eecs.qmul.ac.uk/~jason/data/i-LIDS_Pedestrian.tgz

Hi, this link doesn't work anymore.
