### ISSUE TITLE
is there a document which explain the project?

### ISSUE THREAD

**Issue by chanajianyu** [KaiyangZhou/deep-person-reid#117]

**Comment by KaiyangZhou** [comment]
Say the max rank you want to compute is 100, following the steps
- add argument `max_rank=100` in the [evaluate interface](https://github.com/KaiyangZhou/deep-person-reid/blob/master/train_imgreid_xent.py#L236).
- the returned `cmc` has length `len(cmc) = 100`, you can simple do `plot(cmc)`

**Comment by chanajianyu** [comment]
thank you very much! I have a new question. in the video reid, if we give a person video , how to get the  visual  ranking video?

**Comment by chanajianyu** [comment]
ok, I find it!

**Comment by KaiyangZhou** [comment]
Did not notice this title change. Pls open new issue next time for new topic.

Regarding the doc, I have been thinking about this, but (1) I think it's not too difficult to grasp the overall structure of the framework, as digging into each API shown in the main script like `train_imgreid_xent.py` should be ok; (2) I am not very happy with the current interface so I am considering wrapping functions in such a way that there is only one `main.py`. For this, the docs should be rewritten.

Anyway, when the `1.0.0` version comes out, the APIs will be more stable.

**Comment by KaiyangZhou** [comment]
the documentation is out
