### ISSUE TITLE
what the expected output in results folder when visualize the ranks?

### ISSUE THREAD

**Issue by muna-cs** [KaiyangZhou/deep-person-reid#118]
when visualizing the ranks I have gotten a probe folder and 20 gallery folder, there is more than one person identity in both the gallery and probe folder.

my question is: How can I make sure the results are correct? can you explain the expected results?

Thank you.

**Comment by KaiyangZhou** [comment]
I assume you visualized video reid's results. The visualization is based on the distance matrix you computed, so the results should be correct.

The gallery folders are put in the order based on the rank. You can infer the rank by looking at the folder name with sth like 'gallery_topX_NAME' where X denotes rank and NAME is the tracklet name. See [here](https://github.com/KaiyangZhou/deep-person-reid/blob/master/torchreid/utils/reidtools.py#L55) for the details.
