### ISSUE TITLE
cuhk03.py loadmat func?

### ISSUE THREAD

**Issue by Adorablepet** [KaiyangZhou/deep-person-reid#120]
I want to ask, I downloaded cuhk03_new_protocol_config_detected.mat，but appeared 'unknow mat file type ,version 105 ,116' when running cuhk03.py

**Comment by KaiyangZhou** [comment]
Can you show the full error log and provide more details?

**Comment by Adorablepet** [comment]
@KaiyangZhou In fact, when I was training the dataset of cuhk03, I downloaded 2 mat files according to your prompts, and when I was running, prompted me to loadmat(self.split_new_det_mat_path)（cuhk03.py 242 line）, the error ''unknow mat File type , version 105 , 116''. I want to ask, is there a problem with my downloaded mat file, my environment is pytorch0.4.1, python3.6，thanks.

**Comment by KaiyangZhou** [comment]
The mat files should be fine.

I have never met such problem even I run my code with python3. I am thinking whether it is because your `scipy`'s version is too low? What is the version of `scipy` (type `pip3 list`)?

**Comment by Adorablepet** [comment]
@Adorablepet scipy's version is 1.2.1.What do you mean with ’type pip3 list‘？I used the command with conda install scipy.

**Comment by Adorablepet** [comment]
@KaiyangZhou  scipy's version is 1.2.1.What do you mean with ’type pip3 list‘？I used the command with conda install scipy.

**Comment by KaiyangZhou** [comment]
that's a weird issue and I cannot reproduce your error without further info shown in the full error log

**Comment by Adorablepet** [comment]
@KaiyangZhou first,thank you very much.I found the problem, I downloaded the mat file, there is a problem, I downloaded it again and it is OK.
