### ISSUE TITLE
Handle UnicodeDecodeError (with python3)

### ISSUE THREAD

**Issue by KaiyangZhou** [KaiyangZhou/deep-person-reid#121]
The new commit https://github.com/KaiyangZhou/deep-person-reid/commit/25c64fdd9a89337c9eacac730912ba275dbaae8c adds code to handle **UnicodeDecodeError** when using python3 to load model saved with python2.

Major change:
```python
def load_checkpoint(fpath):
    map_location = None if torch.cuda.is_available() else 'cpu'
    try:
        checkpoint = torch.load(fpath, map_location=map_location)
    except UnicodeDecodeError:
        pickle.load = partial(pickle.load, encoding="latin1")
        pickle.Unpickler = partial(pickle.Unpickler, encoding="latin1")
        checkpoint = torch.load(fpath, pickle_module=pickle, map_location=map_location)
    except Exception:
        print('Unable to load checkpoint from "{}"'.format(fpath))
        raise
    return checkpoint
```

Credit to https://github.com/KaiyangZhou/deep-person-reid/issues/43#issuecomment-411266053.

**Comment by KaiyangZhou** [comment]
P.S. this should really have been done earlier. Sorry for any inconvenience.

**Comment by gceboh** [comment]
@KaiyangZhou The difference between Python 2 and Python 3 (including integer divison problem ,etc.) may cause some bugs which are hard to spot and fix.
Therefore,I suggest write "Python 2 is recommended and full tested" in `README.md`.

**Comment by KaiyangZhou** [comment]
I have been using python3 with this project and do not find any significant bugs.

Is there any bug happening when you use python3? Let me know and I will fix it

**Comment by gceboh** [comment]
Just some small worry,because [python 2 is recommended in early version](https://github.com/KaiyangZhou/deep-person-reid/blame/v0.1.0/README.md#L18) .
No worry now.

Currently no bugs found. Thanks.
