### ISSUE TITLE
how to train your net

### ISSUE THREAD

**Issue by 18842505953** [KaiyangZhou/deep-person-reid#123]
谢谢你的程序。如果我想试着运行一下你的现成的代码看一下效果，是否直接参考你的README.txt就可以。还有在我运行train_imgreid_xent.py 文件时总是提示'Cython evaluation is UNAVAILABLE, which is highly recommended'这个要怎么解决呢。

**Comment by KaiyangZhou** [comment]
yes, following the readme tutorial is ok

you don't have to install the cython lib, but it can accelerate the evaluation speed (on market, from 3 
mins to 7 secs), the python-based eval code will give you the same result

**Comment by 18842505953** [comment]
but,i have the cython lib, may be something else wrong ,you mean i dont have to fix this problem?

the way of training video-reid is the same with image-reid?

thanks for all

**Comment by KaiyangZhou** [comment]
because you did not do `make` to generate the executable file, pls follow the **Installation** section

> the way of training video-reid is the same with image-reid?

almost the same
