### ISSUE TITLE
Traceback(most recent call last)

### ISSUE THREAD

**Issue by Vincy-L** [KaiyangZhou/deep-person-reid#124]
The python version in my computer is python3.7,with pytorch-cpu and anaconda3.when I run the code that you show in the part “train” with”—use-cpu” instead of”—gpu_devices 0”,it throws errors like this”
Traceback(most recent call last):
File”train_imgreid_xent.py”,line 251,in <module>
Main()
File”train_imgreid_xent.py”,line 106,in main
Train(epoch,model,criterion,optimizer,trainloader,use_gpu)
File”train_imgreid_xent.py”,line 160,in Train
Loss.backward()
File”/home/Vince/anaconda3/lib/python3.7/site-packages/torch/tensor.py”,line 102,in backward
Torch.autograd,backward(self,gradient,retain_graph,create_graph)
File”/home/Vince/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py”,line 90,in backward
 Allow_unreachable=true) # allow_unreachable flag
File”/home/Vince/anaconda3/lib/python3.7/site-packages/torch/utility/data loader.py”,line 274,in handler
 _error_if_any_worker_fails()

I’m a new learner in deep-person-Reid,and it’s my first time to study python,I really hope your generous help.

Best wishes 
Vincy

**Comment by KaiyangZhou** [comment]
I use Python 3.7.2 and torch `1.0.1.

Could not reproduce your error.

What torch version do you have? I tried to identify the cause but could not locate `torch/utility/data loader.py` because the `dataloader.py` is under `torch/utils/data` on my machine.

Can you try re-installing the latest torch if it's not the latest version?

**Comment by Vincy-L** [comment]
I checked the version on my computer,it is torch 1.0.1.
But still thanks for your reply, i will re-install the torch and find out the reason.

**Comment by KaiyangZhou** [comment]
Ok, cool. Btw, please use the latest code in this repo.

If you find out what causes the error, let me know.

**Comment by Vincy-L** [comment]
In my case , i find that it caused by out of memory of machine. Then I change the train_batch size parameter to a smaller one,it doesn’t throw errors anymore.
