### ISSUE TITLE
The  LIDS-VID test error

### ISSUE THREAD

**Issue by tangyuanhenyuan** [KaiyangZhou/deep-person-reid#128]
Thanks a lot for your code!

I met this error while evaluating the LIDS-VID dataset.

Traceback (most recent call last):
  File "train_imgreid_xent.py", line 289, in <module>
    main()
  File "train_imgreid_xent.py", line 128, in main
    rank1 = test(model, queryloader, galleryloader, use_gpu)
  File "train_imgreid_xent.py", line 229, in test
    for batch_idx, (imgs, pids, camids, _) in enumerate(queryloader):
ValueError: not enough values to unpack (expected 4, got 3)

Thank you for your attention!

**Comment by KaiyangZhou** [comment]
`train_imgreid_xent ` is supposed to support image dataset only, you need to use `train_vidreid_xent`

**Comment by tangyuanhenyuan** [comment]
> `train_imgreid_xent ` is supposed to support image dataset only, you need to use `train_vidreid_xent`

Thank you so much for your reply!
