### ISSUE TITLE
训练之后model.pth.tar-不出现的问题

### ISSUE THREAD

**Issue by 18842505953** [KaiyangZhou/deep-person-reid#129]
我使用train_vidreid_xent.py+resnet50+mars。训练之后保存在save_dir后面填写的地址，而文件夹中只有log_train.txt记录训练信息，但是没有模型和参数的model.pth.tar-那个文档，是怎么回事呢，会提示cuda out of memory 是不是这个原因导致的呢？？

**Comment by KaiyangZhou** [comment]
If the error shows `out of memory`, it means the code crashes during training. I guess your batch size is set to a large number which cannot fit into your gpu memory.
