### ISSUE TITLE
我想测试自己的数据

### ISSUE THREAD

**Issue by 18842505953** [KaiyangZhou/deep-person-reid#139]
如果我用mars训练网络之后想运行用来测试自己的数据集，那么我的自己制作的测试集要跟mars自带的测试集格式方面保持一直吗？

**Comment by KaiyangZhou** [comment]
All you need is to make sure you generate `train`, `query` and `gallery` that are list containing tuples of `(img_paths, pid, camid)`.

Please have a look at this part https://kaiyangzhou.github.io/deep-person-reid/user_guide.html#use-your-own-dataset
