### ISSUE TITLE
 No module named 'torchreid.utils'

### ISSUE THREAD

**Issue by 18842505953** [KaiyangZhou/deep-person-reid#141]
when i run the program in cmd,a error come out: No module named 'torchreid.utils'.why

**Comment by KaiyangZhou** [comment]
I guess `torchreid` is not successfully installed.

Can you give more details?

**Comment by 18842505953** [comment]
我按照你的方法，运行了 setup.py 文件，此外我还需要做什么吗

**Comment by KaiyangZhou** [comment]
that's all, now `torchreid` can be imported, please refer to the documentation for more details

**Comment by 18842505953** [comment]
我试过了，还是一样的问题，NO module   ,这和环境有关系吗

**Comment by KaiyangZhou** [comment]
what's your system

**Comment by 18842505953** [comment]
i use   win10  + anaconda + vscode

**Comment by 18842505953** [comment]
是不是因为包所在目录不同导致不能成功导入呢

**Comment by 18842505953** [comment]
现在的报错是No module named 'torchreid.utils'

**Comment by KaiyangZhou** [comment]
i havn't tried the code on windows system yet, so could not provide useful information

**Comment by 18842505953** [comment]
all right  ,thanks for all

**Comment by 18842505953** [comment]
speed = int(progress_size / (1024 * duration))
ZeroDivisionError: float division by zero,是下载错误吗

**Comment by PROMETHUES** [comment]
@18842505953 Copy all the python files under "scripts" to the root path (maybe is "deep-person-reid") then run the commend line of training OSNet on Market1501. This should be worked with the environment of Win10 + Anaconda

**Comment by KaiyangZhou** [comment]
@PROMETHUES so in win10 the torchreid package cannot be found?

**Comment by chernbo** [comment]
![image](https://user-images.githubusercontent.com/47548611/92676454-28785a80-f354-11ea-9e45-4370c00e8b6f.png)
I can import torchreid,but I can't use python command.

**Comment by chernbo** [comment]
![image](https://user-images.githubusercontent.com/47548611/92677918-780c5580-f357-11ea-89c5-169ed834b2b5.png)
I can import torchreid,but I can't use python command.

**Comment by KaiyangZhou** [comment]
@chernbo hmm, it seems to be a system problem rather than an issue caused by the code

**Comment by chernbo** [comment]
@KaiyangZhou Thanks for your answer, I am using windows10.  I am trying to use torchreid under linux to see if it will find similar errors.

**Comment by rekharchandran** [comment]
@chernbo how did you solve this? do you remember?

**Comment by weihong0827** [comment]
I download the package using pip install on coblab, and when i try to import modules using this format `from torchreid.data.datasets import ImageDataset` I will get  ModuleNotFoundError: No module named 'torchreid.data' but i can use the data manager by  `torchreid.data.ImageDataset`

**Comment by nbvictory** [comment]
I have issues with these two statements at runtime
from torchreid.utils import FeatureExtractor
from torchreid.utils.tools import download_url
    from torchreid.utils import FeatureExtractor
ModuleNotFoundError: No module named 'torchreid.utils'
I have used many methods in the 1.0 version, but there are still issues. I'm not sure if it's a path issue

**Comment by motherflunker** [comment]
'torchreid.reid.utils' THIS WILL WORK.
