### ISSUE TITLE
Memory Error test MARS

### ISSUE THREAD

**Issue by RaviShivam** [KaiyangZhou/deep-person-reid#144]
I am getting a Memory Error when I try to test my (trained model) on the MARS dataset. This happens because my RAM get loaded too much (I verified this with htop). However, I have a machine with 62gb of RAM, which I think should be enough for the evaluation. Is there is way to fix this? I get the error in the line 106 of `rank.py`:

`matches = (g_pids[indices] == q_pids[:, np.newaxis]).astype(np.int32)`

I hope you could help me solve this issue.

PS I really appreciate this repository. Thanks for the great work!!

**Comment by KaiyangZhou** [comment]
which commit are you using?

can you provide the command to reproduce your case?

**Comment by gceboh** [comment]
Please try to evaluate on other data sets, like `ilids-vid`,`DukeMTMC-VideoReID`,and see if this error happen again.
Also, please provide your log which contains error info .

**Comment by RaviShivam** [comment]
Thank you both for replying. The error seemed to be coming from my part since I was using a `ImageSoftmaxEngine` instead of the `VideoSoftwareEngine`. I don't face the error anymore.
