### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by zhenght17** [KaiyangZhou/deep-person-reid#146]
Hi,
When I ran the install code "python3 set_up.py install", the following error occured, can you tell me what to do to install torchreid in perspective？

user@user:~/deep-person-reid$ sudo python3 setup.py install 
[sudo] password for user: 
/home/user/deep-person-reid/torchreid/metrics/rank.py:17: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.
  'Cython evaluation (very fast so highly recommended) is '
Traceback (most recent call last):
  File "setup.py", line 39, in <module>
    version=find_version(),
  File "setup.py", line 16, in find_version
    exec(compile(f.read(), version_file, 'exec'))
  File "torchreid/__init__.py", line 8, in <module>
    from torchreid import (
  File "/home/user/deep-person-reid/torchreid/__init__.py", line 8, in <module>
    from torchreid import (
  File "/home/user/deep-person-reid/torchreid/engine/__init__.py", line 4, in <module>
    from .engine import Engine
  File "/home/user/deep-person-reid/torchreid/engine/engine.py", line 20, in <module>
    class Engine(object):
  File "/home/user/deep-person-reid/torchreid/engine/engine.py", line 205, in Engine
    use_metric_cuhk03=False, ranks=[1, 5, 10, 20]):
TypeError: 'no_grad' object is not callable

I have already installed pytorch and cython by "sudo apt-get install cython".
Thanks!

**Comment by KaiyangZhou** [comment]
I think it's due to the pytorch version which is incompatible. Please install pytorch>=1.0 (at least >=0.4.1)

Let me know how it goes.

**Comment by KaiyangZhou** [comment]
it means the cython evaluation package is not installed successfully, try to redo the install

**Comment by zhenght17** [comment]
Alright, I just uninstalled cython and installed it again, problem solved.
Thanks a lot!

**Comment by raretomato** [comment]
> it means the cython evaluation package is not installed successfully, try to redo the install

I installed TorchReID on another computer (win10, anaconda3) today with a new installation method (option 2) using conda.

  After that, the message "rank.py:17: UserWarning: Cython evaluation (very fast) in unavailable, now use python evaluation" keeps appearing. I erased Cython and reinstalled it with the latest version, but it is still intact.

My Cython version is 0.29.7. Is not it compatible with the latest version of Cython?

**Comment by cynthia8a** [comment]
I have the same issue with the same configuration (win 10, anaconda3)

**Comment by Joxis** [comment]
I too have the same issue with the same configuration (windows 10, anaconda 3)

**Comment by alexbarnadas** [comment]
I have the same problem I tried in an ubuntu and a windows machine, both have the same problem.
