### ISSUE TITLE
A question on the Inception A/B's structure in HACNN 

### ISSUE THREAD

**Issue by doublepoints** [KaiyangZhou/deep-person-reid#147]
Hi, I am trying to use the hacnn model for learning.
However, I have found that the structure of inception A/B blocks is different from the one proposed on Inception V4 paper.
Would you please tell me why you use this kind of structures?
Thank you very much.

**Comment by KaiyangZhou** [comment]
It's mentioned in the overview where the inception blocks are adopted from "Learning deep feature representations with domain guided dropout for person re-identification" (https://github.com/Cysu/dgd_person_reid).

**Comment by doublepoints** [comment]
Thank you very much for your reply.
