### ISSUE TITLE
Tensor shape in loss

### ISSUE THREAD

**Issue by kerryliu28** [KaiyangZhou/deep-person-reid#150]
Hey, I have checked out the torchreid/losses/cross_entropy_loss.py and found a place confused me a lot. 

In forwad method of CE class, targets is supposed to be with shape  (num_classes). But I think the shape should be batch_size to make sense. Please point it out if I'm wrong. Thx!

**Comment by ggalan87** [comment]
Yes, you are correct. I just confirmed it, that it is a typo error.

**Comment by KaiyangZhou** [comment]
just fixed, thx
