### ISSUE TITLE
the means of some parameters

### ISSUE THREAD

**Issue by 18842505953** [KaiyangZhou/deep-person-reid#152]
i dont understand some parameters ,i have seen your note in default_parser.py,but i still dont understand:
such as:
--fixbase-epoch
--open-layers
--new-layers
--base-lr-mult

**Comment by KaiyangZhou** [comment]
pls have a look at this https://kaiyangzhou.github.io/deep-person-reid/user_guide.html#do-two-stepped-transfer-learning

**Comment by 18842505953** [comment]
谢谢
