### ISSUE TITLE
The size of input image

### ISSUE THREAD

**Issue by ciwei123** [KaiyangZhou/deep-person-reid#153]
@KaiyangZhou The input image is 224*224 in ShffleNet paper, but in your code, the input is 256*128, why about it ? What is the reason for this change?Thank you very much!!

**Comment by KaiyangZhou** [comment]
256x128 works better for reid as it better keeps the aspect ratio (person height is longer than the width)

**Comment by ciwei123** [comment]
@KaiyangZhou Thanks for your reply.　Can the network accept input of any size?　If so, what structure guarantees this？　I know that the FC structure requires a fixed length of input.

**Comment by KaiyangZhou** [comment]
> Can the network accept input of any size?

Yes

> what structure guarantees this？

global average pooling
