### ISSUE TITLE
Can the code of pytorch 0.3 version be shared as well?

### ISSUE THREAD

**Issue by ChunfeiMa** [KaiyangZhou/deep-person-reid#16]

**Comment by KaiyangZhou** [comment]
Sorry, the code has been entirely updated to 0.4.0.

If you wanna use 0.3.0, you can simply wrap torch tensors with `Variable` in , e.g., `train_img_model_xent.py`.

**Comment by ChunfeiMa** [comment]
@KaiyangZhou 
Got it !! Thanks a lot!
