### ISSUE TITLE
How to import evaluate_cy?

### ISSUE THREAD

**Issue by shanqq377** [KaiyangZhou/deep-person-reid#163]
try:
    from torchreid.metrics.rank_cylib.rank_cy import evaluate_cy
    IS_CYTHON_AVAI = True
except ImportError:
    IS_CYTHON_AVAI = False
    warnings.warn(
        'Cython evaluation (very fast so highly recommended) is '
        'unavailable, now use python evaluation.'
    )

**Comment by KaiyangZhou** [comment]
you just found it

**Comment by alexbarnadas** [comment]
Sorry could you be more specific on what is the solution? I have Cython installed but I still get this warning. My code runs at 6FPS. Thank you.
