### ISSUE TITLE
Why evaluation is order sensitive?

### ISSUE THREAD

**Issue by ArchNew** [KaiyangZhou/deep-person-reid#164]
If I understand the evaluation functions (eval_market1501 and eval_cuhk03, their search for the matching between query and gallery is related to the query order. They first find the match for the first instance in the query, then the second, then the third...

I don't know if it is how the papers agree on, or just your implementation. In my humble opinion, isn't it better to match them according to the sheer L2 distance? Match the smallest distance between query and gallery, delete both, and then match the smallest distance in the remainders, then delete them again...so on and so forth, until there's no query or gallery instance left.

Is there any reason to match them according to the query order?

**Comment by KaiyangZhou** [comment]
The matching is performed for each query independently. Intuitively, for each query, the gallery is ranked in the order of increasing distance, so the first position represents rank-1, and so on and so forth.
