### ISSUE TITLE
Do you have plan to reproduce the Visiblility-aware Part Model (VPM)?

### ISSUE THREAD

**Issue by ArchNew** [KaiyangZhou/deep-person-reid#167]
In CVPR 2019, there's a paper done by Tsinghua, called 'Perceive Where to Focus: Learning Visibility-aware Part-level Features for Partial Person Re-identification.' It performs very well on partially occluded people. It is also on par with the state-of-the-art on no occlusion people. Due to its stunning performance on 30% and less occluded people, I think it will have many applications on various tasks.

Unfortunately, the author doesn't release any code with the paper.

**Comment by KaiyangZhou** [comment]
If I have time I could try to reproduce those new papers. But don't count on me.
