### ISSUE TITLE
Doubt on the large performance improvement of appending FC after ResNet50

### ISSUE THREAD

**Issue by WeilamChung** [KaiyangZhou/deep-person-reid#171]
First, we would thank you for this awesome work.
In the model zoo, resnet50 obtains Top1 87.9% and mAP 70.4% on Market1501. After appending FC after resnet50, resnet50_fc512 achieves Top1 90.8% and mAP 75.3%, which significantly outperforms resnet50.
In my implementations, the two settings have similar performance.
After running this code, we find the feature size is different for resnet50 and resnet50_fc512. resnet50 is 8x4, while resnet50_fc512 is 16x8. Specifically, last_stride=2 for resnet50, while last_stride=1 for resnet50_fc512.
The performance is similar after using the same settings.

**Comment by KaiyangZhou** [comment]
What's the performance you got for these two models?

Does the scripts in https://kaiyangzhou.github.io/deep-person-reid/MODEL_ZOO.html not make you reproduce the results?

**Comment by WeilamChung** [comment]
Thanks for your good implementation and I do reproduce the results.
But, in my codes, the two settings obtain similar results.
Thus, I check the scripts in your implementation and find the feature size is different for resnet50 and resnet50_fc512, which may lead to the large performance improvement of appending FC.

非常感谢。

就是在我的代码里resnet50后加个FC和不加FC准确率变动不大，所以查了下你的代码里，发现resnet50和resnet50_fc512用的特征图大小不一样，即resnet50是last_stride=2，resnet50_fc512是last_stride=1。

设为一致后用你的代码两个模型准确率差不多。同时在我的代码里用大的特征图也有准确率提升。

所以resnet50_fc512准确率有大幅提升可能是用了比较大的特征图，而不是加FC导致的。

**Comment by KaiyangZhou** [comment]
Can you report your performance using your code?
