### ISSUE TITLE
About ResNext50_32x4d

### ISSUE THREAD

**Issue by AsuradaYuci** [KaiyangZhou/deep-person-reid#175]
Can't download the pretrained model from ''http://www.eecs.qmul.ac.uk/~kz303/deep-person-reid/model-zoo/imagenet-pretrained/resnext50_32x4d-453b60f8.pth''. 
It reports RuntimeError: invalid hash value (expected "453b60f8", got "9c999c625a8f057567b95e6742d5c3fd63128399045d83c9affab7a26a1f3b52").

**Comment by KaiyangZhou** [comment]
the server is down, I am still looking for a solution
