### ISSUE TITLE
Pretrained arg should be casted to bool

### ISSUE THREAD

**Issue by hanochk** [KaiyangZhou/deep-person-reid#178]
On main.y when calling to : torchreid.models.build_model fix:
not (args.no_pretrained) to not bool(args.no_pretrained) on python 3.7 otherwise, it doesn't apply the negate

**Comment by KaiyangZhou** [comment]
it's been defined as a bool by argparse

**Comment by hanochk** [comment]
When debugged under ubuntu, python3.6 the "not" doesn't apply.
Best regards,
Hanoch Kremer

**Comment by KaiyangZhou** [comment]
I tried with python3.6.8 on ubuntu and it works fine

if you add
```
_pretrained = not args.no_pretrained
print(type(_pretrained), _pretrained)
sys.exit()
```
to https://github.com/KaiyangZhou/deep-person-reid/blob/master/scripts/main.py#L107, what would you see in the output?
