### ISSUE TITLE
A question in MuDeep

### ISSUE THREAD

**Issue by distant1219** [KaiyangZhou/deep-person-reid#18]
In Table 1 of the paper, we can see the structure of three parts Layers.There are some different points between your code and paper. In Multi-scale-A, stream id 3 and stream 4 seems to be wrong in paper. Because the number of last layer's output is not  fit the number of next layer's input. What do you think about it?

**Comment by KaiyangZhou** [comment]
I implemented the model based on its [supplementary material](http://openaccess.thecvf.com/content_ICCV_2017/supplemental/Qian_Multi-Scale_Deep_Learning_ICCV_2017_supplemental.pdf).

**Comment by distant1219** [comment]
Thanks
