### ISSUE TITLE
Model zoo unavailable

### ISSUE THREAD

**Issue by KaiyangZhou** [KaiyangZhou/deep-person-reid#180]

**Comment by ardiya** [comment]
Any update on this issue @KaiyangZhou ?

**Comment by KaiyangZhou** [comment]
not yet, I was travelling last week

will try to find a solution this week

**Comment by KaiyangZhou** [comment]
most models are back

**Comment by Zoesxw** [comment]
你好，model zoo Same-domain ReID 部分下载以后，无法压缩，显示文件损坏。可以重新上传一下吗？

**Comment by KaiyangZhou** [comment]
@Zoesxw which one do not work?

**Comment by Zoesxw** [comment]
model zoo 里面现在是只有checkpoint，没有对应的param settings了吗？

**Comment by Zoesxw** [comment]
model zoo 里面现在是只有checkpoint，没有对应的param settings了吗？

**Comment by Zoesxw** [comment]
![微信图片_20190812091854](https://user-images.githubusercontent.com/23716373/62842115-39cedd80-bce2-11e9-9821-e8c35f3beb69.png)

你好，就是这边训练的参数是啥？

**Comment by KaiyangZhou** [comment]
https://github.com/KaiyangZhou/deep-person-reid#a-unified-interface this should give you similar performance

**Comment by Zoesxw** [comment]
ok, thank you!
