### ISSUE TITLE
The url of DukeMTMC-VideoReID is broken

### ISSUE THREAD

**Issue by BraveApple** [KaiyangZhou/deep-person-reid#181]
I can not download DukeMTMC-VideoReID dataset from http://vision.cs.duke.edu/DukeMTMC/data/misc/DukeMTMC-VideoReID.zip.  Can anyone share the pre-downloaded DukeMTMC-VideoReID dataset? Thx.

**Comment by ardiya** [comment]
Duplicate of #180

**Comment by KaiyangZhou** [comment]
all duke-related datasets are offline, there is no way to download the dataset

**Comment by gceboh** [comment]
https://github.com/layumi/DukeMTMC-reID_evaluation/issues/7

**Comment by barotdhrumil21** [comment]
> I can not download DukeMTMC-VideoReID dataset from http://vision.cs.duke.edu/DukeMTMC/data/misc/DukeMTMC-VideoReID.zip. Can anyone share the pre-downloaded DukeMTMC-VideoReID dataset? Thx.

did you find anything!? please share here :'(
