### ISSUE TITLE
AttrubuteError:'InceptionV4' object has no attribute 'classifier'

### ISSUE THREAD

**Issue by Fridaycoder** [KaiyangZhou/deep-person-reid#183]
Hi @KaiyangZhou 
When I train inceptionv4 I got the error as described above,and I modified the inceptionv4.py:
y = self.classifier(v) as y = self.last_linear(v),then it worked.So I think you have to modified the small bug.

**Comment by KaiyangZhou** [comment]
thanks for reporting, to make the name consistent across models, I changed 'self.last_linear' to 'self.classifier' in the construction function

**Comment by Fridaycoder** [comment]
> thanks for reporting, to make the name consistent across models, I changed 'self.last_linear' to 'self.classifier' in the construction function

OK,I see it.Thank you for so fast feedback.
