### ISSUE TITLE
Person Attribute Recognition

### ISSUE THREAD

**Issue by Akashpanchal95** [KaiyangZhou/deep-person-reid#184]
Hello, @KaiyangZhou I am trying to execute your code and found that the images of similar persons (in terms of color and texture) are obtained by grouping the learned factor selection features, Is there any way to visualize the probabilities of the extracted features(Like, Gender, Clothing, Backpack, etc..)?

![confuse](https://user-images.githubusercontent.com/16742926/58873557-3b799500-86e4-11e9-95b0-e33077049ea1.JPG)

**Comment by gceboh** [comment]
https://github.com/xh-liu/HydraPlus-Net

**Comment by KaiyangZhou** [comment]
@Akashpanchal95 you are talking about attribute recognition, for which you need to train a model to predict attribute

**Comment by Akashpanchal95** [comment]
@gceboh Thanks for the reference link. Is there any python implementation?

**Comment by Akashpanchal95** [comment]
@KaiyangZhou Thanks for the quick reply. Is it possible to train the attribute recognition model using the code in the repository? If yes please share the steps and If no, Is there any other repository Where I can find a similar model for an attribute recognition?

**Comment by KaiyangZhou** [comment]
this code currently does not support attribute recognition

I am not aware of any other implementations, perhaps you can find some via google

I may add the attribute recognition code to this repo in the future

**Comment by Akashpanchal95** [comment]
Alright, Thanks lot @KaiyangZhou

**Comment by gceboh** [comment]
https://github.com/YangZhou1994/WPAL-network
@Akashpanchal95

**Comment by Akashpanchal95** [comment]
@gceboh Thanks for the reference link. I have implemented this concept and found it intuitive. https://github.com/dangweili/pedestrian-attribute-recognition-pytorch
