### ISSUE TITLE
Resume from saved weights for training

### ISSUE THREAD

**Issue by johnzhang1999** [KaiyangZhou/deep-person-reid#186]
I tried using `--resume` and `--load-weights` but neither of them seems to work to resume from a checkpoint to continue training. However `--load-weights` does work for evaluation.

I looked briefly into the library code and seems like `--resume` merely loads the `start_epoch` and `--load-weights` does the resume model weights thing. Am I correct? 

Also could you please provide a correct way of resuming for training? Thanks!

**Comment by KaiyangZhou** [comment]
`--resume` does load model weights, optimizer (if available) and the starting epoch, pls refer to https://github.com/KaiyangZhou/deep-person-reid/blob/master/torchreid/utils/torchtools.py#L96

**Comment by johnzhang1999** [comment]
I still can't manage to resume from a checkpoint. Every time I do it, it says checkpoint loaded successfully but just trains from the very beginning anyways. It would be great if you could give me an example command. Thanks

**Comment by KaiyangZhou** [comment]
python scripts/main.py --root $DATA/reid -s market1501 -a resnet18 --max-epoch 5 --save-dir log/test --gpu-devices 0

python scripts/main.py --root $DATA/reid -s market1501 -a resnet18 --max-epoch 8 --save-dir log/test --gpu-devices 0 --resume log/test/model.pth.tar-5
