### ISSUE TITLE
--ranks argument type str

### ISSUE THREAD

**Issue by johnzhang1999** [KaiyangZhou/deep-person-reid#187]
In `scripts/default_parser.py` line 168, type of the `--ranks` argument is regarded as `str`.
``` python
parser.add_argument('--ranks', type=str, default=[1, 5, 10, 20], nargs='+',
                        help='cmc ranks')
```
But later in `torchreid/engine/engine.py` line 287, the ranks is treated as an int list, and there would be a type error when giving custom ranks for eval,
``` python
 for r in ranks:
            print('Rank-{:<3}: {:.1%}'.format(r, cmc[r-1])) # here r-1 is str-int
```

**Comment by KaiyangZhou** [comment]
this should be a typo, it's been fixed
