### ISSUE TITLE
Timeline of Releasing OSNet Implementation

### ISSUE THREAD

**Issue by johnzhang1999** [KaiyangZhou/deep-person-reid#188]
Is there any rough time that we could expect to see an OSNet implementation in this repo? Thanks!

**Comment by KaiyangZhou** [comment]
will try my best to get this done in these two weeks

**Comment by KaiyangZhou** [comment]
@johnzhang1999  still waiting for consent from samsung, which might take a (long) while, sorry for any inconvenience.

**Comment by johnzhang1999** [comment]
Sure no problem, and I've created my own implementation (tho somehow I cannot get it down to ~2.2M params in size as mentioned in your paper and I'm not sure where I did wrong). Anyways, thank you for notifying me.

**Comment by chenxiaoyu523** [comment]
@johnzhang1999 can you reproduce the results in osnet paper?

**Comment by johnzhang1999** [comment]
> @johnzhang1999 can you reproduce the results in osnet paper?

Not really. I'm getting some architectural or training details wrong I think.
