### ISSUE TITLE
Visualization of Learned feature

### ISSUE THREAD

**Issue by allenfutaki** [KaiyangZhou/deep-person-reid#194]
The visualization of learned feature is made by sum up the absolute-valued activation map along the channel dimension.
![image](https://user-images.githubusercontent.com/28795889/59859057-a696bd00-93ae-11e9-9843-a7f1f69e1e1b.png)

Which activation maps in OSNet is extracted to visualize?
Is the activation maps upsampled to match the shape of original image?

**Comment by gceboh** [comment]
#211

**Comment by allenfutaki** [comment]
Thanks for your information.
I just implement it with myself.
