### ISSUE TITLE
mobilenet pretrained key error 'state_dict'

### ISSUE THREAD

**Issue by maylad31** [KaiyangZhou/deep-person-reid#196]
unable to load pretrained weights for mobilenet model please help

**Comment by jerryhitit** [comment]
I also encountered this problem.

I was wondering those pretrained model urls about mobilenetv2 are no longer available, so are there any other pretrained model can be manually download from?

Like this two:
[mobilenetv2_1dot0](https://mega.nz/#!NKp2wAIA!1NH1pbNzY_M2hVk_hdsxNM1NUOWvvGPHhaNr-fASF6c)
and
[mobilenetv2_1dot4](https://mega.nz/#!RGhgEIwS!xN2s2ZdyqI6vQ3EwgmRXLEW3khr9tpXg96G9SUJugGk)

Any helps will be appreciated!
