### ISSUE TITLE
About the Triplet Loss in Hermans et al.. It seems you guys ignored soft-margin part.

### ISSUE THREAD

**Issue by ArchNew** [KaiyangZhou/deep-person-reid#197]
According to In Defense of the Triplet Loss for Person Re-Identification. arXiv:1703.07737., their best performance reached when using the soft-margin version of their loss function. Of course, it's not hard for anyone to code up that part, only need to add one line (or several lines). 

I'm wondering the reason. If the soft-margin version is not as good as the paper claims in your experiments?

**Comment by JakeCowton** [comment]
Try implementing & testing it? Let us know how you get on!
