### ISSUE TITLE
Some image datasets could not be trained

### ISSUE THREAD

**Issue by crossknight** [KaiyangZhou/deep-person-reid#198]
Hi,

I've downloaded image datasets (refer to https://kaiyangzhou.github.io/deep-person-reid/datasets.html#) and trained the model on them one by one.

Here is the results.

Trainable datasets
- market1501
- cuhk03
- msmt17
- sensereid

Not trainable datasets (It's skipped to Evaluating part with 0 Epoch)
- viper
- grid
- ilids
- prid (log: 
[train.log-2019-07-10-11-15-00.log](https://github.com/KaiyangZhou/deep-person-reid/files/3375854/train.log-2019-07-10-11-15-00.log)
)

Unavailable dataset
- dukemtmc

**Comment by crossknight** [comment]
Add a log for prid dataset

**Comment by KaiyangZhou** [comment]
set `print_freq=1`
