### ISSUE TITLE
Problem when trying to evaluate prid

### ISSUE THREAD

**Issue by akonstantinou** [KaiyangZhou/deep-person-reid#2]
~:/python train_vid_model_xent.py -d prid -a resnet50 --evaluate --resume saved-models/resnet50_xent_prid.pth.tar --save-dir log/resnet50-xent-prid --test-batch 2
==========
Args:Namespace(arch='resnet50', dataset='prid', eval_step=-1, evaluate=True, gamma=0.1, gpu_devices='0', height=256, lr=0.0003, max_epoch=15, pool='avg', print_freq=10, resume='saved-models/resnet50_xent_prid.pth.tar', save_dir='log/resnet50-xent-prid', seed=1, seq_len=15, start_epoch=0, stepsize=5, test_batch=2, train_batch=32, use_cpu=False, weight_decay=0.0005, width=128, workers=4)
==========
Currently using GPU 0
Initializing dataset prid
# train identites: 89, # test identites 89
=> PRID-2011 loaded
Dataset statistics:
  ------------------------------
  subset   | # ids | # tracklets
  ------------------------------
  train    |    89 |      178
  query    |    89 |       89
  gallery  |    89 |       89
  ------------------------------
  total    |   178 |      356
  number of images per tracklet: 28 ~ 675, average 108.1
  ------------------------------
Initializing model: resnet50
Model size: 23.69039M
Loading checkpoint from 'saved-models/resnet50_xent_prid.pth.tar'
Evaluate only
Extracted features for query set, obtained 89-by-2048 matrix
Traceback (most recent call last):
  File "train_vid_model_xent.py", line 269, in <module>
    main()
  File "train_vid_model_xent.py", line 150, in main
    test(model, queryloader, galleryloader, args.pool, use_gpu)
  File "train_vid_model_xent.py", line 232, in test
    imgs = imgs.view(b*s, c, h, w)
RuntimeError: invalid argument 2: size '[15 x 3 x 256 x 128]' is invalid for input with 2949120 elements at /pytorch/torch/lib/TH/THStorage.c:41

**Comment by KaiyangZhou** [comment]
This issue has been solved. It was a typo mistake. Now all set.
