### ISSUE TITLE
Memory requirement for OSNet

### ISSUE THREAD

**Issue by ba305** [KaiyangZhou/deep-person-reid#206]
Hello, thanks very much for releasing the OSNet code. I am excited to start working with it.

One question: I just tried to train on Market1501 using osnet_x1_0, and was surprised to find that I had CUDA out of memory error, unless I reduced my batch size.

I had been using ResNet50, and could get my batch size up to around 120 without any errors. However, with osnet_x1_0, I can only increase batch size to around 80 before running out of memory.

Do you know why this might be? I know OSNet is much more lightweight, so was surprised that I ran out of memory sooner than ResNet50. Thank you!

**Comment by KaiyangZhou** [comment]
with a 12gb gpu, you can fit into the memory with batch size 128

osnet is memory-consuming because of its multi-branch design

lightweight (less params) is not equivalent to memory friendly
