### ISSUE TITLE
Error: all query identities do not appear in gallery

### ISSUE THREAD

**Issue by RodMech** [KaiyangZhou/deep-person-reid#207]
Dear Kaiyang, thanks for sharing your repo, 

I have come across an issue that I am hardly struggling to understand. 

My layout is: 

-I have done a dataset with only 1 camera_id, 50 person ids and an overall of 600 pics, just to check cross-dataset testing. 

And I have followed this process: 

**1.-** Create of the new dataset class and required lists (train, query, gallery), following your instructions:

    class NewDataset(ImageDataset):

        dataset_dir = "new_dataset"`

        def __init__(self, root='', **kwargs):
            self.root = osp.abspath(osp.expanduser(root))
            self.dataset_dir = osp.join(self.root, self.dataset_dir)
        
            #===========================================================
        
            # extract csv info
        
            folder_path = "/opt/project/deep-person-reid/reid-data/my_dataset/" # Change the path to the dataset
            refs  = pd.read_csv("{}references.csv".format(folder_path))
            paths  = os.listdir(folder_path)
        
            # Get some data
            pid_pics = refs[" number_pics"] # Number of pics per id
            pids = refs.shape[0] # Number of identities
        
            # Generate batches of paths by its person id
            batches = list()
            for i in range(pids):
                batches.append([folder_path+path for path in paths if path.startswith("{}-".format(i+1))])
            
            # Create a random split shuffle of the query/gallery paths 

            query_paths = list()
            gallery_paths = list()

            split_size = 0.8 # Query-Gallery split, usually 0.2 : 0.8 

            for i in range(pids):
                gallery_elements = int(len(batches[i])*split_size)
                gallery_paths.append(random.sample(batches[i], gallery_elements))
                query_paths.append([e for e in batches[i] if e not in gallery_paths[i]])
            
            # Generate the required variables

            #train = list()
            query = [(e, i, 0) for i in range(pids) for e in query_paths[i]]
            gallery = [(e, i, 0) for i in range(pids) for e in gallery_paths[i]]
            train = copy.deepcopy(query) + copy.deepcopy(gallery) # dummy variable

        
            super(NewDataset, self).__init__(train, query, gallery, **kwargs)

**2.-** Then, I declare an object in the suggested way:
 
    
    #Register your own dataset

    torchreid.data.register_image_dataset('h2ocio', NewDataset)

**3.-** After, I create the data manager:

     datamanager = torchreid.data.ImageDataManager(
        root='reid-data',
        sources='msmt17', 
        targets='my_dataset', 
        transforms=["random_flip","color_jitter"],
        height=256,
        width=128,
        batch_size=32,
        train_sampler='RandomIdentitySampler',
        combineall=False
    )

The output is:

      ----------------------------------------
      subset   | # ids | # images | # cameras
      ----------------------------------------
      train    |  1041 |    30248 |        15
      query    |  3060 |    11659 |        15
      gallery  |  3060 |    82161 |        15
      ----------------------------------------
    => Loading test (target) dataset
    => Loaded NewDataset
      ----------------------------------------
      subset   | # ids | # images | # cameras
      ----------------------------------------
      train    |    50 |      598 |        1
      query    |    50 |      140 |        1
      gallery  |    50 |      458 |        1
      ----------------------------------------

      **************** Summary ****************
      train            : ['msmt17']
      # train datasets : 1
      # train ids      : 1041
      # train images   : 30248
      # train cameras  : 15
      test             : ['my_dataset']
      *****************************************

**4.-** Then, I create the parameters of the model:

    model = torchreid.models.build_model(
        name='osnet_ibn_x1_0',
        num_classes=datamanager.num_train_pids,
        #loss='softmax',
        loss='triplet',
        pretrained=False
    )

    model = model.cuda()

    optimizer = torchreid.optim.build_optimizer(
        model,
        optim='adam',
        lr=0.0003
    )

    scheduler = torchreid.optim.build_lr_scheduler(
        optimizer,
        lr_scheduler='single_step',
        stepsize=20
    )

**5.-** Now it is time for the engine: 

    engine = torchreid.engine.ImageTripletEngine(
        datamanager,
        model,
        optimizer=optimizer,
        scheduler=scheduler,
        label_smooth=True
    )

**6.-** And run the model!

    engine.run(
        save_dir='log/osnet_ibn_x1_0',
        max_epoch=5,
        eval_freq=50,
        print_freq=50,
        test_only=False
    )
 
====================================================================

AFTER THE TRAINING, THE LOG IS...

    ##### Evaluating my_dataset (target) #####
    Extracting features from query set ...
    Done, obtained 140-by-512 matrix
    Extracting features from gallery set ...
    Done, obtained 458-by-512 matrix
    Speed: 0.1357 sec/batch
    Computing distance matrix with metric=euclidean ...
    Computing CMC and mAP ...

**AND THE ERROR POPS UP:** 

    ---------------------------------------------------------------------------
    AssertionError                            Traceback (most recent call last)
    <ipython-input-10-92727a18c255> in <module>
          4     eval_freq=10,
          5     print_freq=10,
    ----> 6     test_only=False
          7 )

    /opt/project/deep-person-reid/torchreid/engine/engine.py in run(self, save_dir, max_epoch,   start_epoch, fixbase_epoch, open_layers, start_eval, eval_freq, test_only, print_freq, dist_metric, normalize_feature, visrank, visrank_topk, use_metric_cuhk03, ranks, rerank)
         90                 use_metric_cuhk03=use_metric_cuhk03,
         91                 ranks=ranks,
    ---> 92                 rerank=rerank
         93             )
         94             return

    /opt/project/deep-person-reid/torchreid/engine/engine.py in test(self, epoch, testloader, dist_metric, normalize_feature, visrank, visrank_topk, save_dir, use_metric_cuhk03, ranks, rerank)
        204                 use_metric_cuhk03=use_metric_cuhk03,
        205                 ranks=ranks,
     --> 206                 rerank=rerank
        207             )
        208 

    /opt/conda/lib/python3.6/site-packages/torch/autograd/grad_mode.py in decorate_no_grad(*args, **kwargs)
         41         def decorate_no_grad(*args, **kwargs):
         42             with self:
    ---> 43                 return func(*args, **kwargs)
         44         return decorate_no_grad
         45 

    /opt/project/deep-person-reid/torchreid/engine/engine.py in _evaluate(self, epoch, dataset_name, queryloader, galleryloader, dist_metric, normalize_feature, visrank, visrank_topk, save_dir, use_metric_cuhk03, ranks, rerank)
        279             q_camids,
        280             g_camids,
    --> 281             use_metric_cuhk03=use_metric_cuhk03
        282         )
        283 

    /opt/project/deep-person-reid/torchreid/metrics/rank.py in evaluate_rank(distmat, q_pids, g_pids, q_camids, g_camids, max_rank, use_metric_cuhk03, use_cython)
        182         return evaluate_cy(distmat, q_pids, g_pids, q_camids, g_camids, max_rank, use_metric_cuhk03)
        183     else:
    --> 184         return evaluate_py(distmat, q_pids, g_pids, q_camids, g_camids, max_rank, use_metric_cuhk03)

    /opt/project/deep-person-reid/torchreid/metrics/rank.py in evaluate_py(distmat, q_pids, g_pids, q_camids, g_camids, max_rank, use_metric_cuhk03)
        155         return eval_cuhk03(distmat, q_pids, g_pids, q_camids, g_camids, max_rank)
        156     else:
    --> 157         return eval_market1501(distmat, q_pids, g_pids, q_camids, g_camids, max_rank)
        158 
        159 

    /opt/project/deep-person-reid/torchreid/metrics/rank.py in eval_market1501(distmat, q_pids, g_pids, q_camids, g_camids, max_rank)
        142         all_AP.append(AP)
        143 
    --> 144     assert num_valid_q > 0, 'Error: all query identities do not appear in gallery'
        145 
        146     all_cmc = np.asarray(all_cmc).astype(np.float32)

    AssertionError: Error: all query identities do not appear in gallery

==================================================================

I feel that I cannot grasp what is actually going on. Can you please help me to troubleshoot this issue? I would appreciate it a lot. 

Many thanks again for your support, 

R

**Comment by KaiyangZhou** [comment]
Thanks for providing this detailed info. The error is caused by the camera ids which are the same for both query and gallery. This violates the cross-camera matching criterion (for market1501-style). When doing evaluation, for each query, all gallery images are first ranked by the distance to this query, then those images of the same pid and camid are removed for the purpose of cross-camera matching. See this [python code](https://github.com/KaiyangZhou/deep-person-reid/blob/master/torchreid/metrics/rank.py#L118). Therefore, your gallery images should come from different camera views, at least for those with the same pids.

A quick way to solve your problem is to change the code like this
```python
query = [(e, i, 0) for i in range(pids) for e in query_paths[i]] # camera view 0
gallery = [(e, i, 1) for i in range(pids) for e in gallery_paths[i]] # camera view 1
```

To check if the code is correct, do `engine.run(test_only=True)` (direct evaluation without training).

Btw, you are using triplet loss but set `label_smooth=True`, which has no effect. You can tune the `weight_x` and `weight_t` parameters but in general, using softmax with label smoothing is sufficient.

**Comment by RodMech** [comment]
Thanks Kaiyang,

**Your solution is correct**. It is already tested and works like a charm. Cross-dataset evaluation is gorgeous.

I thought that combining label smooth and triplet loss was a correct measure, as suggested in [this paper](https://arxiv.org/pdf/1903.07071.pdf). 

But I guess that label smoothing is applied after the last FC layer (after the BNNeck module), and triplet loss is applied right after the pretrained backbone (in the beggining of the BNNeck).

I think i am missing something. Do you have any insight in this direction?

THANKS again,

R

**Comment by KaiyangZhou** [comment]
make sure weight_x>0 in the triplet engine so softmax loss is enabled, otherwise label smoothing has no effect

a safer way to finetune a (imagenet-)pretrained network is to first train the randomly initialised layers for few epochs, and then open all layers for training, this ensures that the backbone network's good init params are not destroyed by the random grads (this is controlled by the `fixbase_epoch` parameter)

setting fixbase_epoch>0 and using softmax+label_smooth is sufficient (pls refer to the training scripts for osnet in the other post)

adding triplet loss increases the computations and might not bring any improvement when fixbase_epoch>0
