### ISSUE TITLE
Plot ranked images on a single figure

### ISSUE THREAD

**Issue by KaiyangZhou** [KaiyangZhou/deep-person-reid#210]

**Comment by gceboh** [comment]
[Person_reID_baseline_pytorch](https://github.com/layumi/Person_reID_baseline_pytorch) has this feature, too.

Some small advice for reference:
The shortcoming of this feature is that [the topk argument](https://github.com/KaiyangZhou/deep-person-reid/blob/76acdc961250f4e8937025612270301b457c3638/torchreid/utils/reidtools.py#L14) may become fixed. And plotting ranked images on a single figure may be not suitable for video based re-id.

**A simpler solution** is to place a correct mark (eg，★) on the [filename](https://github.com/KaiyangZhou/deep-person-reid/blob/76acdc961250f4e8937025612270301b457c3638/torchreid/utils/reidtools.py#L53) of the correct candidates.
For example,
`gallery_top001_name_1390_c1s6_017446_01.jpg`
 to
`gallery_top001_★★name_1390_c1s6_017446_01.jpg`

**Comment by KaiyangZhou** [comment]
good to know that, thank you

I will try to find time to get this done soon

**Comment by KaiyangZhou** [comment]
See https://kaiyangzhou.github.io/deep-person-reid/user_guide.html#visualize-ranked-results for details
