### ISSUE TITLE
How to draw the figure 6 in the paper of OSNet?

### ISSUE THREAD

**Issue by jianwu585218** [KaiyangZhou/deep-person-reid#211]
![image](https://user-images.githubusercontent.com/34296200/61853339-3e2b8600-aeee-11e9-801b-8d9f82e3d341.png)

I have a question. The activation map in figure 6 is beautiful and convincing. How to generate such figure? Use Grad-CAM? Thanks.

**Comment by KaiyangZhou** [comment]
For now please have a look at this paper https://arxiv.org/abs/1612.03928

I will release this visualization code

**Comment by jianwu585218** [comment]
Thank you

发送自 Windows 10 版邮件应用

发件人: Kaiyang
发送时间: 2019年7月26日 19:32
收件人: KaiyangZhou/deep-person-reid
抄送: jianwu585218; Author
主题: Re: [KaiyangZhou/deep-person-reid] How to draw the figure 6 in thepaper of OSNet? (#211)

For now please have a look at this paper https://arxiv.org/abs/1612.03928
I will release this visualization code

**Comment by gceboh** [comment]
These feature map visualization code may be helpful :
https://github.com/KaiyangZhou/deep-person-reid/issues/47

**Comment by jianwu585218** [comment]
Thank you~




------------------ 原始邮件 ------------------
发件人: "gceboh"<notifications@github.com>;
发送时间: 2019年7月27日(星期六) 晚上10:41
收件人: "KaiyangZhou/deep-person-reid"<deep-person-reid@noreply.github.com>;
抄送: "林建武"<1449214372@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [KaiyangZhou/deep-person-reid] How to draw the figure 6 in thepaper of OSNet? (#211)




These feature map visualization code may be helpful :
 #47

**Comment by KaiyangZhou** [comment]
See https://kaiyangzhou.github.io/deep-person-reid/user_guide.html#visualize-activation-maps for details

**Comment by busdac** [comment]
I have similar question: How does '--root $DATA/reid \' look like in the following command?

python tools/visualize_actmap.py \
    --root $DATA/reid \
    -d market1501 \

Would you please provide am exact example?
I always get this Error
      TypeError: expected str, bytes or os.PathLike object, not tuple
