### ISSUE TITLE
Do your results in Model Zoo use re-ranking?

### ISSUE THREAD

**Issue by ArchNew** [KaiyangZhou/deep-person-reid#213]
The re-ranking method in the paper "Re-ranking Person Re-identification with k-reciprocal Encoding" has a noticeable effect on all current re-id methods. I'm wondering your results on Model Zoo are before or after the re-raking. Namely, if the re-ranking becomes a common practice without mentioning now?

**Comment by KaiyangZhou** [comment]
no rerank

**Comment by gceboh** [comment]
The re-ranking result is reported here:
https://github.com/KaiyangZhou/deep-person-reid/issues/91#issuecomment-491098567

**Comment by ArchNew** [comment]
Thanks! Both of you.
