### ISSUE TITLE
cython

### ISSUE THREAD

**Issue by CuongNguyen218** [KaiyangZhou/deep-person-reid#214]
![cython](https://user-images.githubusercontent.com/43350150/62004858-c4490600-b154-11e9-983b-aac54095bba2.png)
i get some trouble when use cython test. did you have any idea to fix this problem ? 
Thanks

**Comment by KaiyangZhou** [comment]
still have the problem?

can you provide more details to reproduce your error?

**Comment by CuongNguyen218** [comment]
Hi Zhou,
In my pc i still have this problem, I don't understand where this error come from. But it's result when i test with test_cython.py in your package. and when I import this package I also have a trouble with cython. But another pc, your package work very well. Thanks

**Comment by KaiyangZhou** [comment]
what is your pc's system? I guess the cython code was not properly installed so it led to the problem

check this thread https://github.com/KaiyangZhou/deep-person-reid/issues/160 if it is relevant to your problem

**Comment by CuongNguyen218** [comment]
my system : ubuntu 16.04 pytorch 1.0 and cython 0.27.9. xeon e5 32gb ram titanX gpu
