### ISSUE TITLE
How to just test? How to load the final weight?

### ISSUE THREAD

**Issue by xlzup** [KaiyangZhou/deep-person-reid#215]
I have trained a model and I want to evaluate it again,But I got a very low rank and map,I think it should be that the model is loaded with a pre-trained model. How do I load my trained model?
I used ‘’‘--evaluate’, what should I do next?

**Comment by KaiyangZhou** [comment]
```
...
--evaluate \
--load-weights log/my-model/model.pth.tar \
...
```

**Comment by xlzup** [comment]
Thank you for your help

**Comment by gceboh** [comment]
I suggest add this instruction to `readme.md`. @KaiyangZhou
