### ISSUE TITLE
Add logging to tensorboard

### ISSUE THREAD

**Issue by sovrasov** [KaiyangZhou/deep-person-reid#216]
@KaiyangZhou Text log is OK, but it's hard to read. Do you have plans to integrate tensorboard to visualize training curves?

**Comment by sovrasov** [comment]
Actually I did it in my fork, but my code is dirty and needs refactoring:
https://github.com/sovrasov/deep-person-reid/tree/cosine_dist

**Comment by gceboh** [comment]
Code for visualizing Training Curves:
https://github.com/KaiyangZhou/deep-person-reid/issues/148

https://github.com/KaiyangZhou/deep-person-reid/issues/148#issuecomment-483183163

**Comment by KaiyangZhou** [comment]
- Follow the installation steps to install tensorboard
- See [here](https://kaiyangzhou.github.io/deep-person-reid/user_guide.html#visualize-learning-curves-with-tensorboard) for how to use.
