### ISSUE TITLE
yacs is missing in setup.py

### ISSUE THREAD

**Issue by sovrasov** [KaiyangZhou/deep-person-reid#219]
In the setyp.py the `install_requires` parameter doesn't contain yacs, so torchreid fails at launch after clean setup.

**Comment by sovrasov** [comment]
I suggest to read requirements.txt from setup.py like [here](https://stackoverflow.com/questions/14399534/reference-requirements-txt-for-the-install-requires-kwarg-in-setuptools-setup-py)

**Comment by KaiyangZhou** [comment]
thanks for your suggestion, I have fixed this bug
