### ISSUE TITLE
Random Patch Data Augmentation

### ISSUE THREAD

**Issue by KaiyangZhou** [KaiyangZhou/deep-person-reid#221]
New commit: https://github.com/KaiyangZhou/deep-person-reid/commit/0ec14d9afca6e4d401f3293ca468e717d3fd27fb

`RandomPatch` extracts image patches and stores them in a *patch pool*. From the patch pool, a patch is randomly selected and pasted at a random position on an input image for data augmentation. This aims to simulate real-world occlusion.

We used this method to train [OSNet](https://arxiv.org/abs/1905.00953) from scratch (this detail is not mentioned in the paper). For pretrained models, `random_erase` generally performs better (observed on market1501). To use `RandomPatch`, add `random_patch` to the `transforms` argument.

We recommend to not use this method for cross-domain reid as it, like the random erasing, will harm the generalisation performance.

**Comment by L1aoXingyu** [comment]
Did you try random erasing on a large-scale dataset? I mean where do you get this conclusion that random erasing will harm the generalization performance.
Thank you.

**Comment by KaiyangZhou** [comment]
@L1aoXingyu Yes, you can try msmt17->market/duke, market->duke or duke->market, keep random erasing as the only control variable
