### ISSUE TITLE
train custom dataset

### ISSUE THREAD

**Issue by BabuTango** [KaiyangZhou/deep-person-reid#223]
@KaiyangZhou  can you please tell me how to train the model on custom data-set.
What are preparations to be done for the data-set for training,
what are the modifications to be done

**Comment by KaiyangZhou** [comment]
please check the documentation

**Comment by BabuTango** [comment]
@KaiyangZhou I think documentation contains information for training on standard datasets. 
or can you please specify where the information can be found for training custom datasets

**Comment by BabuTango** [comment]
@KaiyangZhou 
I see that in the documentation.
You have mentioned 

# Each list contains tuples of (img_path, pid, camid),
# where
# - img_path (str): absolute path to an image.
# - pid (int): person ID, e.g. 0, 1.
# - camid (int): camera ID, e.g. 0, 1.

I have images from mulitple camera, but I don't have the camera information.
How can I train with out specifying camera id's.

**Comment by KaiyangZhou** [comment]
camera ids are normally useless during the identity classification so you don't need to put the 'real' ids, you can just give camid=0 to all training images

however, because the test code performs cross-camera matching, images of the same pid and camid will be discarded, you need to make sure the camids are different for query and gallery

hope this helps

**Comment by BabuTango** [comment]
Thanks @KaiyangZhou . I want to train on my custom dataset.

You have mentioned that
**_Each list contains tuples of (img_path, pid, camid),
where

img_path (str): absolute path to an image.
pid (int): person ID, e.g. 0, 1.
camid (int): camera ID, e.g. 0, 1._**


Can you just give me an example of **how each list would look like**.

**Comment by KaiyangZhou** [comment]
```
example_list = [
    ('image1.jpg', 0, 0), # pid=0, camid=0
    ('image2.jpg', 1, 0), # pid=1, camid=0
    ('image3.jpg', 2, 0), # pid=2, camid=0
    ...
]
```

check the reid dataset, e.g. market1501, and add `import pdb; pdb.set_trace()` after the list is generated, then you can check what the list looks like in the terminal
