### ISSUE TITLE
Help! I want to load weights from model zoo

### ISSUE THREAD

**Issue by prathameshnetake** [KaiyangZhou/deep-person-reid#225]
I am trying to load weights from model zoo especially for OSNetx0.25. Model is not available for the same. When I am trying to load weights on model using function from the tool that giving me 

Successfully loaded pretrained weights from "./osnet_x0_25_msmt17_combineall_256x128_amsgrad_ep150_stp60_lr0.0015_b64_fb10_softmax_labelsmooth_flip_jitter.pth"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']

this error.
Help will be appreciated.

**Comment by KaiyangZhou** [comment]
> Model is not available for the same

What do you mean?

> The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']

This is typically because the identity layer in your new model is different in IDs from the pretrained one. It's normal and not an error

**Comment by huangzongheng** [comment]
The osnet models are unavailable now. Pretrained model can't be downloaded. Is there another link to replace the current one?
