### ISSUE TITLE
Person ReId in real-time video feeds

### ISSUE THREAD

**Issue by sahilrider** [KaiyangZhou/deep-person-reid#226]
I want to develop a system in which I capture the image of a person in one camera, then re identifies it in the other camera video feeds. How this can be done?

**Comment by gceboh** [comment]
This may help you:
https://github.com/giranntu/Deep-Person-ReID-in-NVIDIA-Jetson

**Comment by gceboh** [comment]
Your requirement is more complex and hard than you have expected.
Please refer to this paper:
http://www.eecs.qmul.ac.uk/~sgg/papers/RajaGong_REIDSpringer14.pdf

**Comment by LSRAO** [comment]
> I performed a search ,and this may help you: https://github.com/giranntu/Deep-Person-ReID-in-NVIDIA-Jetson

@sahilrider did ypu find any solution? I am also working on a similar thing and this link is inactive.
