### ISSUE TITLE
How to display activation map for mobilenetv2?

### ISSUE THREAD

**Issue by amandayeyan** [KaiyangZhou/deep-person-reid#227]
Hi Kaiyang, how was the argument visactmap imported to show activation map of osnet?
After trying to add following code to mobilenetv2 backbone below, no activation maps were saved for mobilenetv2. Any idea?      
```python
def forward(self, x, output_featuremaps_only):
  f = self.featuremaps(x)
    if output_featuremaps_only:
      return f
```

**Comment by KaiyangZhou** [comment]
the argument should be `return_featuremaps`, see https://github.com/KaiyangZhou/deep-person-reid/blob/master/torchreid/engine/engine.py#L332

**Comment by amandayeyan** [comment]
@KaiyangZhou 
I suggest to integrate visactmap function here, so that activation maps are saved for testing only mode too. 
![image](https://user-images.githubusercontent.com/18046926/64932348-e0be1080-d870-11e9-8c70-3d2f1abfd1d7.png)

**Comment by KaiyangZhou** [comment]
hi, thanks for your suggestion

the thing is one doesn't have to run the test in order to get the activation map, so I would prefer to separate them
