### ISSUE TITLE
basic information about frame

### ISSUE THREAD

**Issue by Adorablepet** [KaiyangZhou/deep-person-reid#228]
When I ported my existing model to your framework for training and testing, top1 dropped by 8 points. The learning rate, sampling strategy, etc. are the same as the design of my previous model. You have encountered this question?Thanks.

**Comment by Adorablepet** [comment]
@KaiyangZhou When I used multiple GPUs to train, I had this problem. I changed it to a single gpu. This problem is solved.

**Comment by KaiyangZhou** [comment]
maybe more context information?
