### ISSUE TITLE
url error for multiple datasets

### ISSUE THREAD

**Issue by srinivas-varadharajan** [KaiyangZhou/deep-person-reid#229]
@KaiyangZhou Great repo! Appreciate the effort.

I'm trying to run some basic experiments to get a hang of reid/torchreid. 
I'm unable to download datasets such as market1501, dukemtmcreid, msmt17 either through torchreid script or manually. 

From your paper, even for GRID dataset, you had mentioned that it needs to be trained using these large datasets and then finetuned. 

I tried to search the source URL for dataset but it seems that its invalid now. 
Could you please point me to the source to get these datasets?

Example for market1501:

Error:
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
 urllib.request.urlretrieve(url, dst, _reporthook)

url="http://188.138.127.15:81/Datasets/Market-1501-v15.09.15.zip"

**Comment by KaiyangZhou** [comment]
Hi, thanks for the spot. I guess those links are removed or changed. You can submit a pull request if you have found the correct links. Just replace the old link in the .py file with the up-to-date one you found.

I am not in office for this week so the earliest time I can touch the code might be next week

**Comment by KaiyangZhou** [comment]
I checked the download links. The link for market1501 stills works. Perhaps there is a problem with your network proxy (e.g. are you using company network with some restriction?). For duke and msmt17, they are offline due to privacy issues.

**Comment by srinivas-varadharajan** [comment]
Apologies, I forgot to update the issue here. yes, market1501 error was due to the proxy settings in the lab. And w.r.t to duke and msmt17 is there  any other way to get the data?

**Comment by BJTUJia** [comment]
Hi，@srinivas-varadharajan， how did you fix the internet proxy problem to get access to Market1501？
