### ISSUE TITLE
Error when loading DenseNet model : Missing key(s) in state_dict

### ISSUE THREAD

**Issue by gceboh** [KaiyangZhou/deep-person-reid#23]
# 1.Error Description
I tried to perform test on the MARS dataset with the provided trained model `densenet121_xent_htri_mars.pth.tar`, using this command：
`python train_vid_model_xent_htri.py -d mars -a densenet121 --evaluate --resume saved-models/densenet121_xent_htri_mars.pth.tar --save-dir log/densenet121-xent-htri-mars --test-batch 2`

And I got the following error info: 

> RuntimeError: Error(s) in loading state_dict for DenseNet121:
> 	Missing key(s) in state_dict: "base.denseblock1.denselayer1.norm1.running_var",
> 	...

(for detailed info, please refer to the console log)

## Some Analysis
1)Although I had already put the provided model file in the dir `deep-person-reid/saved-models/`,the console log shows that PyTorch still **automatically** downloaded a pre-trained model from "https://download.pytorch.org/models/densenet121-a639ec97.pth" to the path `/home/user/.torch/models/densenet121-a639ec97.pth`. **After** the download process had completed, pyTorch loaded the provided model `densenet121_xent_htri_mars.pth.tar`.(see the log for detailed info.) 

It seems that the provided model `densenet121_xent_htri_mars.pth.tar` which **contains the model's parameters ONLY** is not consistent with the model auto downloaded from `download.pytorch.org` .
<br/>

2)Why did PyTorch auto download pre-trained model from `download.pytorch.org` before it loaded `densenet121_xent_htri_mars.pth.tar` ?
Because in `__init__` function of `DenseNet.py`,"pretrained" is set to true.
[This Line:](https://github.com/KaiyangZhou/deep-person-reid/blob/385a663e5d494ff72b3bb6f9c385b4c40ea55df2/models/DenseNet.py#L14)
`densenet121 = torchvision.models.densenet121(pretrained=True)`

3)I tried to perform test on the MARS dataset with the **ResNet model** (`resnet50_xent_mars.pth.tar`). PyTorch again automatically downloaded another pre-trained model from `download.pytorch.org`, but this time, **NO runtime error occurred**. Command:
`python train_vid_model_xent.py -d mars -a resnet50 --evaluate --resume saved-models/resnet50_xent_mars.pth.tar --save-dir log/resnet50-xent-mars --test-batch 2`

I have found a similar issue(#4), but it can't solve this problem. 
Does anyone know how to solve it? Thanks in advance.

# 2.Additional Info
## Code Version
May 30, 2018

## Model File Hash
File Name : densenet121_xent_htri_mars.pth.tar
URL : http://www.eecs.qmul.ac.uk/~kz303/deep-person-reid/model-zoo/video-models/densenet121_xent_htri_mars.pth.tar
MD5 : 544FFC7520B5719B2F63CAA44F412F49

## Environment
Ubuntu 14.04 x64
Anaconda 2 4.4.0 x86_64
Python 2.7.13
PyTorch 0.4.0
torchvision-cpu 0.2.1 
use CPU only (no CUDA installed)

**Comment by KaiyangZhou** [comment]
The error is caused by the mismatch in keys, e.g. layers were named 'norm.1', 'conv.1', but are now named 'norm1', 'conv1' (I trained the model with the old torchvision). You can either manually update the keys in the `state_dict` or train a new one (try the default param setting).

**Comment by gceboh** [comment]
Thank you for your prompt and useful reply!
I modified "train_vid_model_xent_htri.py",and the problem has been solved!

train_vid_model_xent_htri.py:
```
import re

...


    if args.resume:
        print("Loading checkpoint from '{}'".format(args.resume))
        checkpoint = torch.load(args.resume)
		
#modify:
        # '.'s are no longer allowed in module names, but pervious _DenseLayer
        # has keys 'norm.1', 'relu.1', 'conv.1', 'norm.2', 'relu.2', 'conv.2'.
        # They are also in the checkpoints in model_urls. 
        # This pattern is used to find such keys.
        pattern = re.compile(
            r'^(.*denselayer\d+\.(?:norm|relu|conv))\.((?:[12])\.(?:weight|bias|running_mean|running_var))$')
        state_dict = checkpoint['state_dict']
        for key in list(state_dict.keys()):
            res = pattern.match(key)
            if res:
                new_key = res.group(1) + res.group(2)
                state_dict[new_key] = state_dict[key]
                del state_dict[key]
        model.load_state_dict(state_dict)

        #model.load_state_dict(checkpoint['state_dict'])
        start_epoch = checkpoint['epoch']
```
		
code reference:
 [torchvision/densenet.py](https://github.com/pytorch/vision/blob/50b2f910490a731c4cd50db5813b291860f02237/torchvision/models/densenet.py#L28)
