### ISSUE TITLE
Issue with resnet 50 pretrained weights 

### ISSUE THREAD

**Issue by Shamazo** [KaiyangZhou/deep-person-reid#231]
Hi,

The weight files linked to on the model zoo for resenet50-fc have a .tar extension, but don't appear to be valid tar files. I have also tried loading them directly. Are the files on the model zoo corrupted somehow, or am I using them wrong? I have loaded other models weights, such as osnet, completely fine. 

Thanks.

**Comment by KaiyangZhou** [comment]
the weight file was saved with `.pth.tar`. You can directly load it with `torch.load()`

**Comment by Shamazo** [comment]
The issue turned out to be a python2/3 issue. Using just torch.load() threw an ascii error, but setting pickle to use 'latin1' fixed it.

**Comment by KaiyangZhou** [comment]
I see. Use `torchreid.utils.load_pretrained_weights()` then

**Comment by Shamazo** [comment]
Thank you, didn't see that helper function.
