### ISSUE TITLE
What is the args to call multiple gpu for the latest repo?

### ISSUE THREAD

**Issue by amandayeyan** [KaiyangZhou/deep-person-reid#233]
Hi Kaiyang, 
In the old thread of deep-person-reid, we can set gpu_devices=[0,1,2,3] for example. 
But now the current thread hit error to find gpu_devices. What is the latest args then to use multiple gpus?

**Comment by KaiyangZhou** [comment]
It's supposed to be the same command as shown here https://github.com/KaiyangZhou/deep-person-reid/blob/master/scripts/main.py#L110.

I only have one gpu so cannot test this option.
