### ISSUE TITLE
Model doesn't train till max_epoch for ilidsvid dataset.

### ISSUE THREAD

**Issue by srinivas-varadharajan** [KaiyangZhou/deep-person-reid#234]
Hey @KaiyangZhou ,

I tried to train the ilidsvid dataset. But, it doesn't train till max_epoch but goes to "=> Final test" right after training till fixbase_epoch.

 I'm not sure if I need to configure anything in specific for video datasets.

python scripts/main.py  --config-file configs/im_osnet_x1_0_softmax_256x128_amsgrad_cosine.yaml -s ilidsvid -t ilidsvid --transforms random_flip random_erase --root $PATH_TO_DATA --gpu-devices 0 data.save_dir log/osnet_x1_0_ilidsvid_softmax_cosinelr_2 data.type 'video' video.seq_len 5

I'm using the default values in the config file im_osnet_x1_0_softmax_256x128_amsgrad_cosine.yaml.

  max_epoch: 250
  fixbase_epoch: 10

output:
=> Start training
* Only train ['classifier'] (epoch: 1/10)
* Only train ['classifier'] (epoch: 2/10)
* Only train ['classifier'] (epoch: 3/10)
* Only train ['classifier'] (epoch: 4/10)
* Only train ['classifier'] (epoch: 5/10)
* Only train ['classifier'] (epoch: 6/10)
* Only train ['classifier'] (epoch: 7/10)
* Only train ['classifier'] (epoch: 8/10)
* Only train ['classifier'] (epoch: 9/10)
* Only train ['classifier'] (epoch: 10/10)
=> Final test
##### Evaluating ilidsvid (source) #####
Extracting features from query set ...

**Comment by KaiyangZhou** [comment]
set print-freq to 1
