### ISSUE TITLE
ValueError: expected 2D or 3D input (got 1D input) while inference

### ISSUE THREAD

**Issue by poormag** [KaiyangZhou/deep-person-reid#235]
Thanx for your deep-person-reid, KaiyangZhou. Im sure its  a kinda stupid question, but anyway I need some help. 

When im making just inference from your pretrained model I caught this ValueError. What kind of input should be to make infer if I do it by easy way:

transform = transforms.Compose([
    transforms.Resize(( 256,128 )),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225)),
])

img_ex = transform(img)
batch = torch.unsqueeze(img_ex, 0)
out = net(batch)

   **** .format(input.dim()))

**ValueError:** expected 2D or 3D input (got 1D input)

I tried to make this:

out = net(batch[None,])

but it only got worse:

**RuntimeError:** Expected 4-dimensional input for 4-dimensional weight 64 3 7 7 8243121639893246580, but got 5-dimensional input of size [1, 1, 3, 256, 128] instead

Sorry, for stupid question, but thanx for any advices.

**Comment by KaiyangZhou** [comment]
what do you see with this
```
print(img.shape)
img_ex = transform(img)
print(img_ex.shape)
batch = torch.unsqueeze(img_ex, 0)
print(batch.shape)
out = net(batch)
```

**Comment by poormag** [comment]
@KaiyangZhou , thanx for you reply, I got these shapes:

print(img.shape)
(107, 313, 3)

print(img_ex.shape)
torch.Size([3, 256, 128])

print(batch.shape)
torch.Size([1, 3, 256, 128])

out = net(batch)

**Comment by KaiyangZhou** [comment]
the dimension of batch seems to be fine, what's your net then?

**Comment by KaiyangZhou** [comment]
what's the code to reproduce your error if possible?

**Comment by poormag** [comment]
@KaiyangZhou My mistake, I have matched another pre-trained model with your ModelClass, so and all keys were successfully matched and i didnt pay attention to this until prediction. So now i have matched your pre-trained model and everything is okay. Sorry for disturbing. That model has different imput with yours...
