### ISSUE TITLE
How to extract features ?

### ISSUE THREAD

**Issue by djidje** [KaiyangZhou/deep-person-reid#236]
Hi,

first thank you for your work.

I would like to know how to extract features for each images for :
- training
- testing
- query

please ?

If it can be in a .pickle file in a OredredDict format should be great. Example for a resnet50 : 
dict({img01 : [array of 2048]}, {img02 : [array of 2048]}, ...)

Thank you.

EDIT : In engine.py we have access to features but not sure how to use them

**Comment by KaiyangZhou** [comment]
add your code around [here](https://github.com/KaiyangZhou/deep-person-reid/blob/master/torchreid/engine/engine.py#L232) to save features in whatever format you like

**Comment by Sushanti99** [comment]
Hey @KaiyangZhou 
I have a question on similar lines, your help would be appreciated. 

I use engine.run for my mars dataset using softmax-loss method described here https://kaiyangzhou.github.io/deep-person-reid/pkg/engine.html#base-engine 

Under the log folder in which I save my model, it is stored like this:
events.out.tfevents.1602080163.ip-172-31-26-80.9514.0
events.out.tfevents.1602080283.ip-172-31-26-80.9558.0

I'm not sure how I can use these for feature extraction.

**Comment by KaiyangZhou** [comment]
@Sushanti99 pls have a look at https://kaiyangzhou.github.io/deep-person-reid/user_guide.html#use-torchreid-as-a-feature-extractor-in-your-projects

don't hesitate to raise questions if that doesn't help

**Comment by Sushanti99** [comment]
I actually tried this out using:

>>> extractor = FeatureExtractor(
...     model_name='events.out.tfevents.1602080283.ip-172-31-26-80.9558.0',
...     model_path='/home/ubuntu/deep-person-reid/log/resnet50-softmax-mars-nohup',
...     device='cuda'
... )

It gives me an error as follows:

'Unknown model: {}. Must be one of {}'.format(name, avai_models)
KeyError: "Unknown model: events.out.tfevents.1602080283.ip-172-31-26-80.9558.0. Must be one of ['resnet18', 'resnet34', 'resnet50', 'resnet101', 'resnet152', 'resnext50_32x4d', 'resnext101_32x8d', 'resnet50_fc512', 'se_resnet50', 'se_resnet50_fc512', 'se_resnet101', 'se_resnext50_32x4d', 'se_resnext101_32x4d', 'densenet121', 'densenet169', 'densenet201', 'densenet161', 'densenet121_fc512', 'inceptionresnetv2', 'inceptionv4', 'xception', 'resnet50_ibn_a', 'resnet50_ibn_b', 'nasnsetmobile', 'mobilenetv2_x1_0', 'mobilenetv2_x1_4', 'shufflenet', 'squeezenet1_0', 'squeezenet1_0_fc512', 'squeezenet1_1', 'shufflenet_v2_x0_5', 'shufflenet_v2_x1_0', 'shufflenet_v2_x1_5', 'shufflenet_v2_x2_0', 'mudeep', 'resnet50mid', 'hacnn', 'pcb_p6', 'pcb_p4', 'mlfn', 'osnet_x1_0', 'osnet_x0_75', 'osnet_x0_5', 'osnet_x0_25', 'osnet_ibn_x1_0', 'osnet_ain_x1_0']"

I wasn't sure if the model had trained correctly/ something is wrong with the model format.

**Comment by KaiyangZhou** [comment]
`model_name` should take the name of an existing model, like `osnet_x1_0`, which has been registered

check this out https://github.com/KaiyangZhou/deep-person-reid/blob/master/torchreid/models/__init__.py

e.g., if you trained a `resnet50`, then set `model_name='resnet50'` (it is not the directory name where you save the model)

**Comment by Sushanti99** [comment]
Oh got it. So the model stored at checkpoint has to be given to the model_path? 
In my case '/home/ubuntu/deep-person-reid/log/resnet50-softmax-mars-nohup/events.out.tfevents.1602080283.ip-172-31-26-80.9558.0' ?

**Comment by KaiyangZhou** [comment]
the `events` file is a log saved for tensorboard visualization

the model weights are actually the file with extension `.tar`, `.pth.tar` or `.pth`

so the code looks like
```python
extractor = FeatureExtractor(
    model_name='resnet50',
    model_path='blah_blah.pth.tar',
    device='cuda'
)
```

**Comment by Sushanti99** [comment]
When you train it further, supposedly 

engine.run(
    max_epoch=60,
    save_dir='log/resnet50-softmax-mars',
    print_freq=10
)

Where is the newly trained model stored?

**Comment by KaiyangZhou** [comment]
it will be saved in the directory you specified

the model file name would be `model.pth.tar-60`

for finetuning the model further, don't forget to load the model before training (check the docs for more details)

I'd suggest you do a little experiment to double check everything is fine, just use epoch=1,2,3 for quick try

**Comment by Sushanti99** [comment]
Yeah, I followed exactly this https://kaiyangzhou.github.io/deep-person-reid/pkg/engine.html#video-engines
But there's no model.pth.tar-60 file, will recheck again, thanks so much!

**Comment by Sushanti99** [comment]
So I've been observing the logs

```
Extracting features from query set ...
Done, obtained 1980-by-2048 matrix
Extracting features from gallery set ...

```

And that's it. It takes forever and then eventually dies. No new weights are stored. 
No features for gallery set.
Do you know why this might be happening?

**Comment by KaiyangZhou** [comment]
maybe you can share the script or command that can reproduce your case
