### ISSUE TITLE
Random image transformation probability

### ISSUE THREAD

**Issue by ercanburak** [KaiyangZhou/deep-person-reid#24]
In [transforms.py](https://github.com/KaiyangZhou/deep-person-reid/blob/master/transforms.py), the probabilty variable p works the opposite way: Increasing p decreases the probability of performing the transformation. Line 31 can be changed to `if self.p < random.random():`

And by the way, have you tried training a model with transformation probability other than p=0.5? In the triplet loss paper (In Defense of the Triplet Loss for Person Re-Identification), this probability seems like 1; it is stated that the transformation is done to all images. Can we expect increased scores with higher transformation probabilities?

**Comment by KaiyangZhou** [comment]
Thanks for spotting this mistake, it has been fixed now.

I did not try different prob. Setting prob to 1 might improve the result marginally, not sure about that, but I think it would also increase the difficulty of convergence. prob = 0.5 is a good trade-off.

**Comment by ercanburak** [comment]
I tried setting p=1 and training with ResNet50M, Market1501 and xent+htri loss, with keeping other settings at their defaults; and get an mAP of 75.1 and a rank-1 score of 90.6. Maybe optimizing other parameters may give slightly better scores. Anyway, thanks for the answer.
