### ISSUE TITLE
Where is OSNet-AIN found in this repo?

### ISSUE THREAD

**Issue by Shamazo** [KaiyangZhou/deep-person-reid#241]
I am reading [this paper](https://arxiv.org/pdf/1910.06827.pdf) which was published recently and links this repo. Has the code for instance normalization and the architecture search been pushed to this repo yet? or is it still to come?

**Comment by KaiyangZhou** [comment]
not yet, please stay tuned

**Comment by Shamazo** [comment]
Thank you. The paper was very interesting to read.

**Comment by KaiyangZhou** [comment]
happy to hear that, my friend

**Comment by KaiyangZhou** [comment]
See this for further update https://github.com/KaiyangZhou/deep-person-reid/issues/242
