### ISSUE TITLE
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.

### ISSUE THREAD

**Issue by GuoGuoYao** [KaiyangZhou/deep-person-reid#243]
When "import torchreid",
i find "WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
", is this right ? Or  is there something wrong?

**Comment by KaiyangZhou** [comment]
it seems to be the caffe2 issue, maybe this can help? https://github.com/pytorch/pytorch/issues/9604

**Comment by lingbo666** [comment]
@GuoGuoYao have you solve it ?  wumaru hh
