### ISSUE TITLE
config file for Cross-domain ReID

### ISSUE THREAD

**Issue by ycwang11** [KaiyangZhou/deep-person-reid#245]
If I want to get the Cross-domain ReID result,R1:66.5,mAP:37.2, source: MSMT17,target:Market1501, which config file and loss  need to be used? Thank you.

**Comment by KaiyangZhou** [comment]
what's the model you are referring to?

**Comment by ycwang11** [comment]
OSNet

**Comment by KaiyangZhou** [comment]
https://github.com/KaiyangZhou/deep-person-reid/blob/master/configs/im_osnet_ibn_x1_0_softmax_256x128_amsgrad.yaml

**Comment by ycwang11** [comment]
Thank you.
