### ISSUE TITLE
model zoo

### ISSUE THREAD

**Issue by haohao900618** [KaiyangZhou/deep-person-reid#248]
Hello Kaiyang,
Thank you for your work!
I can't download ImageNet pretrained models from the https://kaiyangzhou.github.io/deep-person-reid/MODEL_ZOO.Can you tell me how I can download the models?

**Comment by KaiyangZhou** [comment]
perhaps it's due to some proxy problem? btw, can you access this website https://mega.nz/?

if you are looking for the imagenet pretrained osnet models, you can simply run the code to build the network which will automatically download the models (on google drive) via gdown.

**Comment by fengshuangme** [comment]
@KaiyangZhou  hi Kaiyang,
when i run the train sctipts, i can not connect google drive, so i can not download the pretrained model. 
if can i download the model singly and put it in somewhere folder?

**Comment by moyans** [comment]
put it on  ~/.cache/torch/checkpoints

**Comment by KaiyangZhou** [comment]
@moyans is right

or you can put the models wherever you like, and set `pretrained=False` in the config, simply use the `load_weights` arg to load the model weights

**Comment by ww5171351** [comment]
您好，学校网络原因，这个预训练下载不了，有什么其他链接么
