### ISSUE TITLE
Model&configs of MSMT17 dataset

### ISSUE THREAD

**Issue by SikaStar** [KaiyangZhou/deep-person-reid#257]
Hi,
Could you provide me with the trained model (osnet) and training configs of the supervised learning for MSMT17 dataset? In your paper, mAP of MSMT is 52.9 and R@1 is 78.7. However, the model in model zoo shows that mAP is 43.8 and R@1 is 74.9.

**Comment by KaiyangZhou** [comment]
try this https://github.com/KaiyangZhou/deep-person-reid/blob/master/configs/im_osnet_x1_0_softmax_256x128_amsgrad_cosine.yaml and add random erase to the transforms

**Comment by yian2271368** [comment]
@KaiyangZhou hey, i followed the yaml you provided, and added random erase, but the rank-1 results i got is only 60%. the dataset is MSMT17_V2
