### ISSUE TITLE
The program stopped when the epoch did not reach the specified number.

### ISSUE THREAD

**Issue by xiaoweihappy123** [KaiyangZhou/deep-person-reid#26]
Hello，The epoch I set is 30 times, but it runs to 20 times and it stops (on the market1501 dataset also). Is there any problem with the following commands?

The wrong hints are as follows：
Epoch: [20][3970/3983]	Time 0.359 (0.362)	Data 0.009 (0.008)	Loss 1.0619 (1.0747)	
Epoch: [20][3980/3983]	Time 0.341 (0.362)	Data 0.008 (0.008)	Loss 1.0882 (1.0747)	
==> Test
Extracted features for query set, obtained 1980-by-2048 matrix
Extracted features for gallery set, obtained 9330-by-2048 matrix
==> BatchTime(s)/BatchSize(img): 0.109/960
[3]+  已杀死    

The commands are as follows：
python train_img_model_xent.py -d market1501  -a resnet50 --max-epoch 30 --train-batch 128 --test-batch 64 --stepsize 20 --eval-step 20 --save-dir log/resnet50-xent-market1501 --gpu-devices 3
python train_vid_model_xent.py -d mars  -a resnet50 --max-epoch 30 --train-batch 128 --test-batch 64 --stepsize 20 --eval-step 20 --save-dir log/resnet50-xent-mars --gpu-devices 0

**Comment by KaiyangZhou** [comment]
it looks like the evaluation code does not work on your machine, perhaps you are facing [this error](https://github.com/KaiyangZhou/deep-person-reid/issues/21#issuecomment-394167078)

**Comment by xiaoweihappy123** [comment]
Thank you,I'll try again.

**Comment by xiaoweihappy123** [comment]
The problem was finally solved, leaving tears of excitement.

**Comment by KaiyangZhou** [comment]
could you share your solution here in case other people need it?

**Comment by xiaoweihappy123** [comment]
That's the solution to luzai in the link you gave me.

 change

    m, n = qf.size(0), gf.size(0)
    distmat = torch.pow(qf, 2).sum(dim=1, keepdim=True).expand(m, n) + \
              torch.pow(gf, 2).sum(dim=1, keepdim=True).expand(n, m).t()
    distmat.addmm_(1, -2, qf, gf.t())
    distmat = distmat.numpy()
to

qf = qf.numpy()
gf = gf.numpy()
from scipy.spatial.distance import cdist
distmat = cdist(qf, gf)
