### ISSUE TITLE
splits_prid2011.json link error

### ISSUE THREAD

**Issue by xonobo** [KaiyangZhou/deep-person-reid#260]
This [link](http://www.eecs.qmul.ac.uk/~kz303/deep-person-reid/datasets/prid2011/splits_prid2011.json) does not work

http://www.eecs.qmul.ac.uk/~kz303/deep-person-reid/datasets/prid2011/splits_prid2011.json

**Comment by KaiyangZhou** [comment]
try this https://drive.google.com/open?id=1qw7SI7YdIgfHetIQO7LLW4SHpL_qkieT
