### ISSUE TITLE
Merge image and video datasets

### ISSUE THREAD

**Issue by xonobo** [KaiyangZhou/deep-person-reid#261]
What is the main difference between image and video datasets?
How can I merge them or why should not I merge them? 

Any explanation or advice is very welcome.

**Comment by KaiyangZhou** [comment]
one samples images while the other samples tracklets

there is no way to merge these two for now as they have different parent classes

I assume you wanna use image-like training? if so, I suggest writing a new image dataset class which reads images from the datasets you want
