### ISSUE TITLE
Can  you release the splits.json of VIPeR and GRID datasets?

### ISSUE THREAD

**Issue by Lucky-BenXie** [KaiyangZhou/deep-person-reid#268]
Hi! Recently, I ran into problems with the VIPeR and GRID datsets.  Do you release the splits.json of VIPeR and GRID datasets? Looking forward to your reply！

**Comment by KaiyangZhou** [comment]
the code will create the json files itself so you don't need to worry

let me know if you have further problem

**Comment by Lucky-BenXie** [comment]
OK！Thank you!
