### ISSUE TITLE
about inference time of osnet_ain

### ISSUE THREAD

**Issue by faedtodd** [KaiyangZhou/deep-person-reid#271]
带佬，我用了osnet_ain，在我自己的数据集上，表现很好，但是测速的时候发现速度是resnet18的4倍那么慢（本想替代resnet18）
用tessorrt加速后（fp16），batchsize32，在titan xp上 28ms/batch，而resnet18 只有6ms/batch
但我看osnet_ain的模型大小和flops都比resnet18小
不知道问题出在哪

**Comment by KaiyangZhou** [comment]
though osnet models are small in size, the multi-stream structure makes it slow to some extend

e.g. the four streams in osnet differ in depth, meaning that the shallow streams need to wait for the deep streams before fusing their output

this is the price to pay for getting higher performance, which could possibly be solved by improving the multi-stream design in osnet

**Comment by faedtodd** [comment]
> shallow

感谢解答
