### ISSUE TITLE
Ignite

### ISSUE THREAD

**Issue by hfutzzw** [KaiyangZhou/deep-person-reid#272]
Thank you for your great contribution for Re-ID community, but I find that the current version based on ignite libraray was unfriendly to beginner of this field, although it simplified duplicate code, but make it much hard for beginner, could you please a previous version without ignite-based, thank you！

**Comment by KaiyangZhou** [comment]
maybe I can add more tutorials for beginners to learn the structure of this code?

the current engine design is not efficient enough, I plan to improve it to make it more extensible and flexible
