### ISSUE TITLE
OSNet can't reproduce the result in paper when train from scratch

### ISSUE THREAD

**Issue by runzeer** [KaiyangZhou/deep-person-reid#274]
I train OSNet from scratch by
```shell
python scripts/main.py \
--config-file configs/im_osnet_x1_0_softmax_256x128_amsgrad_cosine.yaml \
--transforms random_flip random_erase \
--root $PATH_TO_DATA
```
Only change `pretrained` from `True` to `False` in `configs/im_osnet_x1_0_softmax_256x128_amsgrad_cosine.yaml` as below
```python
model:
  name: 'osnet_x1_0'
  pretrained: False
```

However, I got the result `R1=92.0%, mAP=77.6%` on Market1501 which should be `R1=93.6%, mAP=81.0%`([paper](https://arxiv.org/abs/1905.00953)). Am I doing something wrong?

**Comment by valuefish** [comment]
I got the same issue.

**Comment by KaiyangZhou** [comment]
please refer to the paper regarding the detailed param setting https://arxiv.org/abs/1910.06827

also note that the training params for fine-tuning and training from scratch are different

**Comment by valuefish** [comment]
Thanks for your reply @KaiyangZhou !  I retrained the model according to your instructions and got `R1=93.7%,  mAP=80.6%` which is as expected. Thanks again!
