### ISSUE TITLE
error in hacnn : input is on cpu and grid is on cuda:0

### ISSUE THREAD

**Issue by BKL255** [KaiyangZhou/deep-person-reid#275]
when i run the model of hacnn ,i had stunk in the follow error:
 def stn(self, x, theta):
        """Performs spatial transform

        x: (batch, channel, height, width)
        theta: (batch, 2, 3)
        """

        grid = F.affine_grid(theta, x.size())
        x = F.grid_sample(x, grid)
        return x

RuntimeError: grid_sampler(): expected input and grid to be on same device, but input is on cpu and grid is on cuda:0
Do you have any insights for me?

**Comment by KaiyangZhou** [comment]
make sure you do `input =  input.cuda()` to move the input tensor to gpu

**Comment by BKL255** [comment]
ok，i see,thanks

**Comment by M-Ghorbel** [comment]
I have the same problem, pleas where should i add the Input = input.cuda()   ?
