### ISSUE TITLE
Segmentation fault (core dumped) when install package in develop mode

### ISSUE THREAD

**Issue by garyliu0816** [KaiyangZhou/deep-person-reid#276]
`(torchreid) hxr@cvnlpserver:~/liuhw/PyProjects/deep-person-reid$ python setup.py develop`
`Segmentation fault (core dumped)`
I have install the requirement and pytorch with cuda10.0, but fail in the last step, what's the problem?

**Comment by KaiyangZhou** [comment]
it would be helpful if you could provide more info about your system

**Comment by garyliu0816** [comment]
I change a new environment with latest cuda, and the problem solved,.

**Comment by KaiyangZhou** [comment]
good to hear that
