### ISSUE TITLE
warning can't load the pretrained weights

### ISSUE THREAD

**Issue by Ahnsun** [KaiyangZhou/deep-person-reid#277]
UserWarning: The pretrained weights "./log/old_MOT/hacnn_ibn_b_global+local_mot_person_softmax/model.pth.tar-150" cannot be loaded, please check the key names manually (** ignored and continue **)
  '(** ignored and continue **)'.format(weight_path)

**Comment by KaiyangZhou** [comment]
the error comes from https://github.com/KaiyangZhou/deep-person-reid/blob/master/torchreid/utils/torchtools.py#L295

it means none of the keys in your pretrained weights matches the model keys
