### ISSUE TITLE
OSNet_ain training process

### ISSUE THREAD

**Issue by Ahnsun** [KaiyangZhou/deep-person-reid#278]
Dear Author：
Could you please show me your training process of the model OSNet_ain，including the setting of parameters,such as lr,epoch,batch size and so on？It will be grateful if you can send me a .yaml of OSNet_ain!

**Comment by KaiyangZhou** [comment]
see projects/OSNet_AIN

**Comment by Ahnsun** [comment]
Thanks a lot发自我的华为手机-------- 原始邮件 --------发件人： Kaiyang <notifications@github.com>日期： 2019年12月21日周六 晚上7:23收件人： KaiyangZhou/deep-person-reid <deep-person-reid@noreply.github.com>抄送： Ahnsun <3261055226@qq.com>, Author <author@noreply.github.com>主    题： Re: [KaiyangZhou/deep-person-reid] OSNet_ain training process (#278)Closed #278.
