### ISSUE TITLE
Add label

### ISSUE THREAD

**Issue by Ahnsun** [KaiyangZhou/deep-person-reid#280]
Dear Author：
If I want to add a new label to my dataset and then have training and testing,which part of the code should I modify?Thank you

**Comment by KaiyangZhou** [comment]
check this https://kaiyangzhou.github.io/deep-person-reid/user_guide.html#use-your-own-dataset

for additional label excluding (impath, pid, camid), you might need to modify here https://github.com/KaiyangZhou/deep-person-reid/blob/master/torchreid/data/datasets/dataset.py#L263
