### ISSUE TITLE
A bug of speed

### ISSUE THREAD

**Issue by ljhandlwt** [KaiyangZhou/deep-person-reid#281]
In `torchreid.engine.engine.py`, you calculate the running time for a batch, as follows:
```
imgs, pids, camids = self._parse_data_for_eval(data)
if self.use_gpu:
    imgs = imgs.cuda()
end = time.time()
features = self._extract_features(imgs)
batch_time.update(time.time() - end)
features = features.data.cpu()
```
However, Pytorch adopted asynchronous execution for GPU operations.
https://pytorch.org/docs/stable/notes/cuda.html#asynchronous-execution

You will find `features = self._extract_features(imgs)` is very fast, and `features = features.data.cpu()` is very slow. Because the latter requires to wait for the truly finishing of the former.

A simple solution of this bug is as follows:
```
imgs, pids, camids = self._parse_data_for_eval(data)
if self.use_gpu:
    imgs = imgs.cuda()
end = time.time()
features = self._extract_features(imgs)
features = features.data.cpu()
batch_time.update(time.time() - end)
```
Comparing to the forward step, passing the data from GPU to CPU is very fast. So it would not bring a large measurement error.

**Comment by KaiyangZhou** [comment]
`batch_time` is mainly used to measure the gpu processing time

**Comment by ljhandlwt** [comment]
@KaiyangZhou 
But what you measure is not the true GPU processing time, because Pytorch adopted **asynchronous execution**. Thus, if you execute `features = self._extract_features(imgs)`, it will return immediately.

**Comment by KaiyangZhou** [comment]
adding `torch.cuda.Event` and `torch.cuda.synchronize()` could help
