### ISSUE TITLE
Misleading model complexity units in MZ

### ISSUE THREAD

**Issue by sovrasov** [KaiyangZhou/deep-person-reid#282]
In the model zoo model complexity units are GFLOPS but according to the code complexity is computed in GMACS. GFLOPS ~ 0.5 * GMACS 
The difference is noticable and clearly visible if one tries to use 3rd party tools to estimate complexity.

**Comment by KaiyangZhou** [comment]
the definition follows most papers, e.g. https://arxiv.org/pdf/1512.03385.pdf
