### ISSUE TITLE
Pretrained model OsNet

### ISSUE THREAD

**Issue by suman9868** [KaiyangZhou/deep-person-reid#286]
Hi @KaiyangZhou ,
Just wanted to know how can i use your OsNet pretrained model on new dataset ???
Also can share some reference for the same.

**Comment by KaiyangZhou** [comment]
can you make your question more specific?

**Comment by suman9868** [comment]
I have downloaded the OsNet pre-trained model but was not able to run it on our datasets which consists of two different folder (one folder contains images from one camera and other from different camera). 
So i want to compare images from both folder and want to know which one matches with one another for which i want to know where exactly should i use the path of the images and how can i use the pre-trained model (OsNet) for that.

**Comment by KaiyangZhou** [comment]
one way is to load your images into two lists (for camera A and b), use OSNet to extract features for each image, and then compare each feature from A to all features from B, after which you can get the top-k nearest images in B that match A

the alternative is to write a dataset class (https://kaiyangzhou.github.io/deep-person-reid/user_guide.html#use-your-own-dataset) and then use the built-in functions in torchreid to do the job
