### ISSUE TITLE
why always show 'cuda out of memory'

### ISSUE THREAD

**Issue by guanyonglai** [KaiyangZhou/deep-person-reid#288]
it has nothing to do with batch size, 

=> Start training
* Only train ['classifier'] (epoch: 1/10)
Traceback (most recent call last):
  File "scripts/main.py", line 164, in <module>
    main()
  File "scripts/main.py", line 160, in main
    engine.run(**engine_run_kwargs(cfg))
  File "/home/guanyonglai/gyl/goods_project/osnet-deep-person-reid/torchreid/engine/engine.py", line 122, in run
    open_layers=open_layers
  File "/home/guanyonglai/gyl/goods_project/osnet-deep-person-reid/torchreid/engine/image/softmax.py", line 95, in train
    outputs = self.model(imgs)
  File "/home/guanyonglai/anaconda3/envs/torchreid/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/guanyonglai/anaconda3/envs/torchreid/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 148, in forward
    inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)
  File "/home/guanyonglai/anaconda3/envs/torchreid/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 159, in scatter
    return scatter_kwargs(inputs, kwargs, device_ids, dim=self.dim)
  File "/home/guanyonglai/anaconda3/envs/torchreid/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 35, in scatter_kwargs
    inputs = scatter(inputs, target_gpus, dim) if inputs else []
  File "/home/guanyonglai/anaconda3/envs/torchreid/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 28, in scatter
    return scatter_map(inputs)
  File "/home/guanyonglai/anaconda3/envs/torchreid/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 15, in scatter_map
    return list(zip(*map(scatter_map, obj)))
  File "/home/guanyonglai/anaconda3/envs/torchreid/lib/python3.7/site-packages/torch/nn/parallel/scatter_gather.py", line 13, in scatter_map
    return Scatter.apply(target_gpus, None, dim, obj)
  File "/home/guanyonglai/anaconda3/envs/torchreid/lib/python3.7/site-packages/torch/nn/parallel/_functions.py", line 89, in forward
    outputs = comm.scatter(input, target_gpus, chunk_sizes, ctx.dim, streams)
  File "/home/guanyonglai/anaconda3/envs/torchreid/lib/python3.7/site-packages/torch/cuda/comm.py", line 147, in scatter
    return tuple(torch._C._scatter(tensor, devices, chunk_sizes, dim, streams))
RuntimeError: CUDA error: out of memory (malloc at /pytorch/c10/cuda/CUDACachingAllocator.cpp:241)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f01581aa441 in /home/guanyonglai/anaconda3/envs/torchreid/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7f01581a9d7a in /home/guanyonglai/anaconda3/envs/torchreid/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x1581d (0x7f015775881d in /home/guanyonglai/anaconda3/envs/torchreid/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x16247 (0x7f0157759247 in /home/guanyonglai/anaconda3/envs/torchreid/lib/python3.7/site-packages/torch/lib/libc10_cuda.so)
frame #4: at::native::empty_cuda(c10::ArrayRef<long>, c10::TensorOptions const&) + 0x121 (0x7f0087143f81 in /home/guanyonglai/anaconda3/envs/torchreid/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so)
frame #5: at::CUDAType::empty(c10::ArrayRef<long>, c10::TensorOptions const&) const + 0x19b (0x7f0085d8b6fb in /home/guanyonglai/anaconda3/envs/torchreid/lib/python3.7/site-packages/torch/lib/libcaffe2_gpu.so)
frame #6: torch::autograd::VariableType::empty(c10::ArrayRef<long>, c10::TensorOptions const&) const + 0x284 (0x7f0152824094 in /home/guanyonglai/anaconda3/envs/torchreid/lib/python3.7/site-packages/torch/lib/libtorch.so.1)
frame #7: at::native::to(at::Tensor const&, c10::TensorOptions const&, bool, bool) + 0x506 (0x7f0129a98666 in /home/guanyonglai/anaconda3/envs/torchreid/lib/python3.7/site-packages/torch/lib/libcaffe2.so)
frame #8: at::TypeDefault::to(at::Tensor const&, c10::TensorOptions const&, bool, bool) const + 0x17 (0x7f0129d17857 in /home/guanyonglai/anaconda3/envs/torchreid/lib/python3.7/site-packages/torch/lib/libcaffe2.so)
frame #9: torch::autograd::VariableType::to(at::Tensor const&, c10::TensorOptions const&, bool, bool) const + 0x2c2 (0x7f015270db52 in /home/guanyonglai/anaconda3/envs/torchreid/lib/python3.7/site-packages/torch/lib/libtorch.so.1)
frame #10: torch::cuda::scatter(at::Tensor const&, c10::ArrayRef<long>, c10::optional<std::vector<long, std::allocator<long> > > const&, long, c10::optional<std::vector<c10::optional<c10::cuda::CUDAStream>, std::allocator<c10::optional<c10::cuda::CUDAStream> > > > const&) + 0x389 (0x7f0152c61fd9 in /home/guanyonglai/anaconda3/envs/torchreid/lib/python3.7/site-packages/torch/lib/libtorch.so.1)
frame #11: <unknown function> + 0x5a41cf (0x7f0158b9a1cf in /home/guanyonglai/anaconda3/envs/torchreid/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #12: <unknown function> + 0x130fac (0x7f0158726fac in /home/guanyonglai/anaconda3/envs/torchreid/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #20: THPFunction_apply(_object*, _object*) + 0x6b1 (0x7f01589aa301 in /home/guanyonglai/anaconda3/envs/torchreid/lib/python3.7/site-packages/torch/lib/libtorch_python.so)

**Comment by KaiyangZhou** [comment]
never met such error before

is there a way to reproduce your error? did you make any changes to the code? is it possible that there is a problem with your cuda/gpu?

**Comment by guanyonglai** [comment]
我查了下，原来代码是默认会占用所有的卡，用了 os.environ['CUDA_VISIBLE_DEVICES'] = '3,4' 进行约束也不好使，训练batch设为32时,7个卡平均每个卡占600多M，怎样才能约束使用的GPU呢

**Comment by Ahnsun** [comment]
需要注释上面的一行代码，再固定GPU发自我的华为手机-------- 原始邮件 --------发件人： guanyonglai <notifications@github.com>日期： 2020年1月7日周二 中午11:28收件人： KaiyangZhou/deep-person-reid <deep-person-reid@noreply.github.com>抄送： Subscribed <subscribed@noreply.github.com>主    题： Re: [KaiyangZhou/deep-person-reid] why always show 'cuda out of memory' (#288)我查了下，原来代码是默认会占用所有的卡，用了 os.environ['CUDA_VISIBLE_DEVICES'] = '3,4' 进行约束也不好使，训练batch设为32时,7个卡平均每个卡占600多M，怎样才能约束使用的GPU呢

**Comment by guanyonglai** [comment]
torch.cuda.manual_seed_all(cfg.train.seed) 这一句注释掉了，还是会默认使用所有GPU

**Comment by KaiyangZhou** [comment]
see https://github.com/KaiyangZhou/deep-person-reid/blob/master/README.rst#a-unified-interface

**Comment by KaiyangZhou** [comment]
`.cuda()` by default will copy the network to all available gpus, unless you specify cuda_visible_devices

**Comment by guanyonglai** [comment]
"set_random_seed(cfg.train.seed) " this sentence has been commented out,
and I have been added environment variables "os.environ['CUDA_VISIBLE_DEVICES'] = '3,4' " in the start , but it still takes up all gpus. How to solve this problem?

**Comment by KaiyangZhou** [comment]
does `CUDA_VISIBLE_DEVICES=0 python script.py` work?
