### ISSUE TITLE
activation map code bug

### ISSUE THREAD

**Issue by hfutzzw** [KaiyangZhou/deep-person-reid#291]
[https://github.com/KaiyangZhou/deep-person-reid/blob/master/tools/visualize_actmap.py#L100](url)
`                am = 255 * (am - np.max(am)) / (
                    np.max(am) - np.min(am) + 1e-12
                )`
should be modified to 
`                am = 255 * (am - np.min(am)) / (
                    np.max(am) - np.min(am) + 1e-12
                )`

**Comment by KaiyangZhou** [comment]
good spot, fixed now
