### ISSUE TITLE
How effective would this be for Face Reid?

### ISSUE THREAD

**Issue by anuar12** [KaiyangZhou/deep-person-reid#295]
Thanks for a great repo! 
How effective would these networks (OSNet AIN) be for face reid?

**Comment by KaiyangZhou** [comment]
some guys in ICCV told me they used OSNet-1.0 for face recognition and it works very well

**Comment by anuar12** [comment]
Great thanks!

**Comment by youngjae-avikus** [comment]
> some guys in ICCV told me they used OSNet-1.0 for face recognition and it works very well

Is there a paper that can be referenced?
