### ISSUE TITLE
Is this normal that if you train the model on market and test on dukemtmcreid, the rank1 on dukemtmcreid become very low(only 35.1%))

### ISSUE THREAD

**Issue by talentCODE** [KaiyangZhou/deep-person-reid#296]

**Comment by KaiyangZhou** [comment]
Yes! You just identified the most practical problem of deploying re-id models in real-world applications (a large-scale training dataset would be very useful).

Check out our latest paper https://arxiv.org/abs/1910.06827 which talks about this issue
