### ISSUE TITLE
os.environ['CUDA_VISIBLE_DEVICES'] = '3,4' 一定要在 import torchreid 之前设置

### ISSUE THREAD

**Issue by guanyonglai** [KaiyangZhou/deep-person-reid#297]
os.environ['CUDA_VISIBLE_DEVICES'] = '3,4' 一定要在 import torchreid 之前设置，否则设置无效

**Comment by KaiyangZhou** [comment]
https://github.com/KaiyangZhou/deep-person-reid/issues/267
