### ISSUE TITLE
basic infomation about paper 

### ISSUE THREAD

**Issue by Adorablepet** [KaiyangZhou/deep-person-reid#298]
Thanks for sharing such a good project.I have a few questions about the paper.
First, how `DML` is implemented in code?
Second, what dose `DML model-1+2` mean?

**Comment by KaiyangZhou** [comment]
DML trains two models simultaneously, so model-1+2 means model ensemble.

I have been super super busy recently and could not find time to update the code.

Will upgrade torchreid in 03.2020.

**Comment by Adorablepet** [comment]
@KaiyangZhou ok, you are my idol, thanks.

**Comment by KaiyangZhou** [comment]
The code of DML has been released at https://github.com/KaiyangZhou/deep-person-reid/tree/master/projects/DML

**Comment by Adorablepet** [comment]
@KaiyangZhou thanks.
