### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9b in position 1: ordinal not in range(128)

### ISSUE THREAD

**Issue by khaerulumam42** [KaiyangZhou/deep-person-reid#3]
Hello @KaiyangZhou , thank you for make this project.
I try to running test on prid 2011 dataset using ResNet50m pretrained model you give, but got error

> UnicodeDecodeError: 'ascii' codec can't decode byte 0x9b in position 1: ordinal not in range(128)

I think this error appear because pretrained model resnet50m_xent_prid.pth.tar which can only open using Microsoft Windows OS (I don't know is true or not), but when I type `file resnet50m_xent_prid.pth.tar` got this message

> resnet50m_xent_prid.pth.tar: 8086 relocatable (Microsoft)

How can I use that pretrained model on linux meanwhile pytorch can't install on windows?

Thank you :)

**Comment by KaiyangZhou** [comment]
@khaerulumam42 

It's a bit weird because I ran the code on centOS rather than windows. I could open the weights on Mac OS. Perhaps [this post](https://stackoverflow.com/questions/21129020/how-to-fix-unicodedecodeerror-ascii-codec-cant-decode-byte) is helpful? I am not sure. Please try and let me know.

**Comment by khaerulumam42** [comment]
Okay I will try soon. What version python you use? because [this post](https://stackoverflow.com/questions/21129020/how-to-fix-unicodedecodeerror-ascii-codec-cant-decode-byte) just for python 2, for python 3 auto to utf-8.
Thank you

**Comment by KaiyangZhou** [comment]
I used python 2.7

**Comment by khaerulumam42** [comment]
Sorry for late answer.
I have tried mars and prid pretrained model using python 2.7 and success open file but still got problem on my pytorch, I will find the solver latter. On python 3 still got same problem on prid pretrained model, even though the default unicode of python 3 is utf-8, maybe must training on python 3 (but non-sense). Mars pretrained model successfully open on python 3.

**Comment by brchlluk** [comment]
For Python 3, you have to edit torch/serialization.py file. Add this to line 469.
```
    _sys_info = pickle_module.load(f, encoding='latin1')
    unpickler = pickle_module.Unpickler(f, encoding='latin1')

```
![image](https://user-images.githubusercontent.com/18639856/39348998-9c9ead1c-49f9-11e8-83af-10551d886b90.png)

**Comment by hsfzxjy** [comment]
Now should be line 539 for pytorch 0.4.1.
