### ISSUE TITLE
Training parameters of Mars dataset

### ISSUE THREAD

**Issue by xiaoweihappy123** [KaiyangZhou/deep-person-reid#30]
Because the result of my training is always about 3% worse than the result you provided, so I guess it's the training parameters. My training parameters are as follows:

python train_vid_model_xent_htri.py -d mars  -a resnet50m --max-epoch 500 --train-batch 128 --test-batch 32 --stepsize 200 --eval-step 20 --save-dir log/resnet50m-xent-htri-mars --gpu-devices 0

**Comment by KaiyangZhou** [comment]
please try the default settings and see what you can get

**Comment by xiaoweihappy123** [comment]
ok,is running.

**Comment by KaiyangZhou** [comment]
good good

**Comment by AlekseySh** [comment]
**@xiaoweihappy123**

Can you say please, what map and rank-1 values you get on MARS while training with deep-person-reid code?

**Comment by xiaoweihappy123** [comment]
default settings

==> Test
Extracted features for query set, obtained 1980-by-3072 matrix
Extracted features for gallery set, obtained 9330-by-3072 matrix
==> BatchTime(s)/BatchSize(img): 0.015/75
Computing CMC and mAP
Results ----------
mAP: 75.2%
CMC curve
Rank-1  : 81.1%
Rank-5  : 93.5%
Rank-10 : 95.3%
Rank-20 : 96.5%
------------------
==> Best Rank-1 81.1%, achieved at epoch 500
Finished. Total elapsed time (h:m:s): 2:57:11. Training time (h:m:s): 2:47:26.

**Comment by TheBobbyliu** [comment]
> default settings
> 
> ## ==> Test
> Extracted features for query set, obtained 1980-by-3072 matrix
> Extracted features for gallery set, obtained 9330-by-3072 matrix
> ==> BatchTime(s)/BatchSize(img): 0.015/75
> Computing CMC and mAP
> Results ----------
> mAP: 75.2%
> CMC curve
> Rank-1 : 81.1%
> Rank-5 : 93.5%
> Rank-10 : 95.3%
> Rank-20 : 96.5%
> ==> Best Rank-1 81.1%, achieved at epoch 500
> Finished. Total elapsed time (hs): 2:57:11. Training time (hs): 2:47:26.

Could you please tell me what kind of GPU you used? Running Mars dataset for 500 epochs takes several days for me, how could you finish the training in 3 hours?

**Comment by xiaoweihappy123** [comment]
Tian xp

**Comment by J-LINC** [comment]
> default settings
> 
> ## ==> Test
> Extracted features for query set, obtained 1980-by-3072 matrix
> Extracted features for gallery set, obtained 9330-by-3072 matrix
> ==> BatchTime(s)/BatchSize(img): 0.015/75
> Computing CMC and mAP
> Results ----------
> mAP: 75.2%
> CMC curve
> Rank-1 : 81.1%
> Rank-5 : 93.5%
> Rank-10 : 95.3%
> Rank-20 : 96.5%
> ==> Best Rank-1 81.1%, achieved at epoch 500 Finished. Total elapsed time (hms): 2:57:11. Training time (hms): 2:47:26.

i got a better result:
![image](https://user-images.githubusercontent.com/89594867/236626201-6250d670-c3bf-49c7-ba9d-697f0b1c3996.png)
