### ISSUE TITLE
Question about ResNet-50

### ISSUE THREAD

**Issue by muna-cs** [KaiyangZhou/deep-person-reid#300]
What is the difference between fc and classifier ?
fc: 
https://github.com/KaiyangZhou/deep-person-reid/blob/6216cdb2a5976ba7f8888186fd4b76b10d552fc3/torchreid/models/resnet_ibn_a.py#L167
classifier :
https://github.com/KaiyangZhou/deep-person-reid/blob/6216cdb2a5976ba7f8888186fd4b76b10d552fc3/torchreid/models/resnet_ibn_a.py#L170

Is the main architecture of Resnet-50 has FC?

**Comment by KaiyangZhou** [comment]
`fc` means fully connected layers, while `classifier` means the last linear layer for classification
