### ISSUE TITLE
Proper way to export the model to onnx

### ISSUE THREAD

**Issue by stereomatchingkiss** [KaiyangZhou/deep-person-reid#302]
```
import torchreid

torchreid.models.show_avai_models()

model = torchreid.models.build_model(name='osnet_ain_x1_0', num_classes=1000)

torchreid.utils.load_pretrained_weights(model, "osnet_ain_x1_0_msmt17_256x128_amsgrad_ep50_lr0.0015_coslr_b64_fb10_softmax_labsmth_flip_jitter.pth") 

from torch.autograd import Variable
import torch
import onnx

input_name = ['input']
output_name = ['output']
input = Variable(torch.randn(1, 3, 256, 128))
torch.onnx.export(model, input, 'osnet_ain_x1_0.onnx', input_names=input_name,output_names=output_name, verbose=True, export_params=True)

The model after convert only 10633KBytes, while the pytorch model got 16888KBytes

onnx_model = onnx.load("osnet_ain_x1_0.onnx")
onnx.checker.check_model(onnx_model)

```

1. The output messages seems all fine, but is this the correct way?
2. What is the num_classes I should set?
3. Am I using correct input_name and output_name 

Model before convert is 16888KB, model after convert only got 10633KB

**Comment by stereomatchingkiss** [comment]
Guess the number of class should be 4101

**Comment by KaiyangZhou** [comment]
Based on what I have learned from https://pytorch.org/docs/stable/onnx.html#example-end-to-end-alexnet-from-pytorch-to-onnx, I don't see any obvious error in your code. The `num_classes` variable doesn't matter as the last linear classifier is not used during testing.

Maybe @RodMech has some experience on this problem?

**Comment by stereomatchingkiss** [comment]
> 
> 
> Based on what I have learned from https://pytorch.org/docs/stable/onnx.html#example-end-to-end-alexnet-from-pytorch-to-onnx, I don't see any obvious error in your code. The `num_classes` variable doesn't matter as the last linear classifier is not used during testing.
> 
> Maybe @RodMech has some experience on this problem?

Thanks, I will post how to use the model after translated after it work. opencv dnn module cannot load the model translated by pytorch yet, looks like I need to use libtorch for this purpose.

ps : Can you speak Chinese?

**Comment by RodMech** [comment]
Hi @KaiyangZhou and @stereomatchingkiss , 

Unfortunately, I have never exported a toch model with onnx.
I was checking the source code of the function "export" [here](https://pytorch.org/docs/stable/_modules/torch/onnx.html#export). And it says:

`        input_names(list of strings, default empty list): names to assign to the
            input nodes of the graph, in order`

`         output_names(list of strings, default empty list): names to assign to the
            output nodes of the graph, in order`

Would you please leave them as None? (It is the value given by default). I have seen that [here](http://seba1511.net/tutorials/advanced/super_resolution_with_caffe2.html), they do not mention any graph input/output names, and If I am not wrong, it is just for readability.

Would you print both outputs after onnx.checker.check_model(onnx_model)?

**Comment by stereomatchingkiss** [comment]
>Would you please leave them as None

No problem, tried and same error message

>Would you print both outputs after onnx.checker.check_model(onnx_model)?

it do not print any message


By the way, I post the bug report to the [opencv issue list](https://github.com/opencv/opencv/issues/16476).

**Comment by RodMech** [comment]
Thanks, 
Would you please print `onnx.helper.printable_graph(model.graph)`?
And paste the results?

**Comment by stereomatchingkiss** [comment]
>Would you please print onnx.helper.printable_graph(model.graph)?

Tried, print nothing either, weird.

I tried to export it to the jit module of pytorch, but it fails, then I try to export it to ScriptModule, fails either, in order to make it works, I change the codes of forward(osnet_ain.py) to

```
def forward(self, x):
        return self.featuremaps(x)
```

Convert  by codes

```
import torchreid

torchreid.models.show_avai_models()

model = torchreid.models.build_model(name='osnet_ain_x1_0', num_classes=1041)

torchreid.utils.load_pretrained_weights(model, "osnet_ain_x1_0_msmt17_256x128_amsgrad_ep50_lr0.0015_coslr_b64_fb10_softmax_labsmth_flip_jitter.pth")

import torch
import torchvision


# An example input you would normally provide to your model's forward() method.
example = torch.rand(1, 3, 256, 128)

# Use torch.jit.trace to generate a torch.jit.ScriptModule via tracing.
traced_script_module = torch.jit.trace(model, example)

output = traced_script_module(torch.ones(1, 3, 256, 128))
print(output.shape) #print torch.Size([1, 512, 16, 8])
```

This eliminate the dynamic change of types at runtime, I guess self.featuremaps(x) is the output features we need to compare the similarity between pedestrian?

Load it from c++(tried with qmake, but fail to compile)

```
#undef slots
#include <torch/script.h>
//#def slots Q_SLOTS

#include <iostream>
#include <memory>

int main()
{
    try {
        // Deserialize the ScriptModule from a file using torch::jit::load().
        torch::jit::script::Module module = torch::jit::load("traced_osnet_ain_x1_0.pt");

        // Create a vector of inputs.
        std::vector<torch::jit::IValue> inputs;
        inputs.push_back(torch::ones({1, 3, 256, 128}));

        // Execute the model and turn its output into a tensor.
        at::Tensor output = module.forward(inputs).toTensor();

        std::cout<<output.sizes()<<std::endl;
    }catch(const c10::Error& e){
        std::cerr << e.what() << "\n";
        return -1;
    }

    std::cout << "ok\n";
}

```

output are 

```
[1, 512, 16, 8]
ok
```

The features we need to compare are 512*16*8?

**Comment by RodMech** [comment]
No, they are only 512.

**Comment by stereomatchingkiss** [comment]
> No, they are only 512 per person.

Thanks, then why there are 65536 value?
Which 512 value I should access?

**Comment by RodMech** [comment]
I would love to see a summary of the model before even considering any other things. 
First, we need to be 100% sure that the model has been translated correctly to onnx. 
Until we are not absolutely certain, there is no point in thinking that your output is meaningful.

**Comment by stereomatchingkiss** [comment]
> I would love to see a summary of the model before even considering any other things.

At last I got the output, need to print it out manually, since it is too long I put it at [pastebin](https://pastebin.com/MJR5qFAU).

This time I test it with the output value.

```
import torchreid

torchreid.models.show_avai_models()

model = torchreid.models.build_model(name='osnet_ain_x1_0', num_classes=1041)
torchreid.utils.load_pretrained_weights(model, "osnet_ain_x1_0_msmt17_256x128_amsgrad_ep50_lr0.0015_coslr_b64_fb10_softmax_labsmth_flip_jitter.pth") 

model.eval()

from torch.autograd import Variable
import torch
import onnx

# An example input you would normally provide to your model's forward() method.
input = torch.ones(1, 3, 256, 128)
raw_output = model(input)

torch.onnx.export(model, input, 'osnet_ain_x1_0.onnx', verbose=False, export_params=True)

print("-------------------------check model---------------------------------------\n")

try:
    onnx_model = onnx.load("osnet_ain_x1_0.onnx")
    onnx.checker.check_model(onnx_model)
    graph_output = onnx.helper.printable_graph(onnx_model.graph)
    with open("graph_output.txt", mode="w") as fout:
        fout.write(graph_output)	
except:
    print("Something went wrong")
	
	
import onnxruntime
import numpy as np

ort_session = onnxruntime.InferenceSession("osnet_ain_x1_0.onnx")

def to_numpy(tensor):
    return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()

# compute ONNX Runtime output prediction
ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(input)}
ort_outs = ort_session.run(None, ort_inputs)	

# compare ONNX Runtime and PyTorch results
np.testing.assert_allclose(to_numpy(raw_output), ort_outs[0], rtol=1e-03, atol=1e-05)

print("Exported model has 
```been tested with ONNXRuntime, and the result looks good!")

It raises exception

AssertionError:
Not equal to tolerance rtol=0.001, atol=1e-05

```
Mismatched elements: 13 / 512 (2.54%)
Max absolute difference: 0.00070047
Max relative difference: 0.02552379
 x: array([[9.402755e-05, 2.179507e+00, 3.834043e-01, 2.136301e-01,
        0.000000e+00, 0.000000e+00, 8.341767e-01, 2.012278e+00,
        3.984281e-01, 5.461890e-02, 2.032685e-01, 7.745304e-06,...
 y: array([[9.402186e-05, 2.179636e+00, 3.834159e-01, 2.135554e-01,
        0.000000e+00, 0.000000e+00, 8.342320e-01, 2.012077e+00,
        3.984202e-01, 5.461205e-02, 2.032657e-01, 7.745568e-06,...
```

However, I can output the model to by `torch.jit.trace(model, example)`, check with the output and it works fine.

**Comment by RodMech** [comment]
What is the dimension of the `raw_output`?

**Comment by stereomatchingkiss** [comment]
> 
> 
> What is the dimension of the `raw_output`?

torch.Size([1, 512])

**Comment by RodMech** [comment]
And `ort_outs` is [1, 512, 16, 8]?

**Comment by stereomatchingkiss** [comment]
> 
> 
> And `ort_outs` is [1, 512, 16, 8]?

no, same dimension too, I should not change the codes of forward but call this

`model.eval()`

**Comment by RodMech** [comment]
Ok, so the onnx model has been tested and it works, but results are slightly different from the original. 
So from our side, this issue is closed?

**Comment by stereomatchingkiss** [comment]
> 
> 
> Ok, so the onnx model has been tested and it works, but results are slightly different from the original.
> So from our side, this issue is closed?

Yes, I think the bug is in opencv, thanks for your help

**Comment by MuhammadAsadJaved** [comment]
@RodMech  @stereomatchingkiss   Can you tell me please How I can convert [ResNet-50-reID model](chrome-extension://bigefpfhnfcobdlfbedofhhaibnlghod/mega/secure.html#file/VTpkWSbS#Y8gDnmg7u-sPwnZDhWXrtZNYOj7UYL4QzZkhDf1qWW4)  to .onnx?

**Comment by mikel-brostrom** [comment]
I have a working [multibackend](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/master/strong_sort/reid_multibackend.py) (ONNX, OpenVINO and TFLite) class for for the ReID models that I manged to export (Mobilenet and ResNet50, no luck with the OSNet model yet) with my [export script](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/master/reid_export.py). My export pipeline is as follows: PT --> ONNX --> OpenVINO --> TFLite. Feel free to experiment with it. Don't forget to drop a PR if yu have any improvements! smile

**Comment by FoxHound0x00** [comment]
> 

I'm getting the same issue :
```
---------------------------------------------------------------------------

AssertionError                            Traceback (most recent call last)

[<ipython-input-14-ae31a7aa8b62>](https://localhost:8080/#) in <cell line: 36>()
     34 
     35 # compare ONNX Runtime and PyTorch results
---> 36 np.testing.assert_allclose(to_numpy(raw_output), ort_outs[0], rtol=1e-03, atol=1e-05)
     37 
     38 print("Exported model has been tested with ONNXRuntime, and the result looks good!")

    [... skipping hidden 1 frame]

[/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py](https://localhost:8080/#) in assert_array_compare(comparison, x, y, err_msg, verbose, header, precision, equal_nan, equal_inf)
    842                                 verbose=verbose, header=header,
    843                                 names=('x', 'y'), precision=precision)
--> 844             raise AssertionError(msg)
    845     except ValueError:
    846         import traceback

AssertionError: 
Not equal to tolerance rtol=0.001, atol=1e-05

Mismatched elements: 2 / 512 (0.391%)
Max absolute difference: 0.00196075
Max relative difference: 0.00353949
 x: array([[0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        2.219892e+01, 0.000000e+00, 1.053157e+02, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 6.928540e+00, 0.000000e+00,...
 y: array([[0.000000e+00, 0.000000e+00, 0.000000e+00, 0.000000e+00,
        2.219951e+01, 0.000000e+00, 1.053151e+02, 0.000000e+00,
        0.000000e+00, 0.000000e+00, 6.928965e+00, 0.000000e+00,...
```

The onnx model works without any hiccups ,right ?
