### ISSUE TITLE
Inference on own dataset

### ISSUE THREAD

**Issue by GiBg1aN** [KaiyangZhou/deep-person-reid#304]
Hello, I cannot find any available issues about this:
I have a dataset which made of people coordinates/bounding boxes in images, can I use pre-trained models on that to perform inference? I don't want to evaluate the model with a metric, but only to see a visual output of PIDs

Thank you in advance

**Comment by KaiyangZhou** [comment]
that's doable. just import your images and forward them to the model, then do a comparison to find the closest ones

**Comment by GiBg1aN** [comment]
Thank you
