### ISSUE TITLE
Do you have any Squeezenet model results?

### ISSUE THREAD

**Issue by Ongoza** [KaiyangZhou/deep-person-reid#306]
Looks like this is the most fast model. Did you try use it? 
Do you have any Squeezenet model results?

**Comment by KaiyangZhou** [comment]
https://github.com/KaiyangZhou/deep-person-reid/blob/v0.5.0/MODEL_ZOO.md

try if `osnet_x0_25 ` suits your need

**Comment by Ongoza** [comment]
Thank you. 
Of course I already tried it. 
The osnet_x0_25 has a good quality but it's in 2 times slower than Squeezenet1_1. 
This model  https://github.com/nwojke/deep_sort/blob/master/tools/freeze_model.py  is very fast and have good quality but it's for TF. I am thinking to convert it it Pytorch but don't know how many  a time it takes.
