### ISSUE TITLE
Use OSNet with vehicle re-identification problems

### ISSUE THREAD

**Issue by quoccuonglqd** [KaiyangZhou/deep-person-reid#308]
Hello, I am working with vehicle re-identification problems. As this architecture is originally developed for person re-id, I wonder if I should use it for my problem.
Thank you

**Comment by KaiyangZhou** [comment]
it definitely worths a try

**Comment by quoccuonglqd** [comment]
Hello, I have 1 more question. My task has its own evaluation tool. What I try to do here is training the model and forward the query image into it. So when I start training, can I leave the query and the gallery list empty?

**Comment by KaiyangZhou** [comment]
Yes.

I suggest you have a read at the source code (the Engine class)

**Comment by quoccuonglqd** [comment]
I trained with resnet50 and osnet_x1_0. Then, I loaded the trained model and use it as feature extraction. Everything worked well with resnet50. But with osnet_x1_0, I got the "CUDA out of memory" message in the _extract_features function. My GPU has a 5GB ram. Do you have any suggestions for it?

**Comment by KaiyangZhou** [comment]
the testing memory should be low as the intermediate gradients are not saved

please check
1) is the batch size too big?
2) is the code run under the `with torch.no_grad()` scope?
