### ISSUE TITLE
IndexError: index 2 is out of bounds for axis 0 with size 1 in  eval_cuhk03

### ISSUE THREAD

**Issue by jpainam** [KaiyangZhou/deep-person-reid#31]
https://github.com/KaiyangZhou/deep-person-reid/blob/b19c5a3ffe69d3da3359e46b2a32d45f813f838a/eval_metrics.py#L25

```python
Traceback (most recent call last):
  File "eval_metrics.py", line 25, in eval_cuhk03
    matches = (g_pids[indices] == q_pids[:, np.newaxis]).astype(np.int32)
IndexError: index 2 is out of bounds for axis 0 with size 1
```
Kindly check this

**Comment by KaiyangZhou** [comment]
would you be able to provide detailed commands that led to such error?

**Comment by jpainam** [comment]
Hi!
Sorry, an error from side. I was using `eval_cuhk03`  in own code and needed to make sure `g_pids = [...]` and not `[[....]]`
Solved it.
Thanks
