### ISSUE TITLE
How can I use torchreid as a package like numpy in my environment?

### ISSUE THREAD

**Issue by gk966988** [KaiyangZhou/deep-person-reid#313]
I install torchreid and create a new environment named "torchreid" as your description, but I don't find it in my torchreid and I can't import torchreid in pycharm when I set the environment to torchreid. How can I do?

**Comment by KaiyangZhou** [comment]
I'm not a pycharm user so cannot provide useful tips, just googled it and found this https://www.jetbrains.com/help/pycharm/conda-support-creating-conda-virtual-environment.html
