### ISSUE TITLE
how to add images in the tensorboard?

### ISSUE THREAD

**Issue by chunniunai220ml** [KaiyangZhou/deep-person-reid#315]
hi,thanks for you repo. I want to konw how to show input image and feature maps in the tensorboard?

**Comment by KaiyangZhou** [comment]
do you mean this https://kaiyangzhou.github.io/deep-person-reid/user_guide.html#visualize-activation-maps?

**Comment by chunniunai220ml** [comment]
> do you mean this https://kaiyangzhou.github.io/deep-person-reid/user_guide.html#visualize-activation-maps?

No,I have understand the vis-act-map function. I want to konw feature maps show in tensorboard images,not only scalar picture.

**Comment by KaiyangZhou** [comment]
you need to write the code to save images in the summary writer

**Comment by chunniunai220ml** [comment]
> you need to write the code to save images in the summary writer

I have solve the problem by add_image, thank you!
