### ISSUE TITLE
onnx model

### ISSUE THREAD

**Issue by alicera** [KaiyangZhou/deep-person-reid#316]
could you provide the export onnx model , thanks

**Comment by KaiyangZhou** [comment]
you can follow this https://pytorch.org/docs/stable/onnx.html

**Comment by alicera** [comment]
how about the network inference ? like feature dim (1,13x13) represent one person ,so it will compare other person with L2 norm distance

**Comment by alicera** [comment]
I convert the torch to onnx ,but the onnx have the bad result .
if input the different images ,the output is the same result.
could you help me ?
