### ISSUE TITLE
rank problem

### ISSUE THREAD

**Issue by alicera** [KaiyangZhou/deep-person-reid#318]
this osnet 
![image](https://user-images.githubusercontent.com/59388989/77499535-54c71a00-6e8d-11ea-8aae-ae47363bb6f7.png)

this alignedreid
![image](https://user-images.githubusercontent.com/59388989/77499673-b5565700-6e8d-11ea-92a5-e084a836b329.png)

compare the Market1501
osnet  : rank-1 93.6  ,  mAP 81.0
alignedreid: rank-1  89.2   ,  mAP 71.8 
the result :  osnet is better than alignedreid .

but   compare the CUHK03
osnet  : rank-1 57.1  ,  mAP 54.2
alignedreid: rank-1  88.1    
the result :  alignedreid is better than  osnet .
 
why ? 
which is better?

**Comment by KaiyangZhou** [comment]
osnet and alignreid used different settings for cuhk03
