### ISSUE TITLE
max identities, max images per identity required for training and min identities, min images per identity required for training

### ISSUE THREAD

**Issue by BabuTango** [KaiyangZhou/deep-person-reid#320]
@layumi @luzai @bagxi @luyao777 @KaiyangZhou 
whats the max and min number of identities we can give for training and whats the max and min number of images we can give per identity for training.

Is there any upper limit or lower limit which could affect training

**Comment by KaiyangZhou** [comment]
well, it's commonly acknowledged that more images (per class) typically lead to better performance and generalization
