### ISSUE TITLE
conv pro

### ISSUE THREAD

**Issue by alicera** [KaiyangZhou/deep-person-reid#321]
where is the code do the paper conv3x3 5x5 7x7 9x9?
and I don't  see the conv3x3 5x5 7x7 9x9 in the image
![image](https://user-images.githubusercontent.com/59388989/77717730-262b7980-701c-11ea-8b32-4d98cdf19bd9.png)

and the paper say the dataset without labelling  can  train? how to do in the project?

**Comment by KaiyangZhou** [comment]
I believe this code explains everything https://github.com/KaiyangZhou/deep-person-reid/blob/master/torchreid/models/osnet.py
