### ISSUE TITLE
Cannot load pretrained weights

### ISSUE THREAD

**Issue by namndtth** [KaiyangZhou/deep-person-reid#323]
Hi all,
I downloaded resnet's pretrained model from model zoo. After that, I loaded this model by using torchreid.utils.torchtools.load_pretrained_weights. It gave me this error: UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 0-1: invalid continuation byte.

I'm running on pytorch 1.4.0, torchvision 0.5.0.
Thanks any help.

**Comment by KaiyangZhou** [comment]
hmm, I think this https://github.com/KaiyangZhou/deep-person-reid/blob/master/torchreid/utils/torchtools.py#L83 already solved the problem, what's your python version? try to search in history about the "UnicodeDecodeError" issue

**Comment by namndtth** [comment]
I use python 3.7.3
To day, when i try to change line 522 in torch.load()
```
if sys.version_info >= (3, 0) and 'encoding' not in pickle_load_args.keys():
    pickle_load_args['encoding'] = 'utf-8'
```
```
if sys.version_info >= (3, 0) and 'encoding' not in pickle_load_args.keys():
    pickle_load_args['encoding'] = 'latin1'
```
It works.
Many thanks.
