### ISSUE TITLE
Would you please provide an exact example to visualize activation maps?

### ISSUE THREAD

**Issue by busdac** [KaiyangZhou/deep-person-reid#327]
Hi, I have question about this part
https://kaiyangzhou.github.io/deep-person-reid/user_guide.html#visualize-activation-maps

I set the 'root' as a path to a .jpg file. Then I got this error:
TypeError: expected str, bytes or os.PathLike object, not tuple

Would you please provide an exact example to visualize activation maps? Like what you did in your computer?

**Comment by KaiyangZhou** [comment]
`root` refers to the path to the dataset (in the example, market1501)

if you wanna do a single image, you will have to modify the code

**Comment by busdac** [comment]
Thanks a lot! Now the program goes on.
However I met the next problem when I run the visualize_actmap.py:



** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']
Traceback (most recent call last):

  File "E:\DL\deep-person-reid\tools\visualize_actmap.py", line 174, in <module>
    main()

  File "E:\DL\deep-person-reid\tools\visualize_actmap.py", line 164, in main
    model = model.cuda()

  File "D:\ProgramData\Anaconda3\envs\matplotlib_build\lib\site-packages\torch\nn\modules\module.py", line 304, in cuda
    return self._apply(lambda t: t.cuda(device))

  File "D:\ProgramData\Anaconda3\envs\matplotlib_build\lib\site-packages\torch\nn\modules\module.py", line 201, in _apply
    module._apply(fn)

  File "D:\ProgramData\Anaconda3\envs\matplotlib_build\lib\site-packages\torch\nn\modules\module.py", line 201, in _apply
    module._apply(fn)

  File "D:\ProgramData\Anaconda3\envs\matplotlib_build\lib\site-packages\torch\nn\modules\module.py", line 223, in _apply
    param_applied = fn(param)

  File "D:\ProgramData\Anaconda3\envs\matplotlib_build\lib\site-packages\torch\nn\modules\module.py", line 304, in <lambda>
    return self._apply(lambda t: t.cuda(device))

  File "D:\ProgramData\Anaconda3\envs\matplotlib_build\lib\site-packages\torch\cuda\__init__.py", line 197, in _lazy_init
    torch._C._cuda_init()

RuntimeError: generic_type: cannot initialize type "_CudaDeviceProperties": an object with that name is already defined




I have win10, Anaconda and python3.7.7  . Any idea what is happening?

**Comment by busdac** [comment]
> Thanks a lot! Now the program goes on.
> However I met the next problem when I run the visualize_actmap.py:
> 
> ** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']
> Traceback (most recent call last):
> 
> File "E:\DL\deep-person-reid\tools\visualize_actmap.py", line 174, in
> main()
> 
> File "E:\DL\deep-person-reid\tools\visualize_actmap.py", line 164, in main
> model = model.cuda()
> 
> File "D:\ProgramData\Anaconda3\envs\matplotlib_build\lib\site-packages\torch\nn\modules\module.py", line 304, in cuda
> return self._apply(lambda t: t.cuda(device))
> 
> File "D:\ProgramData\Anaconda3\envs\matplotlib_build\lib\site-packages\torch\nn\modules\module.py", line 201, in _apply
> module._apply(fn)
> 
> File "D:\ProgramData\Anaconda3\envs\matplotlib_build\lib\site-packages\torch\nn\modules\module.py", line 201, in _apply
> module._apply(fn)
> 
> File "D:\ProgramData\Anaconda3\envs\matplotlib_build\lib\site-packages\torch\nn\modules\module.py", line 223, in _apply
> param_applied = fn(param)
> 
> File "D:\ProgramData\Anaconda3\envs\matplotlib_build\lib\site-packages\torch\nn\modules\module.py", line 304, in
> return self._apply(lambda t: t.cuda(device))
> 
> File "D:\ProgramData\Anaconda3\envs\matplotlib_build\lib\site-packages\torch\cuda__init__.py", line 197, in _lazy_init
> torch._C._cuda_init()
> 
> RuntimeError: generic_type: cannot initialize type "_CudaDeviceProperties": an object with that name is already defined
> 
> I have win10, Anaconda and python3.7.7 . Any idea what is happening?

Solved! I've just restarted the Anaconda and  got the activation maps.
