### ISSUE TITLE
last step of installation causes error

### ISSUE THREAD

**Issue by berkdenizi** [KaiyangZhou/deep-person-reid#328]
After i wrote "python setup.py develop" on prompt 

copying build\lib.win-amd64-3.7\torchreid\metrics\rank_cylib\rank_cy.cp37-win_amd64.pyd -> torchreid\metrics\rank_cylib
error: could not delete 'torchreid\metrics\rank_cylib\rank_cy.cp37-win_amd64.pyd': Access is denied

that error appears, what should I do .

**Comment by KaiyangZhou** [comment]
are you using the windows system? if so, this might help https://github.com/KaiyangZhou/deep-person-reid/issues/160

**Comment by berkdenizi** [comment]
after i  re install like 4th times. its fixed . thanks

**Comment by alexbarnadas** [comment]
> after i re install like 4th times. its fixed . thanks

Could you share the version or any detail? I'm having the same issue.
