### ISSUE TITLE
Where are the models?

### ISSUE THREAD

**Issue by karas84** [KaiyangZhou/deep-person-reid#33]
Hi, I noticed that all the models on the main page are gone. Did you move them to another server? Are they available? Thank you.

**Comment by KaiyangZhou** [comment]
I removed them due to space limit on our server. I am thinking it might be better to provide training commands that can reproduce the same results.

**Comment by karas84** [comment]
I understand. Thank you for the clarification.

**Comment by ciwei123** [comment]
@karas84 Hi ,Where can I find the trained model ?Thank you very much!
