### ISSUE TITLE
Practical implementation

### ISSUE THREAD

**Issue by wbenoot** [KaiyangZhou/deep-person-reid#331]
Is it actually possible to use the pre-trained models provided to determine if 2 random pictures of a person are pictures of the same person, or is this code purely built to benchmark test different reid techniques?

**Comment by KaiyangZhou** [comment]
you can definitely try using the pretrained models (available in the model zoo), or fine-tune from them for your own purpose

**Comment by jmwill86** [comment]
I agree it would be great to have an example of usage on a practical example sometime. I'm new to the ML side of things, but I just want to get the features of a single image and compare it to another and it doesn't seem all that simple to do without building a custom dataset and dataloader from what I can see? Happy to help where I can.
