### ISSUE TITLE
loss raises, acc falls at the beginning of epoch when using RandomIdentitySampler

### ISSUE THREAD

**Issue by Yogurt2019** [KaiyangZhou/deep-person-reid#334]
When using RandomIdentitySampler, the loss falls in each epoch, but raises a lot at the beginning of next epoch, vibrates every epoch.
Xent and Htri loss curve might be like this:
![image](https://user-images.githubusercontent.com/49382659/79541939-54512600-80bd-11ea-856b-36595359b1c8.png)
When change to RandomSampler, everything is as expected.

**Comment by KaiyangZhou** [comment]
Using RandomSampler does not make sense to `htri`

this thread might be helpful https://github.com/KaiyangZhou/deep-person-reid/issues/101

**Comment by Yogurt2019** [comment]
> Using RandomSampler does not make sense to `htri`
> 
> this thread might be helpful #101

thx, but RandomIdentitySampler might not contribute to xent, it can cause xent loss decay slow in large datasets, I'm looking for solution for this, trying to use RandomSampler first until xent doesn't decay then RandomIdentitySampler.
