### ISSUE TITLE
What video datasets are currently supported

### ISSUE THREAD

**Issue by mogeko2333** [KaiyangZhou/deep-person-reid#335]
prid2011 can be supported?

**Comment by KaiyangZhou** [comment]
yes, pls check this https://kaiyangzhou.github.io/deep-person-reid/datasets.html

**Comment by mogeko2333** [comment]
Thank you for your reply！
I want to train ilidsvid video dataset，I have downloaded "train_test_splits_ilidsvid.mat" in this dataset，but I can't see "**splits.json**".Is it generated in code, or where to download it？

**Comment by KaiyangZhou** [comment]
yes, and all info can be found in the doc
