### ISSUE TITLE
How to add a new data augmentation methods

### ISSUE THREAD

**Issue by szxczyc** [KaiyangZhou/deep-person-reid#337]
hi,kaiyang:
I tried to add a class in torchreid / data / transforms.py to add a new data enhancement method (such as Rand_Augment) and it didn't work. How can I add a custom data enhancement method? thank u

**Comment by KaiyangZhou** [comment]
can you provide more info about how you did it?

**Comment by KaiyangZhou** [comment]
pls make sure you follow the other transform methods defined in the `transforms.py` file, and add the new method in `build_transforms()`, it should be straightforward

**Comment by szxczyc** [comment]
Thank you very much, I have successfully  add some new data enhancement methods

**Comment by szxczyc** [comment]
hi,kaiyang:
It's too much trouble for you,i have a new problem.Many data enhancement methods only need to simply add a class to work, but mixup and cutmix are a bit complicated, can you tell me how to add these two methods in transforms?thank u

**Comment by KaiyangZhou** [comment]
you should add these two methods in the training code before running `output = model(input)` rather than in `transforms`

for mixup, you can use this code from another project of mine https://github.com/KaiyangZhou/Dassl.pytorch/blob/master/dassl/modeling/ops/mixup.py

for cutmix, I'd suggest you follow the original implementation of cutmix (which is publicly available)

**Comment by szxczyc** [comment]
Can you tell me more about how to add methods  in the training code before running `output = model (input)`? 
I am reproducing `hacnn.py` ,Should I add the code directly in `hacnn.py`？

**Comment by KaiyangZhou** [comment]
I meant adding the mixup/cutmix code in the training loop where you do forward and backward

for mixup, you can do sth like
```python
perm = torch.randperm(x.size(0))
x2 = x[perm]
y2 = y[perm] # label should be one-hot
x_mix = x * lmda + x2 * (1 - lmda)
y_mix = y * lmda + y2 * (1 - lmda)
y_pred = model(x_mix)
loss = criterion(y_pred, y_mix)
```

follow this code for cutmix https://github.com/clovaai/CutMix-PyTorch/blob/master/train.py#L228
