### ISSUE TITLE
how can change the size of feature dim?

### ISSUE THREAD

**Issue by qianjinhao** [KaiyangZhou/deep-person-reid#339]

**Comment by KaiyangZhou** [comment]
more specific?

**Comment by qianjinhao** [comment]
> more specific?

I want to change the default 512 of osnet feature dim to 2048 to see if the performance has changed

**Comment by KaiyangZhou** [comment]
https://github.com/KaiyangZhou/deep-person-reid/blob/master/torchreid/models/osnet.py#L297

**Comment by qianjinhao** [comment]
> https://github.com/KaiyangZhou/deep-person-reid/blob/master/torchreid/models/osnet.py#L297
Thank you for your answer. I have just seen the source code try to modify like this
