### ISSUE TITLE
How to get the split of PRID2011?

### ISSUE THREAD

**Issue by pansanity666** [KaiyangZhou/deep-person-reid#347]
thanks for your work,
I cannot find where to get the split json of PRID2011,could you help me ? 
thx

**Comment by KaiyangZhou** [comment]
https://kaiyangzhou.github.io/deep-person-reid/datasets.html#prid2011-prid2011

**Comment by pansanity666** [comment]
> https://kaiyangzhou.github.io/deep-person-reid/datasets.html#prid2011-prid2011

thank you very much ！
