### ISSUE TITLE
Performance when training a model on one dataset and testing in another?

### ISSUE THREAD

**Issue by ortegaton** [KaiyangZhou/deep-person-reid#35]
Just wondering, has anyone tried? Do you think it would be useful to try it or the results will be awful?

**Comment by ortegaton** [comment]
Hi, seems like it is not possible because model last layer's size, the classifier on,  is relative to the dataset, it has a size equal to possible classes. 
I am thinking on taking out this last layer for the experiment, and classify using the previous layer, which should give a vector representing the person aspect.

**Comment by KaiyangZhou** [comment]
Hi, model's eval mode is set to ignore the classification layer. Pls refer to the model code for more details.

**Comment by gceboh** [comment]
Thanks for adding support for Cross-Domain (Dataset) Person Re-identification.
For more info, please refer to [this issue](https://github.com/KaiyangZhou/deep-person-reid/issues/42#issuecomment-410493197)
