### ISSUE TITLE
Convert onnx

### ISSUE THREAD

**Issue by mhm0902** [KaiyangZhou/deep-person-reid#350]
我尝试了好几种方法进行onnx转化，都没有成功，可否指点一下

**Comment by mhm0902** [comment]
转onnx时，报torch.rand_like这个函数没有，在symbolic_opset9.py文件中添加 def rand_like(g, self, *others): return g.op('RandomUniformLike', self)
运行程序报：frame #1: <unknown function> + 0x491670 in /usr/local/lib/python3.7/site-packages/torch/lib/libtorch_python.so

**Comment by mhm0902** [comment]
尝试修改osnet_search.py 417行 uniform = torch.rand(self.weights.size() ).cuda()，报：
Invoked with: %1565 : Tensor = onnx::RandomUniform(), scope: OSNet/NASBlock
, 'shape', 1560 defined in (%1560 : int[] = prim::ListConstruct(%1559), scope: OSNet/NASBlock
) (occurred when translating rand)

**Comment by KaiyangZhou** [comment]
https://github.com/KaiyangZhou/deep-person-reid/issues?q=onnx

https://github.com/KaiyangZhou/deep-person-reid/issues/302

**Comment by MuhammadAsadJaved** [comment]
How we can convert  [ResNet-50](https://github.com/KaiyangZhou/deep-person-reid/blob/master/docs/MODEL_ZOO.md#msmt17-combinealltrue---market1501--dukemtmc-reid) model to .onnx?
