### ISSUE TITLE
Resnet50_fc512 model

### ISSUE THREAD

**Issue by jiaweihe1996** [KaiyangZhou/deep-person-reid#353]
Hi. Why there is a ReLU layer after FC layer?  It will make all ReID features positive.

https://github.com/KaiyangZhou/deep-person-reid/blob/b075bd3f4b46ff5f35e91d8b3b97e05a73a8c3ba/torchreid/models/resnet.py#L314

**Comment by KaiyangZhou** [comment]
it's common to add a nonlinear transformation layer
