### ISSUE TITLE
eval 

### ISSUE THREAD

**Issue by sky186** [KaiyangZhou/deep-person-reid#354]
@KaiyangZhou 
您好，谢谢您的工作，这边我有个问题想不明白
我想请教下你，这个循环的问题，map测试的基本计算我了解，求ap的过程,
但是代码实现这边，这个循环我不能理解到底做是什么操作，和camid 有什么关系？

![图片](https://user-images.githubusercontent.com/56809648/87125014-5e4d8400-c2bc-11ea-9254-ea1a42db0d68.png)

**Comment by KaiyangZhou** [comment]
pls refer to the comments
