### ISSUE TITLE
Input Normalization

### ISSUE THREAD

**Issue by GeekAlexis** [KaiyangZhou/deep-person-reid#355]
Great work! 
When performing inference with pretrained models, should I normalize my image using ImageNet's mean and std? What is the numeric range expected by the model (e.g. OSNet_x0_25)? Thanks in advance!

**Comment by KaiyangZhou** [comment]
the code automatically includes `normalization` as one of the preprocessing steps where the mean and std come from imagenet

if you wanna use your own mean and std, simply change `data.norm_mean` and `data.norm_std`
