### ISSUE TITLE
Training DukeMTMC-VideoReID  dataset

### ISSUE THREAD

**Issue by abhigoku10** [KaiyangZhou/deep-person-reid#36]
@luzai @KaiyangZhou Hi first of thanks for the wonderful code representation . i have few queries when training the DukeMTMC-VideoReID  dataset 

1.When i download the dataset from the source i have only train , gallery and video folder there is no .json file. Can you share me how to generate the .json file , since it gives me error **camid = int(img_name[5]) - 1 # index-0
ValueError: invalid literal for int() with base 10: 'C'**

Can you pls help me out in solving this issues

**Comment by KaiyangZhou** [comment]
Did you follow the instruction [here](https://github.com/KaiyangZhou/deep-person-reid/blob/master/DATASETS.md) to prepare the dataset? If so, .json files can be automatically generated and everything should be set. Please check the code `data_manager/dukemtmcvidreid.py`.

**Comment by abhigoku10** [comment]
@KaiyangZhou i followed the instructions and created the similar folder structure , should i run any python file to create the .json file . I checked the code in data_manager/dukemtmcvidreid.py i changed from int to float and get the following error 
**line 138, in _process_dir
    camid = float(img_name[5]) - 1 # index-0
ValueError: could not convert string to float: 'C'**

**Comment by KaiyangZhou** [comment]
.json files are automatically generated. I could not reproduce your error. What is the format of your image name? Can you try
```
import data_manager
dataset = data_manager.init_vidreid_dataset(name='dukemtmcvidreid', root='your_root')
```
and see what happens?

**Comment by abhigoku10** [comment]
@KaiyangZhou  i solved the issue in the in the file **dukemtmcvidreid.py**   by changing the line camid = int(img_name[6]) - 1 from 6 to 5 since img_name[5] was reading a string, can you just tell me how much time does it take train on 1080ti gpu system

**Comment by KaiyangZhou** [comment]
The image is named like 0675C1F0001X169722.jpg so camid should be found at 5th place (0-based) as did in the original code. I am wondering why you would need to change from 5 to 6.

Regarding the training time, I have no idea how long it would take as it depends on the train params.

**Comment by gceboh** [comment]
The naming rule of DukeMTMC-VideoReID was updated on [6 May,2018](https://github.com/Yu-Wu/DukeMTMC-VideoReID/commit/4b24fd8464718336c26a37c8370c1b6c50147852).

Now filenames look like  `0001_C6_F0099_X30823.jpg`.

For more info,please refer to [DukeMTMC-VideoReID/Directory Structure](https://github.com/Yu-Wu/DukeMTMC-VideoReID/blob/master/README.md#directory-structure)

**Comment by KaiyangZhou** [comment]
code updated, thx
