### ISSUE TITLE
index 122 is out of bounds for dimension 1 with size 77

### ISSUE THREAD

**Issue by busdac** [KaiyangZhou/deep-person-reid#361]
Dear Kaiyang,

thank you very much for sharing your extraordinary work in person re-id!

Here I am trying to train with a set of 77 different persons. It successfully reads the dataset as follows:

**************** Summary ****************
  source            : ['ltcc']
   source datasets : 1
   source ids      : 77
   source images   : 9576
   source cameras  : 10
  target            : ['ltcc']
  *****************************************
=> Start training

 

However there comes an error like this:

  File "E:\DL\deep-person-reid\torchreid\engine\engine.py", line 128, in run
    open_layers=open_layers

  File "E:\DL\deep-person-reid\torchreid\engine\image\triplet.py", line 131, in train
    loss_x = self._compute_loss(self.criterion_x, outputs, pids)

  File "E:\DL\deep-person-reid\torchreid\engine\engine.py", line 329, in _compute_loss
    loss = criterion(outputs, targets)

  File "D:\ProgramData\Anaconda3\envs\yoloreid\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)

  File "E:\DL\deep-person-reid\torchreid\losses\cross_entropy_loss.py", line 48, in forward
    targets = zeros.scatter_(1, targets.unsqueeze(1).data.cpu(), 1)

RuntimeError: index 122 is out of bounds for dimension 1 with size 77

I print out the "targets" in cross_entropy_loss.py, it shows like this:

tensor([ 27,  27,  27,  27,  89,  89,  89,  89, 138, 138, 138, 138,  70,  70,
         70,  70,  85,  85,  85,  85, 146, 146, 146, 146, 133, 133, 133, 133,
        117, 117, 117, 117], device='cuda:0')
What does it mean?

Would you mind to give me some advice, where could be the problem?

Thanks a lot!

**Comment by KaiyangZhou** [comment]
so there are 77 IDs, which means the label should be from 0 to 76

but the label you passed to the network has value larger than 76, I guess you did not properly relabel the dataset

make sure you follow this instruction https://kaiyangzhou.github.io/deep-person-reid/user_guide.html#use-your-own-dataset

**Comment by busdac** [comment]
Yes! I have already relabel the dataset as it in your market1501.py. Now it works!

Thank you very much!

**Comment by malpeddinilesh** [comment]
Hi @busdac , 

How do you solve this index out of bounds for dimension? I am getting the same error. 

Something like this:

RuntimeError: index 5015 is out of bounds for dimension 1 with size 31

I just printed following tensor: 
targets: tensor([5015, 5009], device='cuda:0')

It will be helpful if you provide some info on this on how to solve this. 

Do we need to start pid and camid always from 0? I have pid starting from 5001.

**Comment by busdac** [comment]
Hello @malpeddinilesh !
Sorry I haven't touch reID for a while. But I am not sure whether we got the same problem. Do you actually have 5015 IDs? I just remember that I relabeled the IDs and make sure that the index is within the bounds.
