### ISSUE TITLE
your dependency tb-nightly  breaks tensorboard

### ISSUE THREAD

**Issue by jpainam** [KaiyangZhou/deep-person-reid#363]
Hi, i was using tensorboard with pytorch without any problem.
While install your code, it asked for tb-nightly which I also installed. Unfortunately, following this issue [https://github.com/pytorch/pytorch/issues/22676#issuecomment-515662805](https://github.com/pytorch/pytorch/issues/22676#issuecomment-515662805) it breaks tensorboard. and someone has to rebuild the environement or reinstall tensorflow-gpu again.
Please confirm that it work fine with tb-nightly

Is there a way to not use tb-nightly?
Thanks

**Comment by KaiyangZhou** [comment]
you can use conda to manage the env so you don't need to uninstall other packages
