### ISSUE TITLE
visrank returns ValueError: too many values to unpack (expected 3)

### ISSUE THREAD

**Issue by nudro** [KaiyangZhou/deep-person-reid#364]
Followed demo instructions without modification. `engine.run()` with `test_only = True` and `vis_rank = True` leads to python value error.

    datamanager = torchreid.data.ImageDataManager(
        root='reid-data',
        sources='market1501',
        targets='market1501',
         height=256,
        width=128,
        batch_size_train=32,
        batch_size_test=100,
        transforms=['random_flip', 'random_crop']
    )

    model = torchreid.models.build_model(
        name='resnet50',
       num_classes=datamanager.num_train_pids,
       loss='softmax',
       pretrained=True
    )

    model = model.cuda()

    optimizer = torchreid.optim.build_optimizer(
        model,
        optim='adam',
        lr=0.0003
    )

    scheduler = torchreid.optim.build_lr_scheduler(
        optimizer,
        lr_scheduler='single_step',
        stepsize=20
    )

    engine = torchreid.engine.ImageSoftmaxEngine(
       datamanager,
       model,
       optimizer=optimizer,
       scheduler=scheduler,
       label_smooth=True
    )

    # Trained 5 epochs for brevity/demo

    engine.run(
        save_dir='log/resnet50',
        max_epoch=5,
        eval_freq=10,
        print_freq=10,
        test_only=False
    )

   # Completes successfully 

    => Final test
    ##### Evaluating market1501 (source) #####
    Extracting features from query set ...
    Done, obtained 3368-by-2048 matrix
    Extracting features from gallery set ...
    Done, obtained 15913-by-2048 matrix
    Speed: 0.0068 sec/batch
    Computing distance matrix with metric=euclidean ...
    Computing CMC and mAP ...
    ** Results **
    mAP: 56.4%
    CMC curve
    Rank-1  : 75.3%
    Rank-5  : 89.3%
    Rank-10 : 92.9%
    Rank-20 : 95.3%
    Checkpoint saved to "log/resnet50/model/model.pth.tar-5"
    Elapsed 0:05:52

# test returns error

    engine.run(
        save_dir='log/resnet50',
        max_epoch=5,
        eval_freq=10,
        print_freq=10,
        test_only=True,
        visrank_topk=5,
        visrank=True,
    )

    ##### Evaluating market1501 (source) #####
    Extracting features from query set ...
    Done, obtained 3368-by-2048 matrix
    Extracting features from gallery set ...
    Done, obtained 15913-by-2048 matrix
    Speed: 0.0069 sec/batch
    Computing distance matrix with metric=euclidean ...
    Computing CMC and mAP ...
    ** Results **
    mAP: 56.4%
    CMC curve
    Rank-1  : 75.3%
    Rank-5  : 89.3%
    Rank-10 : 92.9%
    Rank-20 : 95.3%
    # query: 3368
    # gallery 15913
    Visualizing top-5 ranks ...

# Traceback:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-13-9a0e97a284b2> in <module>
      6     test_only=True,
      7     visrank_topk=5,
----> 8     visrank=True,
      9 )

~/deep-person-reid/torchreid/engine/engine.py in run(self, save_dir, max_epoch, start_epoch, print_freq, fixbase_epoch, open_layers, start_eval, eval_freq, test_only, dist_metric, normalize_feature, visrank, visrank_topk, use_metric_cuhk03, ranks, rerank)
    175                 use_metric_cuhk03=use_metric_cuhk03,
    176                 ranks=ranks,
--> 177                 rerank=rerank
    178             )
    179             return

~/deep-person-reid/torchreid/engine/engine.py in test(self, dist_metric, normalize_feature, visrank, visrank_topk, save_dir, use_metric_cuhk03, ranks, rerank)
    333                 use_metric_cuhk03=use_metric_cuhk03,
    334                 ranks=ranks,
--> 335                 rerank=rerank
    336             )
    337 

~/anaconda3/envs/gans/lib/python3.7/site-packages/torch/autograd/grad_mode.py in decorate_context(*args, **kwargs)
     13         def decorate_context(*args, **kwargs):
     14             with self:
---> 15                 return func(*args, **kwargs)
     16         return decorate_context
     17 

~/deep-person-reid/torchreid/engine/engine.py in _evaluate(self, dataset_name, query_loader, gallery_loader, dist_metric, normalize_feature, visrank, visrank_topk, save_dir, use_metric_cuhk03, ranks, rerank)
    428                 height=self.datamanager.height,
    429                 save_dir=osp.join(save_dir, 'visrank_' + dataset_name),
--> 430                 topk=visrank_topk
    431             )
    432 

~/deep-person-reid/torchreid/utils/reidtools.py in visualize_ranked_results(distmat, dataset, data_type, width, height, save_dir, topk)
     77 
     78     for q_idx in range(num_q):
---> 79         qimg_path, qpid, qcamid = query[q_idx]
     80         qimg_path_name = qimg_path[0] if isinstance(
     81             qimg_path, (tuple, list)

**ValueError: too many values to unpack (expected 3)**

**Comment by KaiyangZhou** [comment]
thanks for reporting this error

it was caused by not unpacking `dsetid` in `query[i]`

so previously a data list contains tuples of `(impath, pid, camid)`, which has recently been updated to `(impath, pid, camid, dsetid)` to take into account the dataset index (for the purpose of multi-dataset training)

error fixed now in v1.3.3

**Comment by nudro** [comment]
thanks
