### ISSUE TITLE
Return filenames of visrank results

### ISSUE THREAD

**Issue by nudro** [KaiyangZhou/deep-person-reid#366]
Thanks for a highly documented library. 

What functionality exists in the repo to return filenames of the visrank results?  For example, in [https://kaiyangzhou.github.io/deep-person-reid/_images/ranking_results.jpg](url), returning and sorting filenames by match (green) and no match (red).

**Comment by KaiyangZhou** [comment]
you have to modify the source code, e.g. saving the file names in a text file
