### ISSUE TITLE
Training for DukeMTMC-VideoReID

### ISSUE THREAD

**Issue by abhigoku10** [KaiyangZhou/deep-person-reid#37]
@luzai @KaiyangZhou Hi i have taken the default DukeMTMC-VideoReID dataset and training it but in the end where is the model getting saved? should i create a director called save-model and pass it as a arguement ? can you pls share the command / process to view the saved model file

**Comment by Yu-Wu** [comment]
@abhigoku10 
Hi, By default, the model is saved to './log/'. You may change the saving dir by pass it as the argument "save-dir".

By the way, you'd better update the code to fix some error as reported in #36 , since the naming rule of DukeMTMC-VideoReID was updated.
