### ISSUE TITLE
 I change the config loss to triplet loss,but it occurs a error

### ISSUE THREAD

**Issue by zhangting1994** [KaiyangZhou/deep-person-reid#373]
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']
Model complexity: params=2,193,616 flops=978,878,352
Building triplet-engine for image-reid
=> Start training
* Only train ['classifier'] (epoch: 1/10)
Traceback (most recent call last):
  File "scripts/main.py", line 184, in <module>
    main()
  File "scripts/main.py", line 180, in main
    engine.run(**engine_run_kwargs(cfg))
  File "/home/deeplearn/cloud/zhangting/contestAI/deep-person-reid/torchreid/engine/engine.py", line 193, in run
    open_layers=open_layers
  File "/home/deeplearn/cloud/zhangting/contestAI/deep-person-reid/torchreid/engine/engine.py", line 245, in train
    loss_summary = self.forward_backward(data)
  File "/home/deeplearn/cloud/zhangting/contestAI/deep-person-reid/torchreid/engine/image/triplet.py", line 119, in forward_backward
    loss.backward()
  File "/opt/conda/lib/python3.7/site-packages/torch/tensor.py", line 118, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

**Comment by KaiyangZhou** [comment]
can you provide the full command to reproduce your error? also the detailed config

**Comment by zhangting1994** [comment]
the full command is following:
python scripts/main.py \
--config-file configs/im_osnet_x1_0_softmax_256x128_amsgrad.yaml \
-s selfdata \
-t selfdata \
--transforms random_flip random_erase \
--root ../A/train \
data.save_dir log/osnet_x1_0_selfdata_softmax_euclideanlr

the config is following:
model:
  name: 'osnet_x1_0'
  pretrained: True

data:
  type: 'image'
  sources: ['market1501']
  targets: ['market1501']
  height: 256
  width: 128
  combineall: False
  transforms: ['random_flip']
  save_dir: 'log/osnet_x1_0_market1501_softmax'

loss:
  name: 'triplet'
  #['softmax', 'triplet']
  softmax:
    label_smooth: True

train:
  optim: 'amsgrad'
  #['adam', 'amsgrad', 'sgd', 'rmsprop', 'radam']
  lr: 0.0015
  max_epoch: 150
  batch_size: 64
  fixbase_epoch: 10
  open_layers: ['classifier']
  lr_scheduler: 'single_step'
  stepsize: [60]

test:
  batch_size: 300
  dist_metric: 'euclidean'
  normalize_feature: False
  evaluate: False
  eval_freq: -1
  rerank: False

**Comment by KaiyangZhou** [comment]
when using `triplet`, you have to set `fixbase_epoch ` to 0 as the classifier's output is unused

https://github.com/KaiyangZhou/deep-person-reid/blob/master/torchreid/engine/image/triplet.py#L110

**Comment by KaiyangZhou** [comment]
I've added `check_cfg()` in `main.py` to filter out some error-prone settings

please pull the latest code
