### ISSUE TITLE
how to extract the feature ?

### ISSUE THREAD

**Issue by szh91** [KaiyangZhou/deep-person-reid#378]
I want to extract the feature of my image by your  instructions, but it's fail to extract it.  I have downloaded  the pretrain model .
the error as follow:
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1LaG1EJpHrxdAxKnSCJ_i0u-nbxSAeiFY (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff0bb6b6610>: Failed to establish a new connection: [Errno 110] Connection timed out'))

**Comment by KaiyangZhou** [comment]
can you describe in more detail how you get this error? like which script you are using, what command, etc.

btw, this error looks like an internet problem

**Comment by szh91** [comment]
I write a python script named-feature_extract.py and write the code as follow. the image I have uploaded
but it represents the error "requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1LaG1EJpHrxdAxKnSCJ_i0u-nbxSAeiFY (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f493008b090>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
python-BaseException"




from torchreid.utils import FeatureExtractor

extractor = FeatureExtractor(
    model_name='osnet_x1_0',
    #model_path='a/b/c/model.pth.tar',
    model_path='./model_pth/osnet_x1_0_imagenet.pth',
    device='cuda'
)

image_list = [
    './img/1.jpg',
    './img/2.jpg',
    './img/3.jpg'
]

features = extractor(image_list)
print(features.shape) # output

**Comment by KaiyangZhou** [comment]
when instantiating the `extractor`, the code will automatically download the imagenet weights for `osnet_x1_0`, which will cause an internet problem if you are in China (the notorious great firewall)
