### ISSUE TITLE
How can i use your library in my project ?

### ISSUE THREAD

**Issue by borre47** [KaiyangZhou/deep-person-reid#379]
Hi, excellent work. I am working on a object tracking application for persons. Until now, I have used yolov4 to get detections and deepsort to track, but now I want to use multi-cameras and I know that I need re-id to match the detection on a camera with the detections of another camera. How can I use your library in my project?

**Comment by KaiyangZhou** [comment]
I only answer questions regarding bugs or issues of code, sorry
