### ISSUE TITLE
Incremental training 

### ISSUE THREAD

**Issue by abhigoku10** [KaiyangZhou/deep-person-reid#38]
@luzai @KaiyangZhou Hi what is the command to perform incremental training , lets assume i trained my net for 20 epochs and got the weights now i want to train it for another 30 epochs but i have to start from 20th epoch , how can we do it ?

**Comment by KaiyangZhou** [comment]
https://github.com/KaiyangZhou/deep-person-reid/blob/master/train_imgreid_xent.py#L87
