### ISSUE TITLE
提示预训练模型下载不了，怎么解决

### ISSUE THREAD

**Issue by ww5171351** [KaiyangZhou/deep-person-reid#388]
您好，学校网络原因，这个预训练下载不了，有什么其他链接么，说明书上面的那个model zoo链接也打不开。
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /uc?id=1LaG1EJpHrxdAxKnSCJ_i0u-nbxSAeiFY (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001FC76D8F8C8>: Failed to est
ablish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。'))
有什么国内的连接嘛，下载。万分感谢

**Comment by ww5171351** [comment]
找国外的同学，将ImageNet pretrained models下载后，pretrained: False，cfg.model.load_weights = 'ImageNet pretrained models' ，运行后依旧提示让下载预训练权重

**Comment by GesilaA** [comment]
把权重放到~/.cache/torch/checkpoints下就可以了
