### ISSUE TITLE
Custom data augmentation functions

### ISSUE THREAD

**Issue by tampe125** [KaiyangZhou/deep-person-reid#392]
Hello,  

I'd wish to use some data augmentation, like `RandomRotation`, but looking at the code such method is not added to the allowed list.
Moreover, what if I'd wish to add some custom technique? Is there a way to play nicely with the framework or the only way is to manually edit your source code?

**Comment by KaiyangZhou** [comment]
unfortunately, the only way is to manually modify https://github.com/KaiyangZhou/deep-person-reid/blob/master/torchreid/data/transforms.py

**Comment by tampe125** [comment]
Ok, thanks, good to know.
