### ISSUE TITLE
visualize actmap for se_resnet50

### ISSUE THREAD

**Issue by huangzhao1** [KaiyangZhou/deep-person-reid#393]
TypeError: forward() got unexpected keyword argument "return_featuremaps". Please add return_featuremaps as an input argument to forward(). When return_featuremaps=True, return feature maps only.

how should I fix my code to ouput the actmap for se_resnet50?

**Comment by KaiyangZhou** [comment]
you can follow this https://github.com/KaiyangZhou/deep-person-reid/blob/master/torchreid/models/osnet.py#L422 to modify the code of se_resnet50
