### ISSUE TITLE
ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'

### ISSUE THREAD

**Issue by kazuki-can** [KaiyangZhou/deep-person-reid#396]
Hi there. I am new to torchreid. I want to train this on maker-1501.
But I got an error saying 'ValueError: Buffer dtype mismatch, expected 'long' but got 'long long''.
I made a new file called 'train.py' in the same diretory as 'main.py' and I ran this command 'python scripts/train.py'.
It can be trained but when it computes CMC and mAP, this happended.

**Comment by youjinqing123** [comment]
I find another way to solve this problem, find torchreid\metrics\rank.py and set use_cython=False in function evaluate_rank, which helps me print out evaluation result successfully, but i am not sure wheather it could have any influence on other process, if any one know please tell me.
