### ISSUE TITLE
Trouble with training OSNet on Market1501 using conventional setting

### ISSUE THREAD

**Issue by robweld** [KaiyangZhou/deep-person-reid#414]
Hello, I have just finished the installation of torchreid and continued following your instructions to try out the example. I ran this code that you say to use and get the following errors.

(torchreid) C:\Users\Rob\Desktop\deep-person-reid-master>python scripts/main.py \--config-file configs/im_osnet_x1_0_softmax_256x128_amsgrad_cosine.yaml \--transforms random_flip random_erase \--root=C:\Users\Rob\Desktop\deep-person-reid-master\torchreid\data
Traceback (most recent call last):
  File "scripts/main.py", line 191, in <module>
    main()
  File "scripts/main.py", line 137, in main
    cfg.merge_from_list(args.opts)
  File "C:\Users\Rob\anaconda3\envs\torchreid\lib\site-packages\yacs\config.py", line 243, in merge_from_list
    _assert_with_logging(subkey in d, "Non-existent key: {}".format(full_key))
  File "C:\Users\Rob\anaconda3\envs\torchreid\lib\site-packages\yacs\config.py", line 545, in _assert_with_logging
    assert cond, msg
AssertionError: Non-existent key: \--config-file

Thank you for providing this software. Any help is much appreciated!

**Comment by KaiyangZhou** [comment]
The running command is correct. I guess the error might be caused by some spacing issue?

**Comment by robweld** [comment]
Hi thanks for the quick response. Yeah that must have been the problem after retyping the --config-file part it worked.
