### ISSUE TITLE
Using our own dataset for testing

### ISSUE THREAD

**Issue by xertxiao** [KaiyangZhou/deep-person-reid#42]
Is there a way to prepare our own dataset and test the models on it? Thanks

**Comment by KaiyangZhou** [comment]
Yes, you could follow .py files in dataset_manager/ and write your own dataset classes.

**Comment by xertxiao** [comment]
Thanks!

**Comment by xertxiao** [comment]
Hi, I was trying to use a pre-trained market1501 model on my own dataset but failed. The error messages says that this pre-trained model expect a "torch.Size([751])" (I suspect this 751 is the total ids of people in market) but my dataset has "torch.Size([16])", where 16 is total ids of my dataset. Is there anything I can do to resolve this? Thanks again.

**Comment by KaiyangZhou** [comment]
use `--load-weights`.

**Comment by xertxiao** [comment]
Thanks for helping!
