### ISSUE TITLE
Custom Dataset - RuntimeError: index 214 is out of bounds for dimension 1 with size 214

### ISSUE THREAD

**Issue by szhitansky** [KaiyangZhou/deep-person-reid#420]
I have custom dataset, as target it works ok, but when I try to use it for training I have an error:

**RuntimeError: index 214 is out of bounds for dimension 1 with size 214**

Any suggestions whats wrong ?

=> Loading test (target) dataset
=> Loaded MyDataset
  ----------------------------------------
  subset   | # ids | # images | # cameras
  ----------------------------------------
  train    |   214 |    10888 |        45
  query    |     3 |       39 |        11
  gallery  |     3 |       79 |        27
  ----------------------------------------

RuntimeError                              Traceback (most recent call last)
<ipython-input-16-b122413cccb0> in <module>
      4     eval_freq=1,
      5     print_freq=500,
----> 6     test_only=False
      7 )

/Deep Re-ID/deep-person-reid/torchreid/engine/engine.py in run(self, save_dir, max_epoch, start_epoch, print_freq, fixbase_epoch, open_layers, start_eval, eval_freq, test_only, dist_metric, normalize_feature, visrank, visrank_topk, use_metric_cuhk03, ranks, rerank)
    191                 print_freq=print_freq,
    192                 fixbase_epoch=fixbase_epoch,
--> 193                 open_layers=open_layers
    194             )
    195 

/Deep Re-ID/deep-person-reid/torchreid/engine/engine.py in train(self, print_freq, fixbase_epoch, open_layers)
    243         for self.batch_idx, data in enumerate(self.train_loader):
    244             data_time.update(time.time() - end)
--> 245             loss_summary = self.forward_backward(data)
    246             batch_time.update(time.time() - end)
    247             losses.update(loss_summary)

/Deep Re-ID/deep-person-reid/torchreid/engine/image/softmax.py in forward_backward(self, data)
     84 
     85         outputs = self.model(imgs)
---> 86         loss = self.compute_loss(self.criterion, outputs, pids)
     87 
     88         self.optimizer.zero_grad()

/Deep Re-ID/deep-person-reid/torchreid/engine/engine.py in compute_loss(self, criterion, outputs, targets)
    437             loss = DeepSupervision(criterion, outputs, targets)
    438         else:
--> 439             loss = criterion(outputs, targets)
    440         return loss
    441 

~/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

/Deep Re-ID/deep-person-reid/torchreid/losses/cross_entropy_loss.py in forward(self, inputs, targets)
     44         log_probs = self.logsoftmax(inputs)
     45         zeros = torch.zeros(log_probs.size())
---> 46         targets = zeros.scatter_(1, targets.unsqueeze(1).data.cpu(), 1)
     47         if self.use_gpu:
     48             targets = targets.cuda()

RuntimeError: index 214 is out of bounds for dimension 1 with size 214

**Comment by szhitansky** [comment]
Resolved, it was raw dataset, additional prefiltering and re-indexing fixed issue.

**Comment by wrannaman** [comment]
Hey @szhitansky I'm running into this as well. What do you mean profiteering and re-indexing? Thanks in advance for your time.

**Comment by szhitansky** [comment]
> Hey @szhitansky I'm running into this as well. What do you mean prefiltering and re-indexing? Thanks in advance for your time.

I found few damaged and empty images. And after that I did dataset creation.
