### ISSUE TITLE
Pre-trained model training issue

### ISSUE THREAD

**Issue by malpeddinilesh** [KaiyangZhou/deep-person-reid#423]
Hi @KaiyangZhou,

I am getting following issue while performing model training. 

engine.run(
    save_dir='log/osnet_ain_transfer',
    max_epoch=60,
    eval_freq=10,
    print_freq=10,
    test_only=False,
    fixbase_epoch=5,
    open_layers='classifier'
)

=> Start training
* Only train classifier (epoch: 1/5)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-21-db919c647e64> in <module>
      6     test_only=False,
      7     fixbase_epoch=5,
----> 8     open_layers='classifier'
      9 )
     10 # or open_layers=['fc', 'classifier'] if there is another fc layer that

~/person_reid_new/deep-person-reid/torchreid/engine/engine.py in run(self, save_dir, max_epoch, start_epoch, print_freq, fixbase_epoch, open_layers, start_eval, eval_freq, test_only, dist_metric, normalize_feature, visrank, visrank_topk, use_metric_cuhk03, ranks, rerank)
    191                 print_freq=print_freq,
    192                 fixbase_epoch=fixbase_epoch,
--> 193                 open_layers=open_layers
    194             )
    195 

~/person_reid_new/deep-person-reid/torchreid/engine/engine.py in train(self, print_freq, fixbase_epoch, open_layers)
    243         for self.batch_idx, data in enumerate(self.train_loader):
    244             data_time.update(time.time() - end)
--> 245             loss_summary = self.forward_backward(data)
    246             batch_time.update(time.time() - end)
    247             losses.update(loss_summary)

~/person_reid_new/deep-person-reid/torchreid/engine/image/softmax.py in forward_backward(self, data)
     84 
     85         outputs = self.model(imgs)
---> 86         loss = self.compute_loss(self.criterion, outputs, pids)
     87 
     88         self.optimizer.zero_grad()

~/person_reid_new/deep-person-reid/torchreid/engine/engine.py in compute_loss(self, criterion, outputs, targets)
    437             loss = DeepSupervision(criterion, outputs, targets)
    438         else:
--> 439             loss = criterion(outputs, targets)
    440         return loss
    441 

~/anaconda3/envs/newmmpose/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

~/person_reid_new/deep-person-reid/torchreid/losses/cross_entropy_loss.py in forward(self, inputs, targets)
     44         log_probs = self.logsoftmax(inputs)
     45         zeros = torch.zeros(log_probs.size())
---> 46         targets = zeros.scatter_(1, targets.unsqueeze(1).data.cpu(), 1)
     47         if self.use_gpu:
     48             targets = targets.cuda()

RuntimeError: index 5019 is out of bounds for dimension 1 with size 30

**Comment by KaiyangZhou** [comment]
Seems like the error is caused by mismatch between the number of classes in the dataset and that in the classification layer?

**Comment by malpeddinilesh** [comment]
Hi @KaiyangZhou ,

After loading pre-trained model of OSNet-AIN trained on MSMT17, where should I change number of classes in the classification layer? 

In DataManager I have number of classes as 30. 

model = torchreid.models.build_model(
    name='osnet_ain_x1_0',
    num_classes=datamanager.num_train_pids,
    loss='softmax',
    pretrained=True
)

I passing num_classes when building model, still seeing the same issue.

**Comment by KaiyangZhou** [comment]
You need to identify what caused the problem of out-of-bound index

please check https://github.com/KaiyangZhou/deep-person-reid/issues?q=index+out+of+bounds which might be helpful

**Comment by malpeddinilesh** [comment]
Hi @KaiyangZhou  , 

Based on the instruction provided in the document.

Do I need to start pid and camid always from 0? I have pid starting from 5001. Is that the cause for this issue?

**Comment by malpeddinilesh** [comment]
Thank you @KaiyangZhou ! Issue resolved and closing.
