### ISSUE TITLE
Periodically saving checkpoints while training

### ISSUE THREAD

**Issue by arsenal-2004** [KaiyangZhou/deep-person-reid#425]
Hello,

I am using the Main script to train OSNet on a custom dataset. However, I am not sure how to periodically save the checkpoint using the inbuilt engine. Could you suggest a way for this?

**Comment by KaiyangZhou** [comment]
https://github.com/KaiyangZhou/deep-person-reid/blob/master/scripts/default_config.py#L103

https://github.com/KaiyangZhou/deep-person-reid/blob/master/torchreid/engine/engine.py#L209

**Comment by arsenal-2004** [comment]
Thank you so much :)
