### ISSUE TITLE
Train Custom Model

### ISSUE THREAD

**Issue by sramakrishnan247** [KaiyangZhou/deep-person-reid#429]
@KaiyangZhou 
Hey, excellent work. 
I want to use custom model or fine-tune existing models. 
I looked at the issues and wiki but could not find the process to add new CNN/model and run the code.
Please let me know if you can give some more info or point me to the right place.
Thanks!

**Comment by KaiyangZhou** [comment]
you need to register your model here https://github.com/KaiyangZhou/deep-person-reid/blob/master/torchreid/models/__init__.py
