### ISSUE TITLE
mudeep.py does not support Triplet Loss

### ISSUE THREAD

**Issue by sramakrishnan247** [KaiyangZhou/deep-person-reid#431]
In the test phase with loss="triplet"
mudeep.py returns a tuple y,x whereas engine.py features expects a pytorch tensor. 
As a result, 
`features = features.cpu().clone()`
fails in engine.py line 370

Proposed Fix: https://github.com/KaiyangZhou/deep-person-reid/pull/430

**Comment by KaiyangZhou** [comment]
thanks

PR merged now
