### ISSUE TITLE
HACNN model download link is unavailable

### ISSUE THREAD

**Issue by hsuRush** [KaiyangZhou/deep-person-reid#44]
HACNN [download link](http://eecs.qmul.ac.uk/~kz303/deep-person-reid/model-zoo/image-models/hacnn_xent_market.pth.tar) is unavailable in [benchmark](https://github.com/KaiyangZhou/deep-person-reid/blob/master/BENCHMARK.md) page.

**Comment by LiuTaw** [comment]
I found the same question.

**Comment by KaiyangZhou** [comment]
fixed now
