### ISSUE TITLE
What is train, query and gallery?

### ISSUE THREAD

**Issue by danishansari** [KaiyangZhou/deep-person-reid#442]
What is train, query and gallery? are these positive, negative and anchor images? or is it train, test, eval sets of images?

I read the paper as well as documentation but could not figure out what is the content and purpose of each directory.
        # All you need to do here is to generate three lists,
        # which are train, query and gallery.
        # Each list contains tuples of (img_path, pid, camid),

All it says is create three folder, but what is the purpose of each?
I could understand pid is person's id, which will be unique to each person.
camid is camera id, probably to guess the same pose of person.
Still don't know how they are related and make difference?

**Comment by sainivedh** [comment]
Train is for training the model.
query and gallery used for testing, where for each image in query you find similar persons in gallery set

**Comment by danishansari** [comment]
Thanks @sainivedh for your clarification, I understood this eventually. And so I had a set of 10 person(pids), of which a I put 8 in training set and 2 in test(20 images from each in query and remaining in gallery), I want train and test to be exclusive. Thus my dataset looks like below:
Train: [2, 3, 3, 4, 5, 6, 7, 8, 9] (pids)
gallery: [0, 1] (pids)
query: [0, 1] (pids)
I have more than 1000 instance of same pids of which I put 20 samples of each pid in query, so its look like below:
gallery: [980, 980], files for pids 0 and 1
query:  [20, 20]       files for pids 0 and 1. But I am getting "AssertionError: Error: all query identities do not appear in gallery".
Any idea what could be wrong?

`Traceback (most recent call last):
  File "train_team_re_id.py", line 55, in <module>
    use_metric_cuhk03 = False,
  File "/home/danish/TeamidEmbeddings/deep-person-reid/torchreid/engine/engine.py", line 220, in run
    ranks=ranks
  File "/home/danish/TeamidEmbeddings/deep-person-reid/torchreid/engine/engine.py", line 335, in test
    rerank=rerank
  File "/home/danish/miniconda3/envs/torchreid/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/danish/TeamidEmbeddings/deep-person-reid/torchreid/engine/engine.py", line 413, in _evaluate
    use_metric_cuhk03=use_metric_cuhk03
  File "/home/danish/TeamidEmbeddings/deep-person-reid/torchreid/metrics/rank.py", line 206, in evaluate_rank
    use_metric_cuhk03
  File "/home/danish/TeamidEmbeddings/deep-person-reid/torchreid/metrics/rank.py", line 165, in evaluate_py
    distmat, q_pids, g_pids, q_camids, g_camids, max_rank
  File "/home/danish/TeamidEmbeddings/deep-person-reid/torchreid/metrics/rank.py", line 146, in eval_market1501
    assert num_valid_q > 0, 'Error: all query identities do not appear in gallery'
AssertionError: Error: all query identities do not appear in gallery
`

**Comment by staeff777** [comment]
I run into the same error. The evaluation expects different cam ids in the gallery results than that one used in the query. My workaround for single cam use is to set all query cam IDs to 0 and all gallery IDs to 1.

**Comment by danishansari** [comment]
@staeff777 thanks a lot, it did worked :)

**Comment by harshap-ai** [comment]
> I run into the same error. The evaluation expects different cam ids in the gallery results than that one used in the query. My workaround for single cam use is to set all query cam IDs to 0 and all gallery IDs to 1.

Thank you for clarifying this. Quick question: Did you also set a different camid for train, say 2, to distinguish from query and gallery in the single cam case?

**Comment by AsadRahu60** [comment]
Hello every one, I would like to know that in cuhk-03 dataset I was training the LA-transformer  I  dataset split  i am following are 13,131 images in the train set and 1,930 images in the test set (965 in query and 965 in the gallery set).but I am confuse that the query and gallery dataset need to have the different person or the same person images ?
