### ISSUE TITLE
Should I normalize the feature vector?

### ISSUE THREAD

**Issue by GeekAlexis** [KaiyangZhou/deep-person-reid#449]
Do I need to normalize the feature vector before computing the distance for the best matching results? It probably wouldn't matter for cosine distance, but what about euclidean distance required by a model like the pretrained OSNet x025?

Thanks in advance!

**Comment by KaiyangZhou** [comment]
normalization + euclidean distance is equivalent to using cosine similarity

normalizing features in general helps improve the performance, and is highly recommended
