### ISSUE TITLE
RandomIdentitySampler can have a repeating PID

### ISSUE THREAD

**Issue by ergysr** [KaiyangZhou/deep-person-reid#45]
This is a minor issue with the RandomIdentitySampler. The implementation does not necessarily guarantee that the N identities in the batch are unique. For example, ID 28 is sampled twice in this batch.

```
tensor([ 554,  554,  554,  554,  195,  195,  195,  195,  399,  399,
         399,  399,  527,  527,  527,  527,   28,   28,   28,   28,
         501,  501,  501,  501,  252,  252,  252,  252,  136,  136,
         136,  136,  700,  700,  700,  700,  125,  125,  125,  125,
         120,  120,  120,  120,   68,   68,   68,   68,  577,  577,
         577,  577,  455,  455,  455,  455,   28,   28,   28,   28,
           9,    9,    9,    9,  387,  387,  387,  387,  564,  564,
         564,  564], device='cuda:0')
```
Can be reproduced by calling any of the htri demo examples.

**Comment by KaiyangZhou** [comment]
Thanks so much for reporting this. I have updated the [sampler](https://github.com/KaiyangZhou/deep-person-reid/blob/master/torchreid/samplers.py#L42), so person identities are unique in each epoch. Let me know if there is any problem.

**Comment by ergysr** [comment]
Thank you Kaiyang, it appears resolved.
