### ISSUE TITLE
train_vidreid_xent.py: Function argument TypeError occurred when option "evaluation only" is true

### ISSUE THREAD

**Issue by gceboh** [KaiyangZhou/deep-person-reid#46]
**Code Version**
Aug 17, 2018

Command
```
python train_vidreid_xent.py -d ilidsvid -a resnet50  \
--save-dir log/ilidsvid_test-resnet50-xent --gpu-devices 6,7  \
--evaluate --resume log/ilidsvid_train-resnet50-xent/best_model.pth.tar
```
</br>

Error Info
```
Traceback (most recent call last):
  File "train_vidreid_xent.py", line 379, in <module>
    main()
  File "train_vidreid_xent.py", line 200, in main
    distmat = test(model, queryloader, galleryloader, use_gpu, return_distmat=True)
TypeError: test() takes at least 5 arguments (5 given)
```

</br>

**Solution**
It seems that at [train_vidreid_xent.py/line 200](https://github.com/KaiyangZhou/deep-person-reid/blob/cc1e23049ae0c9469d4acc088b7fb55b3af1d714/train_vidreid_xent.py#L200), argument "pool" is missing when invoking the test function:
`distmat = test(model, queryloader, galleryloader, use_gpu, return_distmat=True)`
fix:
`distmat = test(model, queryloader, galleryloader,args.pool, use_gpu, return_distmat=True)`

**Comment by KaiyangZhou** [comment]
good spot, thank you

now fixed
