### ISSUE TITLE
perform inference

### ISSUE THREAD

**Issue by aliceinland** [KaiyangZhou/deep-person-reid#461]
hi! I have trained the OSNet model, saved the weights and now I need to perform inference over a video stream. 
I am not able to find anything on the documentation to understand how to perform this operation. 
Do you have any suggestions or tutorials on how to do that?

**Comment by KaiyangZhou** [comment]
Is this https://kaiyangzhou.github.io/deep-person-reid/user_guide#use-torchreid-as-a-feature-extractor-in-your-projects what you are looking for?

Torchreid doesn't provide interfaces for processing video streams (like person detection).

**Comment by aliceinland** [comment]
Yes, thank you! I will implement the video stream by myself, I just need to pass to the trained network the images (e.g. a numpy array).

**Comment by aliceinland** [comment]
#close 461
