### ISSUE TITLE
HANN中可视化特征图方法求教

### ISSUE THREAD

**Issue by Bo396543018** [KaiyangZhou/deep-person-reid#47]
您好，感谢您的代码，对我这种刚入门的小白帮助很大
请问下像HANN等论文中可视化特征图一般用的是什么方法？

**Comment by KaiyangZhou** [comment]
1) https://github.com/paarthneekhara/convolutional-vqa/blob/master/utils.py#L40

2) https://github.com/kelvinxu/arctic-captions/blob/master/alpha_visualization.ipynb

**Comment by Bo396543018** [comment]
谢谢，明天学习下~
