### ISSUE TITLE
questions for samplers.py and train_vid_xent_htri.py

### ISSUE THREAD

**Issue by ltxue** [KaiyangZhou/deep-person-reid#48]
Hi, my understanding of samplers.py is that you are trying to use every image in data_source, only limitting the identities in each batch.
So I was wondering if there's some problems in train_vid_xent_htri.py when defines RandomIdentitySampler for trainloader: 
RandomIdentitySampler(dataset.train ...
Is it should be:
RandomIdentitySampler(new_train, ...

Thanks very much for your excellent work! It helps me a lot!

**Comment by KaiyangZhou** [comment]
you are right, it was a mistake, thanks for reporting this!
