### ISSUE TITLE
About Reid Dims

### ISSUE THREAD

**Issue by developer0hye** [KaiyangZhou/deep-person-reid#491]
@KaiyangZhou 
Hi! Thanks for sharing your works! I have one question related to feature dimension for reid task.

![image](https://user-images.githubusercontent.com/35001605/152311535-a7a7a377-7710-4fc5-b75a-807b643d7494.png)

Table6 says 64 dimensions are appropriate for reid task. However, I understood that the feature dimensions for reid-task are 128 according to previous section.

![image](https://user-images.githubusercontent.com/35001605/152311653-7e79bf61-5f45-485d-b048-30e22191aeb3.png)

Is there a point that I am missing?

**Comment by KaiyangZhou** [comment]
For JDE, the table indeed suggests 64-dim features work better. Perhaps the paper uses an additional fc layer to map 128-dim features to a 64-dim space.

Which paper you are talking about btw?

**Comment by developer0hye** [comment]
@KaiyangZhou 
Sorry... I made a mistake. I planned to upload this issue on another project.
