### ISSUE TITLE
Automatic download and loading of trained models for feature extraction

### ISSUE THREAD

**Issue by mikel-brostrom** [KaiyangZhou/deep-person-reid#496]
I am only interested in using the already trained models (not the ImageNet pretrained models).
Is there any way of automatically downloading them and loading them for feature extraction?

**Comment by KaiyangZhou** [comment]
maybe this would help https://kaiyangzhou.github.io/deep-person-reid/user_guide#use-torchreid-as-a-feature-extractor-in-your-projects

**Comment by mikel-brostrom** [comment]
I would like the model under

https://github.com/KaiyangZhou/deep-person-reid/blob/40bfa1ae77fc52c5c52e002011e6b33cde30e254/torchreid/utils/feature_extractor.py#L62

to be downloaded automatically. Only pretrained model on ImageNet gets downloaded automatically

**Comment by mikel-brostrom** [comment]
I cannot do the following:

```python
# link found under https://kaiyangzhou.github.io/deep-person-reid/MODEL_ZOO.html
osnet_x1_0_market1501_link = "https://drive.google.com/file/d/1vduhq5DpN2q1g4fYEZfPI17MJeh9qyrA"
output = "osnet_x1_0_market1501"
gdown.download('https://drive.google.com/file/d/1vduhq5DpN2q1g4fYEZfPI17MJeh9qyrA', output, quiet=False)
```

**Comment by KaiyangZhou** [comment]
gdown works, you just need to twist the url link a little bit like using "uc?id="

see https://github.com/wkentaro/gdown for more details

**Comment by mikel-brostrom** [comment]
I get the following error @KaiyangZhou :

```bash
Access denied with the following error:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

         https://drive.google.com/file/d/uc?id=1z1UghYvOTtjx7kEoRfmqSMu-z62J6MAj 
```

when trying:

```python
# link found under https://kaiyangzhou.github.io/deep-person-reid/MODEL_ZOO.html
osnet_x1_0_market1501_link = "https://drive.google.com/file/d/1vduhq5DpN2q1g4fYEZfPI17MJeh9qyrA"
output = "osnet_x1_0_market1501"
gdown.download('https://drive.google.com/file/d/uc?id=1vduhq5DpN2q1g4fYEZfPI17MJeh9qyrA', output, quiet=False) 
```

`https://drive.google.com/file/uc?id=1z1UghYvOTtjx7kEoRfmqSMu-z62J6MAj` did not work either

**Comment by mikel-brostrom** [comment]
Fixed it! Should be:
`https://drive.google.com/uc?id=1z1UghYvOTtjx7kEoRfmqSMu-z62J6MAj`
