### ISSUE TITLE
Do you have time consuming log?

### ISSUE THREAD

**Issue by lzhaozi** [KaiyangZhou/deep-person-reid#5]
Thank you for your great work in person reidentification. It makes clear which model can perform what performance from the table. And I want to ask, if you have stored the time consuming log of these models? Can you share the time consuming (such as, forward time/batch size) log?
Thank you again for your great work.

Yours,
Hao

**Comment by KaiyangZhou** [comment]
Unfortunately, I did not include this information during training.

**Comment by lzhaozi** [comment]
Thank you very much~

**Comment by lzhaozi** [comment]
Thanks a lot~~
