### ISSUE TITLE
ReID model trainning on a custom dataset (Waymo's perception dataset)

### ISSUE THREAD

**Issue by ZePinto99** [KaiyangZhou/deep-person-reid#508]
I'm trying to train a ReID model on a custom dataset (a subset of Waymo's perception dataset https://github.com/waymo-research/waymo-open-dataset). This dataset contains images with multiple classes (pedestrians,  cyclysts and vehicles) and each label has an id parameter with the object id, the object type, the bounding box coordinates and demensions (https://github.com/waymo-research/waymo-open-dataset/blob/master/waymo_open_dataset/label.proto). How can I prepare this dataset so then I can use it as explained on "Use your own dataset" section of https://kaiyangzhou.github.io/deep-person-reid/user_guide.html#id18.
My question is oriented to how must I store the images and labels so that the dataset is ready for trainning a REID model.

**Comment by KaiyangZhou** [comment]
If the id labels are unique, meaning that each person identity's id is correctly labeled, what you need is to write a code to extract the person images (using the bbox annotation) and store in a folder, which might look like:
```
folder/
    person_001_001.jpg  # person_x_y: x means the identity and y means the y-th image for person-x
    person_001_002.jpg
    person_002_001.jpg
    ...
```

Then you write a dataset class following the instruction, i.e., "Use your own dataset."

Finally, choose a re-id model and run the code.

Highly suggest you use the pre-trained OSNet or OSNetAIN model, which is effective beyond re-id (see this thread https://twitter.com/kaiyangzhou/status/1517749618645553153)

**Comment by KaiyangZhou** [comment]
Also suggest you take a look at this repo https://github.com/GeekAlexis/FastMOT, which is an example of using OSNet for your own application.

**Comment by ZePinto99** [comment]
Thanks for the  help! I will take a look on that repo.
