### ISSUE TITLE
Error while training on custom dataset

### ISSUE THREAD

**Issue by abhaykumart12** [KaiyangZhou/deep-person-reid#537]
While I was training with my Custom dataset I got the following error:
![1](https://user-images.githubusercontent.com/114352053/224614946-6fdce126-6b58-4f7d-bdbd-93d1c2fc6742.png)
![2](https://user-images.githubusercontent.com/114352053/224614976-8067a209-340e-48d0-8847-21ab9dd21b23.png)

could you please help me regarding the same?

**Comment by abhaykumart12** [comment]
fixed the error.
had to relabel the training set.
thanks!

**Comment by muhammad-usama-aleem** [comment]
@abhaykumart12 can you please share the dataset? the given dataset urls are not available
