### ISSUE TITLE
how do you improve the benchmark of MobilenetV2 from 77% to 84% on Market?

### ISSUE THREAD

**Issue by BJTUJia** [KaiyangZhou/deep-person-reid#54]
Dear Author, Thanks a lot for your excellent work. If I remember correctly, the initial results you posted for MobileNetV2 is around 77% on Market1501. The benchmark now https://github.com/KaiyangZhou/deep-person-reid/blob/master/BENCHMARK.md is much higher, can you instruct me on how to boost the performance of MobileNetV2? Did you use different hyperparameter setting? Thanks a lot!

**Comment by KaiyangZhou** [comment]
https://github.com/KaiyangZhou/deep-person-reid/issues/7#issuecomment-387051156 this should work
