### ISSUE TITLE
calculate the forward time

### ISSUE THREAD

**Issue by Adorablepet** [KaiyangZhou/deep-person-reid#55]
HACNN: The model has been trained and then used to extract features, but each time it takes 0.0267s, I want to ask if it is a problem, and it takes a long time.
'''
start = time.clock()
features = module()
finish = time.clock()
print('running time: %s seconds' %(finish - start))

'''

**Comment by Adorablepet** [comment]
@KaiyangZhou Can you answer my doubts? And what formula is used to calculate distmat? What is the main meaning of it? Thank you very much.

**Comment by KaiyangZhou** [comment]
the processing time depends on the batch size and computing device.

dismat is computed by L2 distance, you can also use cosine similarity, which might bring some benefits in computation efficiency, but the results would not differ too much.

**Comment by Adorablepet** [comment]
@KaiyangZhou 
GPU：titan xp
In the same environment, the size of batchsize and input are the same, and the parameters of resnet50 are more than hacnn. If normal, the processing time of resnet50 is longer than hacnn. However, I have done a comparison and found that the processing time of resnet50 is 12-18ms, and hacnn is about 27ms. This is inconsistent with the results obtained by the paper. If the parameters are small, the processing time should be faster.
