### ISSUE TITLE
about the comparison of features of query with the test images.

### ISSUE THREAD

**Issue by naren142** [KaiyangZhou/deep-person-reid#56]
Where are you comparing the features of the query images with the test(Gallery) images?I can see "distmat" variable in the code of test part but not sure how you are matching and selecting  the top 20 images.And also how to check a single image each time with the gallery of images to match features? 
Thanks.

**Comment by KaiyangZhou** [comment]
the computation of distance matrix is done inside `test(...)`, the code should be easy to understand.

the visualization is done here https://github.com/KaiyangZhou/deep-person-reid/blob/master/torchreid/utils/reidtools.py#L12, please check the code for more details.

**Comment by naren142** [comment]
okay got it.

**Comment by naren142** [comment]
Hi....the time for a single query image with 15 images in test(gallery set)
is taking 1 sec approximately.Is there any way to reduce this time?
Thanks.

**Comment by yancccc** [comment]
> okay got it.



> the computation of distance matrix is done inside `test(...)`, the code should be easy to understand.
> 
> the visualization is done here https://github.com/KaiyangZhou/deep-person-reid/blob/master/torchreid/utils/reidtools.py#L12, please check the code for more details.

请问楼主，这个reidtools.py怎么使用呢
