### ISSUE TITLE
Weights on MARS

### ISSUE THREAD

**Issue by AlekseySh** [KaiyangZhou/deep-person-reid#57]
Hello and thank you for your code! 
Can you share weights for networks trained on MARS dataset?

**Comment by KaiyangZhou** [comment]
hi, i don't have weights trained for mars at this moment

**Comment by ciwei123** [comment]
@KaiyangZhou @AlekseySh Hi, We can not trained in Mars,right? Because we don't have the pre-trained in Mars.(I think the “pre-training model” means the initialization of the parameters. And the "trained model" means we have trained some epochs which has a good test rusult . I understand it right?)
