### ISSUE TITLE
set the parametres with densenet121

### ISSUE THREAD

**Issue by Adorablepet** [KaiyangZhou/deep-person-reid#58]
Thanks for you code.I have a question.

The script for 'xent + htri ' of densenet121:
python3.5 train_imgreid_xent_htri.py -d market1501 -a densenet121 --lr 0.0003 --max-epoch 180 --stepsize 60 --train-batch 32 --test-batch 32 --save-dir logs/densenet121-xent-htri-market1501 --gpu-devices 0,1,2,3

But mAP is 60.8%, Rank-1 is 80.0%.A little different from the data you provided.Can you tell me where this script is wrong?

**Comment by Adorablepet** [comment]
@KaiyangZhou Can you tell me how to effectively set the training parameters, each model has different parameters, such as max-epoch, lr, stepsize and so on.I want to train inceptionresnetv2.py. I train the default parametres, but the mAP is 63.6%, the Rank-1 is 81.2%.Can you give me some advice? Thank you very much.

**Comment by KaiyangZhou** [comment]
regarding the command to train densenet121 with xent+htri: lr=0.00065, margin=0.3, optim=amsgrad, stepsize=[20, 40], trainbatch=64, maxepoch=60. I guess your model overfitted to the data so you got worse results.

there is no absolute rules for training params, empirically, i would say use less epochs for imagenet pretrained big models e.g. resnet. you can always try 'maxepoch=60, stepsize=[20, 40], optim=adam or amsgrad, lr=0.0003, batchsize=32' for those models, which i found was quite useful. if you wanna train models from scratch, then use more epochs, also, sgd might be a better choice for training from scratch.

as i remember, inceptionresnetv2 was too big to train on reid datasets, i got similar performance so did not release the trained weights. for research, use resnet50 or densenet121 as the baselines, which could give pretty good results.

**Comment by Adorablepet** [comment]
@KaiyangZhou First of all, thank you for answering my question. Now I have another question. Which version of the inception unit used in the hacnn model is used. If the calculation of the forward operation time is slow, will it be related to this inception?Thanks again.
