### ISSUE TITLE
Bug in mars split

### ISSUE THREAD

**Issue by AlekseySh** [KaiyangZhou/deep-person-reid#59]
Look like I found the problem in MARS dataset split. For some queries, I can't found right answers in the gallery, (and vice versa). Does anyone have the ​same problem? 

=====================================

import numpy as np
from scipy.io import loadmat

q = loadmat('/media/re-id/datasets/mars/info/query_IDX.mat')['query_IDX'][0]
t = loadmat('/media/re-id/datasets/mars/info/tracks_test_info.mat')['track_test_info']

query_inds = q - 1
gallery_inds = [i for i in range(len(t)) if i not in query_inds]

query_pids = t[query_inds , 2]
gallery_pids = t[gallery_inds, 2]

print('This person ids only in query')
print(np.setdiff1d(query_pids, gallery_pids))
print()
print('This pids only in gallery')
print(np.setdiff1d(gallery_pids, query_pids))

============================================

This person ids only in query
[   6  152  436  454  640  782  944 1062 1138 1140 1146 1172 1252 1444]

This pids only in gallery
[  -1    0   12   14  154  166  982 1034 1104 1354]

**Comment by KaiyangZhou** [comment]
i tried a simple test with the following code
```
from torchreid import data_manager

dataset = data_manager.init_vidreid_dataset(name='mars', verbose=False)

print(">>>>>>>>>>>> test")

q_pids = set()
for _, pid, _ in dataset.query:
    q_pids.add(pid)

g_pids = set()
for _, pid, _ in dataset.gallery:
    g_pids.add(pid)

has_error = False
for pid in q_pids:
    if pid not in g_pids:
        print("pid {} is not found in gallery".format(pid))
        has_error = True

print("has_error = {}".format(has_error))
```

my output is
```
>>>>>>>>>>>> test
pid 6 is not found in gallery
pid 152 is not found in gallery
pid 436 is not found in gallery
pid 454 is not found in gallery
pid 640 is not found in gallery
pid 782 is not found in gallery
pid 944 is not found in gallery
pid 1062 is not found in gallery
pid 1138 is not found in gallery
pid 1140 is not found in gallery
pid 1146 is not found in gallery
pid 1172 is not found in gallery
pid 1252 is not found in gallery
pid 1444 is not found in gallery
has_error = True
```
where the missing ids are identical to yours

i will inform the author of mars regarding this issue

**Comment by weleen** [comment]
I met the same problem, and how about the response from the author? @AlekseySh 
And in the [original paper](http://www.liangzheng.com.cn/1320.pdf), there are 631 and 630 ids in train and test split, now is 625 and 636 respectively, as reported in the author's homepage.

**Comment by AlekseySh** [comment]
Unfortunately, the authors are silent.
