### ISSUE TITLE
[bug] 'best_rank1' and 'best_epoch' may be wrong when resuming from a saved model

### ISSUE THREAD

**Issue by gceboh** [KaiyangZhou/deep-person-reid#63]
After user resumed from a saved model, the value of `best_rank1` and `best_epoch` may be wrong (The wrong values will be recorded in the log).
And in some cases, it may cause previously saved best model (`best_model.pth.tar`) to be falsely overwritten during the subsequent training process.

### Fix
https://github.com/KaiyangZhou/deep-person-reid/pull/62

### Warning
this fix is **incompatible** with saved models created by old versions.

**Comment by KaiyangZhou** [comment]
good spot, thx, updated now
