### ISSUE TITLE
[bug] When resume from a model, the value of "start epoch" counter is wrong

### ISSUE THREAD

**Issue by gceboh** [KaiyangZhou/deep-person-reid#64]
When resume from a model, the value of "start epoch" counter is wrong

### Solution
This line 
https://github.com/KaiyangZhou/deep-person-reid/blob/4bf76590dfa71721714d16bfbb89aa463db18d12/train_imgreid_xent.py#L200

fix:
`args.start_epoch = checkpoint['epoch'] + 1`

### Reason
1.When saving a check point,`current epoch` is recorded.
https://github.com/KaiyangZhou/deep-person-reid/blob/4bf76590dfa71721714d16bfbb89aa463db18d12/train_imgreid_xent.py#L260

2.After resuming,it should begin at (`current epoch+1`), because  [the FOR loop](https://github.com/KaiyangZhou/deep-person-reid/blob/4bf76590dfa71721714d16bfbb89aa463db18d12/train_imgreid_xent.py#L236) begins at "args.start_epoch".

**Comment by KaiyangZhou** [comment]
updated, thx
