### ISSUE TITLE
How to draw attention regions and heat map?

### ISSUE THREAD

**Issue by liliangqi** [KaiyangZhou/deep-person-reid#67]
Hi, I'm using your model to implement HA-CNN. Thank you for you excellent work first.
And now I want to draw attention regions and heat maps as shown in Fig.6 of [HA-CNN paper](https://arxiv.org/abs/1802.08122).

1. Soft attention. There are three kinds of attention maps with different scales in the model. They are 1/4, 1/16, 1/32 to the input image (say, the first attention map of 80x32 compared to the input image of 160x64). How should I use them to draw the heat map on the original input image? Does interpolation work?

2. Hard attention. The affine transformation coefficients tx and ty would be produced by the "stn" in the model. But how can I get the exact attention region **location** using these two coefficients?

**Comment by KaiyangZhou** [comment]
1. use cv2.resize with bilinear interpolation.

2. do `stn(original_input, obtained_theta)` and visualise the output

**Comment by liliangqi** [comment]
Cool, thanks

**Comment by 240084173** [comment]
Hi, when I try to draw the hard attention regions, I meet with a problem,what does the original_input in stn(original_input, obtained_theta) mean? the original input image or the convolution features？ Can you show me your visualization code? Thanks !
