### ISSUE TITLE
Parameters of the FC layers of HACNN

### ISSUE THREAD

**Issue by liliangqi** [KaiyangZhou/deep-person-reid#68]
Hi, I noted you initialize the FC bias of HardAttn module with [0, -0.75, 0, -0.25, 0, 0.25, 0, 0.75] [here](https://github.com/KaiyangZhou/deep-person-reid/blob/master/torchreid/models/hacnn.py#L165). Why do you assign them with such values? There are four attention regions in your code, so the number of the FC units are 8. But once I want to produce three attention regions with 6 units in the corresponding FC layer, how should I initialize the FC bias?

**Comment by KaiyangZhou** [comment]
Those values lead to better initialization, i.e. the four bboxes can cover the four horizontal image regions (the original paper allowed little overlaps).
