### ISSUE TITLE
When I run train_imgreid_xent.py , it shows some problem.

### ISSUE THREAD

**Issue by ViousGod** [KaiyangZhou/deep-person-reid#70]
UnboundLocalError: local variable 'best_rank1' referenced before assignment

How can I fix it?

Thank you.

**Comment by ViousGod** [comment]
I solve this problem!

I add the "global" to the best_rank, then it solves.

**Comment by ViousGod** [comment]
like this "global best_rank1"

**Comment by KaiyangZhou** [comment]
which python version are you using?

**Comment by KaiyangZhou** [comment]
i know where the error comes from, best_rank1 is reassigned if you do --load-weights

will fix this
