### ISSUE TITLE
training settings for cuhk03

### ISSUE THREAD

**Issue by SpONA** [KaiyangZhou/deep-person-reid#71]

**Comment by KaiyangZhou** [comment]
more details can be found here https://github.com/KaiyangZhou/deep-person-reid/blob/master/DATASETS.md

**Comment by SpONA** [comment]
Thank you so much~ 

----- 原始邮件 -----
发件人: "Kaiyang" <notifications@github.com>
收件人: "KaiyangZhou/deep-person-reid" <deep-person-reid@noreply.github.com>
抄送: "SpONA" <spofnewage@sjtu.edu.cn>, "Author" <author@noreply.github.com>
发送时间: 星期六, 2018年 10 月 27日 上午 12:50:34
主题: Re: [KaiyangZhou/deep-person-reid] training settings for cuhk03 (#71)

Closed #71.

-- 
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub:
https://github.com/KaiyangZhou/deep-person-reid/issues/71#event-1929330793
