### ISSUE TITLE
Does this project have a corresponding paper?

### ISSUE THREAD

**Issue by 695874419** [KaiyangZhou/deep-person-reid#73]
Does this project have a corresponding paper?

**Comment by KaiyangZhou** [comment]
coming soon ...

will add more useful features as well, stay tuned

**Comment by InnovArul** [comment]
Hi, Is the paper out already?

**Comment by KaiyangZhou** [comment]
It's under review. Will be out very soon :)

**Comment by InnovArul** [comment]
Thanks for your reply!
I am not sure if its possible for you to publish in arxiv? 
It will be convenient to cite the results :)

**Comment by KaiyangZhou** [comment]
https://arxiv.org/abs/1905.00953
