### ISSUE TITLE
about the args.py

### ISSUE THREAD

**Issue by wangminjie920705** [KaiyangZhou/deep-person-reid#78]
Mr Zhou, I have a simple question to ask you in args.py.
![image](https://user-images.githubusercontent.com/40478079/49065907-662cf180-f25a-11e8-9c75-40c37f33a3ff.png)
![image](https://user-images.githubusercontent.com/40478079/49065942-7fce3900-f25a-11e8-8679-5de65114beb8.png)
the"source-names"and"source_names"  is  difference ,why? Thanks you!

**Comment by KaiyangZhou** [comment]
`-` will be automatically converted to `_` to make sure the attribute name is valid. Pls see [argparse docs](https://docs.python.org/dev/library/argparse.html#dest).

**Comment by wangminjie920705** [comment]
thank you
