### ISSUE TITLE
ResNeXt baseline

### ISSUE THREAD

**Issue by 0-oo-0** [KaiyangZhou/deep-person-reid#8]
Hi,  would you please add [ResNeXt](https://github.com/facebookresearch/ResNeXt) as baseline?

**Comment by KaiyangZhou** [comment]
Will do it later.

**Comment by 0-oo-0** [comment]
Nice.
According to [this paper](http://homepages.inf.ed.ac.uk/thospeda/papers/chang2018mlfn.pdf), the ResNeXt is able to achieve rank-1: 88.0, map: 69.8 on Market1501(at the top of page 8 in paper).
I attempt to reproduce, but failed. Thank you.
Besides, [it](http://homepages.inf.ed.ac.uk/thospeda/papers/chang2018mlfn.pdf) is a good work , in my opinion.

**Comment by KaiyangZhou** [comment]
I agree. It is an insightful paper, coming from our group. :)

**Comment by 0-oo-0** [comment]
hahaha. Interesting...
