### ISSUE TITLE
the person detector of the mlfn model？

### ISSUE THREAD

**Issue by Adorablepet** [KaiyangZhou/deep-person-reid#80]
I am very embarrassed to bother you again. I am also looking at the 2018 paper on the mlfn model. After inputting a picture, it and how to judge visual features such as color, clothes, gender, etc. I saw a DPM detector in the paper. Is this used? Is the accuracy of the extracted colors, clothes, and gender attributes 81% of the paper? Thanks!

**Comment by KaiyangZhou** [comment]
In the mlfn paper, the images of similar persons (in terms of color and texture) are obtained by grouping the learned factor selection features. For more details regarding the paper, please contact the author.
