### ISSUE TITLE
set parameter of the mlfn model

### ISSUE THREAD

**Issue by Adorablepet** [KaiyangZhou/deep-person-reid#82]
Sorry to bother you again, when I train mlfn, set the parameters as follows:
-s market1501 -t market1501 --height 256 --width  128 --optim adam  --lr 0.00035 --max-epoch 100 --stepsize 50 75 --train-batch-size 64 --test-batch-size 100 -a mlfn
The result is mAP: 74.1%, top-1: 89.2, which is a little different from the results of the paper. I would like to ask if the parameter is set incorrectly.Some parameters are set in  the paper. How is the parameter of the stepsize controlled?50%-75%?33.3%-66.7%?Thanks!

**Comment by KaiyangZhou** [comment]
the training script is provided in the model zoo, pls download the zip file
