### ISSUE TITLE
A minor mistake in README.md

### ISSUE THREAD

**Issue by foolishflyfox** [KaiyangZhou/deep-person-reid#83]
I just find there is a minor mistake in README.md, in the Tutorial section and Train part:

- `train_imgreid_xent.py`: train image-reid models with cross entropy loss.
- `train_imgreid_xent_htri.py`: train image-reid models with hard mining triplet loss or the combination of hard mining triplet loss and cross entropy loss.
- `train_imgreid_xent.py`: train video-reid models with cross entropy loss.
- `train_imgreid_xent_htri.py`: train video-reid models with hard mining triplet loss or the combination of hard mining triplet loss and cross entropy loss.

The last two item seems should be : `train_vidreid_xent.py` and `train_vidreid_xent_htri.py`

**Comment by KaiyangZhou** [comment]
thank you, it is fixed now
