### ISSUE TITLE
how to test a custom image or video?

### ISSUE THREAD

**Issue by chunniunai220ml** [KaiyangZhou/deep-person-reid#85]
Hi,
I am a little confused with the code,it seems just for public dataset. If i want to test a custom image,how to extract the features? I load the se_resnet50, and  print key as follows:
layer4.2.se_module.fc1.weight
layer4.2.se_module.fc1.bias
layer4.2.se_module.fc2.weight
layer4.2.se_module.fc2.bias
fc.0.weight
fc.0.bias
fc.1.weight
fc.1.bias
fc.1.running_mean
fc.1.running_var
classifier.weight
classifier.bias

but, I do not konw i should pick which layer to extract features for distance computation.

**Comment by KaiyangZhou** [comment]
Normally, you extract features from the last layer (before the classification layer). In the case of se_resnet50_fc512, you can extract features from `self.fc`. Pls refer to [this code](https://github.com/KaiyangZhou/deep-person-reid/blob/master/torchreid/models/senet.py#L404).

This project is developed for academic purpose so we mainly do experiments on public benchmark datasets.

**Comment by chunniunai220ml** [comment]
THX so much! I have extracted feaures by th code if not self.training:  return v. I print the features like :: 
![image](https://user-images.githubusercontent.com/17668109/49622093-15a85780-fa03-11e8-831e-58985ab7b9fc.png)

it seems not L2 nomarlization, so I am not sure the extracted-features is right?

**Comment by KaiyangZhou** [comment]
L2-norm is not a must, the performance would not differ too much between w/ and w/o L2-norm.

**Comment by sahilrider** [comment]
@chunniunai220ml Were you able to test on a custom image or video?
