### ISSUE TITLE
[Tiny Bug] lower limit of 'train-batch-size' argument

### ISSUE THREAD

**Issue by gceboh** [KaiyangZhou/deep-person-reid#87]
Video based Re-ID is very memory cosuming (especially when sequence length is long).Due to limited GPU  resource and large model size,some user may set train batch size to a very small value.
If 'hard mining triplet loss' is enabled, and `train-batch-size` is wrongly set to value `2` or `1` (lower than `3`),triplet loss may work incorrectly.

Fix:
I suggest give some warning info when the argument is wrong.

**Comment by KaiyangZhou** [comment]
current training of video reid follows the image based paradigm so it is independent of the seq length

anyway, i will add some comments to readme to avoid confusion

thanks
