### ISSUE TITLE
KeyError: "Invalid dataset, got 'mooth',

### ISSUE THREAD

**Issue by ezreal1129** [KaiyangZhou/deep-person-reid#89]
when i run the train_imgreid_xent.py ,the result appeared 'KeyError: "Invalid dataset, got 'mooth', but expected to be one of ['cuhk03', 'viper', 'market1501', 'sensereid', 'dukemtmcreid', 'cuhk01', 'grid', 'msmt17', 'prid450s', 'ilids']"'.the parameters which i inputs are ‘python train_imgreid_xent.py -s market1501 -t market1501 --height 256 --width 128 --optim amsgrad --label -smooth --lr 0.0003 --max-epoch 60 --stepsize 20 40 --train-batch-size 32 --test-batch-size 100 -a resnet50 --save-dir log/exp1 --gpu-devices 0’,

so how to solve it ?
@KaiyangZhou

**Comment by KaiyangZhou** [comment]
change `--label -smooth` to `--label-smooth` (no space in between)

**Comment by ezreal1129** [comment]
@

> change `--label -smooth` to `--label-smooth` (no space in between)
it's ok .thanks a lot
