### ISSUE TITLE
hyperparameters for ResNet50m + xent + htri 

### ISSUE THREAD

**Issue by RQuispeC** [KaiyangZhou/deep-person-reid#9]
Dear author.

Can you publish the hyperparameters you used to get 90.7| 97.0| 98.2| 76.8 (rank1, rank5, rank10, mAP) in market1501?, I have tried with the default configuration and only got 81.4| 92.5| 95.4| 62.7. it gets stuck in this point.

Thanks a lot for the great work! :)

**Comment by KaiyangZhou** [comment]
I used the default setting as well. Please try again.

**Comment by RQuispeC** [comment]
I try again and got the same results, I was using --stepsize = 20 and it seems that it is the reason :) 

Thanks!!

**Comment by KaiyangZhou** [comment]
Good.

The lr starts from 3e-4, so maximally it can be decayed twice by 0.1 (more decays turned out to be useless as the model would not update anymore with too small lr).
