### ISSUE TITLE
re-ranking

### ISSUE THREAD

**Issue by wzjiang** [KaiyangZhou/deep-person-reid#91]
Thank you for your great work. Could you provide the re-ranking code？

**Comment by gceboh** [comment]
May be [these code](https://github.com/daizuozhuo/batch-feature-erasing-network/blob/9257fbd3a5d2569cdf9a7f7bbbbe1f24b3c518eb/trainers/evaluator.py#L93) will be useful, which has integrated re-ranking algorithm into distance matrix computing .
@KaiyangZhou

**Comment by KaiyangZhou** [comment]
The reranking code has been added https://github.com/KaiyangZhou/deep-person-reid/commit/5839a026c3aeebce260cbf1127a1d18c2714be96.

It's copied from https://github.com/zhunzhong07/person-re-ranking.

Credit to: @zhunzhong07 @michuanhaohao @huanghoujing

How to use:
1. If you are using your own script, set `rerank=True` in `engine.run()` (`test_only` also needs to be set to True).
2. If you are using `deep-person-reid/scripts/main.py`, do `--evaluate --rerank`. Note that rerank can only be enabled when `test_only=True`.

**Comment by KaiyangZhou** [comment]
For sanity check, the performance of `resnet50` (available in the model zoo) with and without using `rerank` is reported as follows

| Rerank | top1 | mAP |
| :--: | :--: | :--: |
| False | 87.9 | 70.4 |
| True | 89.5 | 84.5 |
