### ISSUE TITLE
Where can I find the trained model 

### ISSUE THREAD

**Issue by ciwei123** [KaiyangZhou/deep-person-reid#96]
Where can I find the trained model of  the result in  MODEL_ZOO ?Thank you very much! @KaiyangZhou

**Comment by KaiyangZhou** [comment]
just click the highlighted numbers and magic will happen

**Comment by NightFury10497** [comment]
Yes, Click on that and you will be able to download the Pre-Trained Models.

**Comment by ciwei123** [comment]
@NightFury10497 Yes!But I want to get a trained well model not a pre-trained model.

**Comment by ciwei123** [comment]
@KaiyangZhou @NightFury10497 I can find three dataset pre-trained model in MODEL_ZOO which are used for image reid. I want to train in Mars dataset , where can I find the pre-trained model for vedio reid?Thank you very much!!
