### ISSUE TITLE
How use the feature of images?

### ISSUE THREAD

**Issue by ciwei123** [KaiyangZhou/deep-person-reid#98]
@KaiyangZhou Thank you for sharing. I have got the feature of image during test, now I want to use the feature for tracking. How to compare the feature?  What evaluation indicators do you use?Looking for your reply. Thank you very much.

**Comment by ciwei123** [comment]
@KaiyangZhou 我想用训练好的模型测试两张图片，得到特征后，利用“距离计算”计算两个特征相似度，从而说明这两个图片是否是同一个人，这样可行吗？　　因为基础网络是分类网络，这样做效果会不会很差？“距离计算”用什么度量比较好，欧式距离，余弦距离还是其他的方式？

**Comment by ciwei123** [comment]
@KaiyangZhou Thanks for your reply. I just use the "features" to compute distance? How to understand  the following codes?
  "   m, n = qf.size(0), gf.size(0)
     distmat = torch.pow(qf, 2).sum(dim=1, keepdim=True).expand(m, n) + \
              torch.pow(gf, 2).sum(dim=1, keepdim=True).expand(n, m).t()
　“
Should Ｉuse the variable“features” or the variable "distmat" ?Could you tell me the evaluation method of this code? I can not understand the" Funtion evaluate".

**Comment by ciwei123** [comment]
@KaiyangZhou I think the scores of the assessment are very high, so I want to  use the evaluation method to generate a distance matrix.

**Comment by KaiyangZhou** [comment]
The code you referred to is for computing the L2 distance given two feature matrices.

I have no context information regarding what you are doing so I could not provide too much help beyond this reid project. Sorry about that.
